import pymcnp
from ... import consts
from ... import classes


class Test_Header:
    class Test_Init(classes.Test_Init):
        element = pymcnp.meshtal.Header
        EXAMPLES_VALID = [
            {
                'code': consts.ast.types.STRING,
                'version': consts.ast.types.STRING,
                'ld': consts.ast.types.STRING,
                'probid': consts.ast.types.STRING,
                'title': consts.ast.types.STRING,
                'histories': consts.ast.types.INTEGER,
                'number': consts.ast.types.INTEGER,
                'particle': consts.ast.types.STRING,
                'columns': consts.ast.types.STRING,
                'bins_x': consts.ast.types.STRING,
                'bins_y': consts.ast.types.STRING,
                'bins_z': consts.ast.types.STRING,
                'bins_energy': consts.ast.types.STRING,
                'bins_time': consts.ast.types.STRING,
            },
            {
                'code': consts.ast.types.STRING,
                'version': consts.ast.types.STRING,
                'ld': consts.ast.types.STRING,
                'probid': consts.ast.types.STRING,
                'title': consts.ast.types.STRING,
                'histories': consts.ast.types.INTEGER,
                'number': consts.ast.types.INTEGER,
                'particle': consts.ast.types.STRING,
                'columns': consts.ast.types.STRING,
                'bins_x': None,
                'bins_y': consts.ast.types.STRING,
                'bins_z': consts.ast.types.STRING,
                'bins_energy': consts.ast.types.STRING,
                'bins_time': consts.ast.types.STRING,
            },
            {
                'code': consts.ast.types.STRING,
                'version': consts.ast.types.STRING,
                'ld': consts.ast.types.STRING,
                'probid': consts.ast.types.STRING,
                'title': consts.ast.types.STRING,
                'histories': consts.ast.types.INTEGER,
                'number': consts.ast.types.INTEGER,
                'particle': consts.ast.types.STRING,
                'columns': consts.ast.types.STRING,
                'bins_x': consts.ast.types.STRING,
                'bins_y': None,
                'bins_z': consts.ast.types.STRING,
                'bins_energy': consts.ast.types.STRING,
                'bins_time': consts.ast.types.STRING,
            },
            {
                'code': consts.ast.types.STRING,
                'version': consts.ast.types.STRING,
                'ld': consts.ast.types.STRING,
                'probid': consts.ast.types.STRING,
                'title': consts.ast.types.STRING,
                'histories': consts.ast.types.INTEGER,
                'number': consts.ast.types.INTEGER,
                'particle': consts.ast.types.STRING,
                'columns': consts.ast.types.STRING,
                'bins_x': consts.ast.types.STRING,
                'bins_y': consts.ast.types.STRING,
                'bins_z': None,
                'bins_energy': consts.ast.types.STRING,
                'bins_time': consts.ast.types.STRING,
            },
            {
                'code': consts.ast.types.STRING,
                'version': consts.ast.types.STRING,
                'ld': consts.ast.types.STRING,
                'probid': consts.ast.types.STRING,
                'title': consts.ast.types.STRING,
                'histories': consts.ast.types.INTEGER,
                'number': consts.ast.types.INTEGER,
                'particle': consts.ast.types.STRING,
                'columns': consts.ast.types.STRING,
                'bins_x': consts.ast.types.STRING,
                'bins_y': consts.ast.types.STRING,
                'bins_z': consts.ast.types.STRING,
                'bins_energy': None,
                'bins_time': consts.ast.types.STRING,
            },
            {
                'code': consts.ast.types.STRING,
                'version': consts.ast.types.STRING,
                'ld': consts.ast.types.STRING,
                'probid': consts.ast.types.STRING,
                'title': consts.ast.types.STRING,
                'histories': consts.ast.types.INTEGER,
                'number': consts.ast.types.INTEGER,
                'particle': consts.ast.types.STRING,
                'columns': consts.ast.types.STRING,
                'bins_x': consts.ast.types.STRING,
                'bins_y': consts.ast.types.STRING,
                'bins_z': consts.ast.types.STRING,
                'bins_energy': consts.ast.types.STRING,
                'bins_time': None,
            },
        ]
        EXAMPLES_INVALID = [
            {
                'code': None,
                'version': consts.ast.types.STRING,
                'ld': consts.ast.types.STRING,
                'probid': consts.ast.types.STRING,
                'title': consts.ast.types.STRING,
                'histories': consts.ast.types.INTEGER,
                'number': consts.ast.types.INTEGER,
                'particle': consts.ast.types.STRING,
                'columns': consts.ast.types.STRING,
                'bins_x': consts.ast.types.STRING,
                'bins_y': consts.ast.types.STRING,
                'bins_z': consts.ast.types.STRING,
                'bins_energy': consts.ast.types.STRING,
                'bins_time': consts.ast.types.STRING,
            },
            {
                'code': consts.ast.types.STRING,
                'version': None,
                'ld': consts.ast.types.STRING,
                'probid': consts.ast.types.STRING,
                'title': consts.ast.types.STRING,
                'histories': consts.ast.types.INTEGER,
                'number': consts.ast.types.INTEGER,
                'particle': consts.ast.types.STRING,
                'columns': consts.ast.types.STRING,
                'bins_x': consts.ast.types.STRING,
                'bins_y': consts.ast.types.STRING,
                'bins_z': consts.ast.types.STRING,
                'bins_energy': consts.ast.types.STRING,
                'bins_time': consts.ast.types.STRING,
            },
            {
                'code': consts.ast.types.STRING,
                'version': consts.ast.types.STRING,
                'ld': None,
                'probid': consts.ast.types.STRING,
                'title': consts.ast.types.STRING,
                'histories': consts.ast.types.INTEGER,
                'number': consts.ast.types.INTEGER,
                'particle': consts.ast.types.STRING,
                'columns': consts.ast.types.STRING,
                'bins_x': consts.ast.types.STRING,
                'bins_y': consts.ast.types.STRING,
                'bins_z': consts.ast.types.STRING,
                'bins_energy': consts.ast.types.STRING,
                'bins_time': consts.ast.types.STRING,
            },
            {
                'code': consts.ast.types.STRING,
                'version': consts.ast.types.STRING,
                'ld': consts.ast.types.STRING,
                'probid': None,
                'title': consts.ast.types.STRING,
                'histories': consts.ast.types.INTEGER,
                'number': consts.ast.types.INTEGER,
                'particle': consts.ast.types.STRING,
                'columns': consts.ast.types.STRING,
                'bins_x': consts.ast.types.STRING,
                'bins_y': consts.ast.types.STRING,
                'bins_z': consts.ast.types.STRING,
                'bins_energy': consts.ast.types.STRING,
                'bins_time': consts.ast.types.STRING,
            },
            {
                'code': consts.ast.types.STRING,
                'version': consts.ast.types.STRING,
                'ld': consts.ast.types.STRING,
                'probid': consts.ast.types.STRING,
                'title': None,
                'histories': consts.ast.types.INTEGER,
                'number': consts.ast.types.INTEGER,
                'particle': consts.ast.types.STRING,
                'columns': consts.ast.types.STRING,
                'bins_x': consts.ast.types.STRING,
                'bins_y': consts.ast.types.STRING,
                'bins_z': consts.ast.types.STRING,
                'bins_energy': consts.ast.types.STRING,
                'bins_time': consts.ast.types.STRING,
            },
            {
                'code': consts.ast.types.STRING,
                'version': consts.ast.types.STRING,
                'ld': consts.ast.types.STRING,
                'probid': consts.ast.types.STRING,
                'title': consts.ast.types.STRING,
                'histories': None,
                'number': consts.ast.types.INTEGER,
                'particle': consts.ast.types.STRING,
                'columns': consts.ast.types.STRING,
                'bins_x': consts.ast.types.STRING,
                'bins_y': consts.ast.types.STRING,
                'bins_z': consts.ast.types.STRING,
                'bins_energy': consts.ast.types.STRING,
                'bins_time': consts.ast.types.STRING,
            },
            {
                'code': consts.ast.types.STRING,
                'version': consts.ast.types.STRING,
                'ld': consts.ast.types.STRING,
                'probid': consts.ast.types.STRING,
                'title': consts.ast.types.STRING,
                'histories': consts.ast.types.INTEGER,
                'number': None,
                'particle': consts.ast.types.STRING,
                'columns': consts.ast.types.STRING,
                'bins_x': consts.ast.types.STRING,
                'bins_y': consts.ast.types.STRING,
                'bins_z': consts.ast.types.STRING,
                'bins_energy': consts.ast.types.STRING,
                'bins_time': consts.ast.types.STRING,
            },
            {
                'code': consts.ast.types.STRING,
                'version': consts.ast.types.STRING,
                'ld': consts.ast.types.STRING,
                'probid': consts.ast.types.STRING,
                'title': consts.ast.types.STRING,
                'histories': consts.ast.types.INTEGER,
                'number': consts.ast.types.INTEGER,
                'particle': None,
                'columns': consts.ast.types.STRING,
                'bins_x': consts.ast.types.STRING,
                'bins_y': consts.ast.types.STRING,
                'bins_z': consts.ast.types.STRING,
                'bins_energy': consts.ast.types.STRING,
                'bins_time': consts.ast.types.STRING,
            },
            {
                'code': consts.ast.types.STRING,
                'version': consts.ast.types.STRING,
                'ld': consts.ast.types.STRING,
                'probid': consts.ast.types.STRING,
                'title': consts.ast.types.STRING,
                'histories': consts.ast.types.INTEGER,
                'number': consts.ast.types.INTEGER,
                'particle': consts.ast.types.STRING,
                'columns': None,
                'bins_x': consts.ast.types.STRING,
                'bins_y': consts.ast.types.STRING,
                'bins_z': consts.ast.types.STRING,
                'bins_energy': consts.ast.types.STRING,
                'bins_time': consts.ast.types.STRING,
            },
        ]

    class Test_Mcnp(classes.Test_Mcnp):
        element = pymcnp.meshtal.Header
        EXAMPLES_VALID = [
            consts.string.meshtal.HEADER,
        ]
        EXAMPLES_INVALID = [
            'hello',
        ]
