import pymcnp
from ... import _utils


class Test_Gq:
    class Test_FromMcnp(_utils._Test_FromMcnp):
        element = pymcnp.inp.surface.Gq
        EXAMPLES_VALID = []
        EXAMPLES_INVALID = []

    class Test_Build(_utils._Test_Build):
        element = pymcnp.inp.surface.GqBuilder
        EXAMPLES_VALID = [
            {
                'a': _utils.string.type.REAL,
                'b': _utils.string.type.REAL,
                'c': _utils.string.type.REAL,
                'd': _utils.string.type.REAL,
                'e': _utils.string.type.REAL,
                'f': _utils.string.type.REAL,
                'g': _utils.string.type.REAL,
                'h': _utils.string.type.REAL,
                'j': _utils.string.type.REAL,
                'k': _utils.string.type.REAL,
            },
            {'a': 3.1, 'b': 3.1, 'c': 3.1, 'd': 3.1, 'e': 3.1, 'f': 3.1, 'g': 3.1, 'h': 3.1, 'j': 3.1, 'k': 3.1},
            {
                'a': _utils.ast.type.REAL,
                'b': _utils.ast.type.REAL,
                'c': _utils.ast.type.REAL,
                'd': _utils.ast.type.REAL,
                'e': _utils.ast.type.REAL,
                'f': _utils.ast.type.REAL,
                'g': _utils.ast.type.REAL,
                'h': _utils.ast.type.REAL,
                'j': _utils.ast.type.REAL,
                'k': _utils.ast.type.REAL,
            },
        ]
        EXAMPLES_INVALID = [
            {
                'a': None,
                'b': _utils.string.type.REAL,
                'c': _utils.string.type.REAL,
                'd': _utils.string.type.REAL,
                'e': _utils.string.type.REAL,
                'f': _utils.string.type.REAL,
                'g': _utils.string.type.REAL,
                'h': _utils.string.type.REAL,
                'j': _utils.string.type.REAL,
                'k': _utils.string.type.REAL,
            },
            {
                'a': _utils.string.type.REAL,
                'b': None,
                'c': _utils.string.type.REAL,
                'd': _utils.string.type.REAL,
                'e': _utils.string.type.REAL,
                'f': _utils.string.type.REAL,
                'g': _utils.string.type.REAL,
                'h': _utils.string.type.REAL,
                'j': _utils.string.type.REAL,
                'k': _utils.string.type.REAL,
            },
            {
                'a': _utils.string.type.REAL,
                'b': _utils.string.type.REAL,
                'c': None,
                'd': _utils.string.type.REAL,
                'e': _utils.string.type.REAL,
                'f': _utils.string.type.REAL,
                'g': _utils.string.type.REAL,
                'h': _utils.string.type.REAL,
                'j': _utils.string.type.REAL,
                'k': _utils.string.type.REAL,
            },
            {
                'a': _utils.string.type.REAL,
                'b': _utils.string.type.REAL,
                'c': _utils.string.type.REAL,
                'd': None,
                'e': _utils.string.type.REAL,
                'f': _utils.string.type.REAL,
                'g': _utils.string.type.REAL,
                'h': _utils.string.type.REAL,
                'j': _utils.string.type.REAL,
                'k': _utils.string.type.REAL,
            },
            {
                'a': _utils.string.type.REAL,
                'b': _utils.string.type.REAL,
                'c': _utils.string.type.REAL,
                'd': _utils.string.type.REAL,
                'e': None,
                'f': _utils.string.type.REAL,
                'g': _utils.string.type.REAL,
                'h': _utils.string.type.REAL,
                'j': _utils.string.type.REAL,
                'k': _utils.string.type.REAL,
            },
            {
                'a': _utils.string.type.REAL,
                'b': _utils.string.type.REAL,
                'c': _utils.string.type.REAL,
                'd': _utils.string.type.REAL,
                'e': _utils.string.type.REAL,
                'f': None,
                'g': _utils.string.type.REAL,
                'h': _utils.string.type.REAL,
                'j': _utils.string.type.REAL,
                'k': _utils.string.type.REAL,
            },
            {
                'a': _utils.string.type.REAL,
                'b': _utils.string.type.REAL,
                'c': _utils.string.type.REAL,
                'd': _utils.string.type.REAL,
                'e': _utils.string.type.REAL,
                'f': _utils.string.type.REAL,
                'g': None,
                'h': _utils.string.type.REAL,
                'j': _utils.string.type.REAL,
                'k': _utils.string.type.REAL,
            },
            {
                'a': _utils.string.type.REAL,
                'b': _utils.string.type.REAL,
                'c': _utils.string.type.REAL,
                'd': _utils.string.type.REAL,
                'e': _utils.string.type.REAL,
                'f': _utils.string.type.REAL,
                'g': _utils.string.type.REAL,
                'h': None,
                'j': _utils.string.type.REAL,
                'k': _utils.string.type.REAL,
            },
            {
                'a': _utils.string.type.REAL,
                'b': _utils.string.type.REAL,
                'c': _utils.string.type.REAL,
                'd': _utils.string.type.REAL,
                'e': _utils.string.type.REAL,
                'f': _utils.string.type.REAL,
                'g': _utils.string.type.REAL,
                'h': _utils.string.type.REAL,
                'j': None,
                'k': _utils.string.type.REAL,
            },
            {
                'a': _utils.string.type.REAL,
                'b': _utils.string.type.REAL,
                'c': _utils.string.type.REAL,
                'd': _utils.string.type.REAL,
                'e': _utils.string.type.REAL,
                'f': _utils.string.type.REAL,
                'g': _utils.string.type.REAL,
                'h': _utils.string.type.REAL,
                'j': _utils.string.type.REAL,
                'k': None,
            },
        ]
