import pymcnp
from ... import _utils


class Test_Wed:
    class Test_FromMcnp(_utils._Test_FromMcnp):
        element = pymcnp.inp.surface.Wed
        EXAMPLES_VALID = []
        EXAMPLES_INVALID = []

    class Test_Build(_utils._Test_Build):
        element = pymcnp.inp.surface.WedBuilder
        EXAMPLES_VALID = [
            {
                'vx': _utils.string.type.REAL,
                'vy': _utils.string.type.REAL,
                'vz': _utils.string.type.REAL,
                'v1x': _utils.string.type.REAL,
                'v1y': _utils.string.type.REAL,
                'v1z': _utils.string.type.REAL,
                'v2x': _utils.string.type.REAL,
                'v2y': _utils.string.type.REAL,
                'v2z': _utils.string.type.REAL,
                'v3x': _utils.string.type.REAL,
                'v3y': _utils.string.type.REAL,
                'v3z': _utils.string.type.REAL,
            },
            {'vx': 3.1, 'vy': 3.1, 'vz': 3.1, 'v1x': 3.1, 'v1y': 3.1, 'v1z': 3.1, 'v2x': 3.1, 'v2y': 3.1, 'v2z': 3.1, 'v3x': 3.1, 'v3y': 3.1, 'v3z': 3.1},
            {
                'vx': _utils.ast.type.REAL,
                'vy': _utils.ast.type.REAL,
                'vz': _utils.ast.type.REAL,
                'v1x': _utils.ast.type.REAL,
                'v1y': _utils.ast.type.REAL,
                'v1z': _utils.ast.type.REAL,
                'v2x': _utils.ast.type.REAL,
                'v2y': _utils.ast.type.REAL,
                'v2z': _utils.ast.type.REAL,
                'v3x': _utils.ast.type.REAL,
                'v3y': _utils.ast.type.REAL,
                'v3z': _utils.ast.type.REAL,
            },
        ]
        EXAMPLES_INVALID = [
            {
                'vx': None,
                'vy': _utils.string.type.REAL,
                'vz': _utils.string.type.REAL,
                'v1x': _utils.string.type.REAL,
                'v1y': _utils.string.type.REAL,
                'v1z': _utils.string.type.REAL,
                'v2x': _utils.string.type.REAL,
                'v2y': _utils.string.type.REAL,
                'v2z': _utils.string.type.REAL,
                'v3x': _utils.string.type.REAL,
                'v3y': _utils.string.type.REAL,
                'v3z': _utils.string.type.REAL,
            },
            {
                'vx': _utils.string.type.REAL,
                'vy': None,
                'vz': _utils.string.type.REAL,
                'v1x': _utils.string.type.REAL,
                'v1y': _utils.string.type.REAL,
                'v1z': _utils.string.type.REAL,
                'v2x': _utils.string.type.REAL,
                'v2y': _utils.string.type.REAL,
                'v2z': _utils.string.type.REAL,
                'v3x': _utils.string.type.REAL,
                'v3y': _utils.string.type.REAL,
                'v3z': _utils.string.type.REAL,
            },
            {
                'vx': _utils.string.type.REAL,
                'vy': _utils.string.type.REAL,
                'vz': None,
                'v1x': _utils.string.type.REAL,
                'v1y': _utils.string.type.REAL,
                'v1z': _utils.string.type.REAL,
                'v2x': _utils.string.type.REAL,
                'v2y': _utils.string.type.REAL,
                'v2z': _utils.string.type.REAL,
                'v3x': _utils.string.type.REAL,
                'v3y': _utils.string.type.REAL,
                'v3z': _utils.string.type.REAL,
            },
            {
                'vx': _utils.string.type.REAL,
                'vy': _utils.string.type.REAL,
                'vz': _utils.string.type.REAL,
                'v1x': None,
                'v1y': _utils.string.type.REAL,
                'v1z': _utils.string.type.REAL,
                'v2x': _utils.string.type.REAL,
                'v2y': _utils.string.type.REAL,
                'v2z': _utils.string.type.REAL,
                'v3x': _utils.string.type.REAL,
                'v3y': _utils.string.type.REAL,
                'v3z': _utils.string.type.REAL,
            },
            {
                'vx': _utils.string.type.REAL,
                'vy': _utils.string.type.REAL,
                'vz': _utils.string.type.REAL,
                'v1x': _utils.string.type.REAL,
                'v1y': None,
                'v1z': _utils.string.type.REAL,
                'v2x': _utils.string.type.REAL,
                'v2y': _utils.string.type.REAL,
                'v2z': _utils.string.type.REAL,
                'v3x': _utils.string.type.REAL,
                'v3y': _utils.string.type.REAL,
                'v3z': _utils.string.type.REAL,
            },
            {
                'vx': _utils.string.type.REAL,
                'vy': _utils.string.type.REAL,
                'vz': _utils.string.type.REAL,
                'v1x': _utils.string.type.REAL,
                'v1y': _utils.string.type.REAL,
                'v1z': None,
                'v2x': _utils.string.type.REAL,
                'v2y': _utils.string.type.REAL,
                'v2z': _utils.string.type.REAL,
                'v3x': _utils.string.type.REAL,
                'v3y': _utils.string.type.REAL,
                'v3z': _utils.string.type.REAL,
            },
            {
                'vx': _utils.string.type.REAL,
                'vy': _utils.string.type.REAL,
                'vz': _utils.string.type.REAL,
                'v1x': _utils.string.type.REAL,
                'v1y': _utils.string.type.REAL,
                'v1z': _utils.string.type.REAL,
                'v2x': None,
                'v2y': _utils.string.type.REAL,
                'v2z': _utils.string.type.REAL,
                'v3x': _utils.string.type.REAL,
                'v3y': _utils.string.type.REAL,
                'v3z': _utils.string.type.REAL,
            },
            {
                'vx': _utils.string.type.REAL,
                'vy': _utils.string.type.REAL,
                'vz': _utils.string.type.REAL,
                'v1x': _utils.string.type.REAL,
                'v1y': _utils.string.type.REAL,
                'v1z': _utils.string.type.REAL,
                'v2x': _utils.string.type.REAL,
                'v2y': None,
                'v2z': _utils.string.type.REAL,
                'v3x': _utils.string.type.REAL,
                'v3y': _utils.string.type.REAL,
                'v3z': _utils.string.type.REAL,
            },
            {
                'vx': _utils.string.type.REAL,
                'vy': _utils.string.type.REAL,
                'vz': _utils.string.type.REAL,
                'v1x': _utils.string.type.REAL,
                'v1y': _utils.string.type.REAL,
                'v1z': _utils.string.type.REAL,
                'v2x': _utils.string.type.REAL,
                'v2y': _utils.string.type.REAL,
                'v2z': None,
                'v3x': _utils.string.type.REAL,
                'v3y': _utils.string.type.REAL,
                'v3z': _utils.string.type.REAL,
            },
            {
                'vx': _utils.string.type.REAL,
                'vy': _utils.string.type.REAL,
                'vz': _utils.string.type.REAL,
                'v1x': _utils.string.type.REAL,
                'v1y': _utils.string.type.REAL,
                'v1z': _utils.string.type.REAL,
                'v2x': _utils.string.type.REAL,
                'v2y': _utils.string.type.REAL,
                'v2z': _utils.string.type.REAL,
                'v3x': None,
                'v3y': _utils.string.type.REAL,
                'v3z': _utils.string.type.REAL,
            },
            {
                'vx': _utils.string.type.REAL,
                'vy': _utils.string.type.REAL,
                'vz': _utils.string.type.REAL,
                'v1x': _utils.string.type.REAL,
                'v1y': _utils.string.type.REAL,
                'v1z': _utils.string.type.REAL,
                'v2x': _utils.string.type.REAL,
                'v2y': _utils.string.type.REAL,
                'v2z': _utils.string.type.REAL,
                'v3x': _utils.string.type.REAL,
                'v3y': None,
                'v3z': _utils.string.type.REAL,
            },
            {
                'vx': _utils.string.type.REAL,
                'vy': _utils.string.type.REAL,
                'vz': _utils.string.type.REAL,
                'v1x': _utils.string.type.REAL,
                'v1y': _utils.string.type.REAL,
                'v1z': _utils.string.type.REAL,
                'v2x': _utils.string.type.REAL,
                'v2y': _utils.string.type.REAL,
                'v2z': _utils.string.type.REAL,
                'v3x': _utils.string.type.REAL,
                'v3y': _utils.string.type.REAL,
                'v3z': None,
            },
        ]

    class Test_Draw(_utils._Test_Draw):
        element = pymcnp.inp.surface.Wed
        EXAMPLES = [
            'wed 1 2 3 4 5 6 7 8 9 1 2 3',
        ]
