import pymcnp
from ... import _utils


class Test_Box:
    class Test_FromMcnp(_utils._Test_FromMcnp):
        element = pymcnp.inp.surface.Box
        EXAMPLES_VALID = []
        EXAMPLES_INVALID = []

    class Test_Build(_utils._Test_Build):
        element = pymcnp.inp.surface.BoxBuilder
        EXAMPLES_VALID = [
            {
                'vx': _utils.string.type.REAL,
                'vy': _utils.string.type.REAL,
                'vz': _utils.string.type.REAL,
                'a1x': _utils.string.type.REAL,
                'a1y': _utils.string.type.REAL,
                'a1z': _utils.string.type.REAL,
                'a2x': _utils.string.type.REAL,
                'a2y': _utils.string.type.REAL,
                'a2z': _utils.string.type.REAL,
                'a3x': _utils.string.type.REAL,
                'a3y': _utils.string.type.REAL,
                'a3z': _utils.string.type.REAL,
            },
            {'vx': 3.1, 'vy': 3.1, 'vz': 3.1, 'a1x': 3.1, 'a1y': 3.1, 'a1z': 3.1, 'a2x': 3.1, 'a2y': 3.1, 'a2z': 3.1, 'a3x': 3.1, 'a3y': 3.1, 'a3z': 3.1},
            {
                'vx': _utils.ast.type.REAL,
                'vy': _utils.ast.type.REAL,
                'vz': _utils.ast.type.REAL,
                'a1x': _utils.ast.type.REAL,
                'a1y': _utils.ast.type.REAL,
                'a1z': _utils.ast.type.REAL,
                'a2x': _utils.ast.type.REAL,
                'a2y': _utils.ast.type.REAL,
                'a2z': _utils.ast.type.REAL,
                'a3x': _utils.ast.type.REAL,
                'a3y': _utils.ast.type.REAL,
                'a3z': _utils.ast.type.REAL,
            },
        ]
        EXAMPLES_INVALID = [
            {
                'vx': None,
                'vy': _utils.string.type.REAL,
                'vz': _utils.string.type.REAL,
                'a1x': _utils.string.type.REAL,
                'a1y': _utils.string.type.REAL,
                'a1z': _utils.string.type.REAL,
                'a2x': _utils.string.type.REAL,
                'a2y': _utils.string.type.REAL,
                'a2z': _utils.string.type.REAL,
                'a3x': _utils.string.type.REAL,
                'a3y': _utils.string.type.REAL,
                'a3z': _utils.string.type.REAL,
            },
            {
                'vx': _utils.string.type.REAL,
                'vy': None,
                'vz': _utils.string.type.REAL,
                'a1x': _utils.string.type.REAL,
                'a1y': _utils.string.type.REAL,
                'a1z': _utils.string.type.REAL,
                'a2x': _utils.string.type.REAL,
                'a2y': _utils.string.type.REAL,
                'a2z': _utils.string.type.REAL,
                'a3x': _utils.string.type.REAL,
                'a3y': _utils.string.type.REAL,
                'a3z': _utils.string.type.REAL,
            },
            {
                'vx': _utils.string.type.REAL,
                'vy': _utils.string.type.REAL,
                'vz': None,
                'a1x': _utils.string.type.REAL,
                'a1y': _utils.string.type.REAL,
                'a1z': _utils.string.type.REAL,
                'a2x': _utils.string.type.REAL,
                'a2y': _utils.string.type.REAL,
                'a2z': _utils.string.type.REAL,
                'a3x': _utils.string.type.REAL,
                'a3y': _utils.string.type.REAL,
                'a3z': _utils.string.type.REAL,
            },
            {
                'vx': _utils.string.type.REAL,
                'vy': _utils.string.type.REAL,
                'vz': _utils.string.type.REAL,
                'a1x': None,
                'a1y': _utils.string.type.REAL,
                'a1z': _utils.string.type.REAL,
                'a2x': _utils.string.type.REAL,
                'a2y': _utils.string.type.REAL,
                'a2z': _utils.string.type.REAL,
                'a3x': _utils.string.type.REAL,
                'a3y': _utils.string.type.REAL,
                'a3z': _utils.string.type.REAL,
            },
            {
                'vx': _utils.string.type.REAL,
                'vy': _utils.string.type.REAL,
                'vz': _utils.string.type.REAL,
                'a1x': _utils.string.type.REAL,
                'a1y': None,
                'a1z': _utils.string.type.REAL,
                'a2x': _utils.string.type.REAL,
                'a2y': _utils.string.type.REAL,
                'a2z': _utils.string.type.REAL,
                'a3x': _utils.string.type.REAL,
                'a3y': _utils.string.type.REAL,
                'a3z': _utils.string.type.REAL,
            },
            {
                'vx': _utils.string.type.REAL,
                'vy': _utils.string.type.REAL,
                'vz': _utils.string.type.REAL,
                'a1x': _utils.string.type.REAL,
                'a1y': _utils.string.type.REAL,
                'a1z': None,
                'a2x': _utils.string.type.REAL,
                'a2y': _utils.string.type.REAL,
                'a2z': _utils.string.type.REAL,
                'a3x': _utils.string.type.REAL,
                'a3y': _utils.string.type.REAL,
                'a3z': _utils.string.type.REAL,
            },
            {
                'vx': _utils.string.type.REAL,
                'vy': _utils.string.type.REAL,
                'vz': _utils.string.type.REAL,
                'a1x': _utils.string.type.REAL,
                'a1y': _utils.string.type.REAL,
                'a1z': _utils.string.type.REAL,
                'a2x': None,
                'a2y': _utils.string.type.REAL,
                'a2z': _utils.string.type.REAL,
                'a3x': _utils.string.type.REAL,
                'a3y': _utils.string.type.REAL,
                'a3z': _utils.string.type.REAL,
            },
            {
                'vx': _utils.string.type.REAL,
                'vy': _utils.string.type.REAL,
                'vz': _utils.string.type.REAL,
                'a1x': _utils.string.type.REAL,
                'a1y': _utils.string.type.REAL,
                'a1z': _utils.string.type.REAL,
                'a2x': _utils.string.type.REAL,
                'a2y': None,
                'a2z': _utils.string.type.REAL,
                'a3x': _utils.string.type.REAL,
                'a3y': _utils.string.type.REAL,
                'a3z': _utils.string.type.REAL,
            },
            {
                'vx': _utils.string.type.REAL,
                'vy': _utils.string.type.REAL,
                'vz': _utils.string.type.REAL,
                'a1x': _utils.string.type.REAL,
                'a1y': _utils.string.type.REAL,
                'a1z': _utils.string.type.REAL,
                'a2x': _utils.string.type.REAL,
                'a2y': _utils.string.type.REAL,
                'a2z': None,
                'a3x': _utils.string.type.REAL,
                'a3y': _utils.string.type.REAL,
                'a3z': _utils.string.type.REAL,
            },
            {
                'vx': _utils.string.type.REAL,
                'vy': _utils.string.type.REAL,
                'vz': _utils.string.type.REAL,
                'a1x': _utils.string.type.REAL,
                'a1y': _utils.string.type.REAL,
                'a1z': _utils.string.type.REAL,
                'a2x': _utils.string.type.REAL,
                'a2y': _utils.string.type.REAL,
                'a2z': _utils.string.type.REAL,
                'a3x': None,
                'a3y': _utils.string.type.REAL,
                'a3z': _utils.string.type.REAL,
            },
            {
                'vx': _utils.string.type.REAL,
                'vy': _utils.string.type.REAL,
                'vz': _utils.string.type.REAL,
                'a1x': _utils.string.type.REAL,
                'a1y': _utils.string.type.REAL,
                'a1z': _utils.string.type.REAL,
                'a2x': _utils.string.type.REAL,
                'a2y': _utils.string.type.REAL,
                'a2z': _utils.string.type.REAL,
                'a3x': _utils.string.type.REAL,
                'a3y': None,
                'a3z': _utils.string.type.REAL,
            },
            {
                'vx': _utils.string.type.REAL,
                'vy': _utils.string.type.REAL,
                'vz': _utils.string.type.REAL,
                'a1x': _utils.string.type.REAL,
                'a1y': _utils.string.type.REAL,
                'a1z': _utils.string.type.REAL,
                'a2x': _utils.string.type.REAL,
                'a2y': _utils.string.type.REAL,
                'a2z': _utils.string.type.REAL,
                'a3x': _utils.string.type.REAL,
                'a3y': _utils.string.type.REAL,
                'a3z': None,
            },
        ]

    class Test_Draw(_utils._Test_Draw):
        element = pymcnp.inp.surface.Box
        EXAMPLES = [
            'box 0 0 0 1 0 0 0 1 0 0 0 1',
        ]
