[build-system]
requires = ["setuptools>=61.0", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "pymcnp"
authors = [
   { name = "Mauricio Ayllon Unzueta", email = "mauri.ayllon12@gmail.com" },
   { name = "Arun Persaud", email = "apersaud@lbl.gov" },
   { name = "Devin Pease", email = "dmpease@lbl.gov" },
]
description = "Python-based MCNP tools."
version = "0.0.0"
requires-python = ">=3.10"

[project.urls]
"Homepage" = "https://github.com/mauricioAyllon/MCNP-tools"

[project.scripts]
pymcnp = "pymcnp.main:main"

[tool.setuptools.packages.find]
where = ["./src"]

[tool.setuptools_scm]
write_to = "./src/pymcnp/version.py"
