[build-system]
requires = ["setuptools>=61.0", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "mcnptools"
authors = [
   { name = "Mauricio Ayllon Unzueta", email = "mauri.ayllon12@gmail.com" },
   { name = "Arun Persaud", email = "apersaud@lbl.gov" },
]
description = "MCNP tools"
readme = "README.md"
requires-python = ">=3.8"
classifiers=[
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Operating System :: OS Independent",
]
dependencies = [
    "pandas",
    "numpy",
    "matplotlib",
    "molmass >= 2021.6.18",
    "scipy",
    "fortranformat >= 1.0.1",
    "h5py",
]
dynamic = ["version"]

[project.optional-dependencies]
test = ['pytest','pytest-cov']

[project.urls]
"Homepage" = "https://github.com/mauricioAyllon/MCNP-tools"

[project.scripts]
MCNPtools-parse-ptrac = "mcnptools.cli.MCNPtools_parse_ptrac:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"mcnptools.data" = ["*.txt"]

[tool.setuptools_scm]
write_to = "src/mcnptools/version.py"
