[build-system]
module = "mcnptools"
author = "Mauricio Ayllon Unzueta"
author-email = "mauri.ayllon12@gmail.com"
home-page = "https://github.com/mauricioAyllon/MCNP-tools"
requires = [
    "pandas",
    "numpy",
    "matplotlib",
    "scipy",
    "fortranformat",
    "h5py",
    "setuptools>=42",
    "wheel",
    "setuptools_scm[toml]>=3.4"
]
description-file="README.md"
classifiers=[
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.setuptools_scm]
write_to = "mcnptools/version.py"