import pymcnp

files = [
	# <<<<<<<<<< head # '/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/API-lab-B58/room58a_API.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/Detection Efficiency/ROOTSGDE.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/Detection Efficiency/ROOTSGDEF5.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/Neutron-scattering-soil/input-files/wet_soil_n_scatt_fmesh.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/Neutron-scattering-soil/input-files/dry_soil_n_scatt_ptrac.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/Neutron-scattering-soil/input-files/dry_soil_n_scatt_fmesh.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/angular-resolution/C_block_API_ptrac_cone_2cm.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/angular-resolution/C_block_API_ptrac_cone_3cm.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/angular-resolution/C_block_API_ptrac_cone_vertical.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/angular-resolution/C_block_API_ptrac_cone_7cm.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/angular-resolution/C_block_API_ptrac_cone_6cm.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/angular-resolution/C_block_API_ptrac_cone_4cm.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/angular-resolution/C_block_API_ptrac_cone_5cm.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/angular-resolution/C_block_API_ptrac_cone_10cm.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/angular-resolution/C_block_API_ptrac_cone.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/angular-resolution/C_block_API_ptrac_cone_8cm.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/angular-resolution/C_block_API_ptrac_cone_9cm.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/Gamma-spectrum/soil_RPP_F5.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/Gamma-spectrum/wet_soil_RPP_F5.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/Gamma-spectrum/soil_RPP_F5_fu.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/time-voxel/soil_f4_ring_det_thin_tally-water.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/time-voxel/soil_f4_ring_det_thin_tally.i',
	# fdir # '/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/teststand-shielding/test-stand-58a-shielding.i',
	# ... log # '/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/teststand-shielding/polypb.i',
	# phys:n # '/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/teststand-shielding/pbpoly.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/teststand-shielding/macro-bodies/room58a_macro_localShield.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/teststand-shielding/macro-bodies/openField3.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/teststand-shielding/macro-bodies/room58a_macro_localShield_10cm.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/teststand-shielding/macro-bodies/room58a_macro.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/teststand-shielding/macro-bodies/photon_dose/input/room58a_macro_photon.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/teststand-shielding/macro-bodies/photon_dose/input/room58a_macro_localShield_photon_10cm.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/teststand-shielding/macro-bodies/photon_dose/input/room58a_macro_localShield_photon_5cm.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/teststand-shielding/macro-bodies/openField.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/teststand-shielding/macro-bodies/openField4.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/teststand-shielding/macro-bodies/room58a_macro_photon.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/teststand-shielding/macro-bodies/room58a_macro_localShield_5cm.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/teststand-shielding/macro-bodies/openField2.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/teststand-shielding/macro-bodies/room58a_macro_localShield_20cm.i',
	# phys:n # '/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/teststand-shielding/bare.i',
	# m5 poly # '/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/Gamma-detector-shielding/parameter-scan-python/baseHD.i',
	# {{}} # '/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/Gamma-detector-shielding/shielding_polyF5_lead3.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/Gamma-detector-shielding/shielding_polyF5_lead3_neutron_spectrum.i',
	# {{}} # '/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/detector-response/labr-detector.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/detector-response/F8-4.i',
	# {{}} # '/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/detector-response/nai-detector.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/Gamma-scattering-target/cu_target.i',
	# {{}} # '/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/API/C_block_API_ptrac_filter.i',
	# {{}} # '/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/API/C_block_API_ptrac_large_soil_zaxis.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/Neutron-scattering-target/cu_2mm.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/Neutron-scattering-target/cu_3mm.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/Neutron-scattering-target/cu_1mm.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/Neutron-scattering-target/cu_4mm.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/Neutron-scattering-target/cu_5mm.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/Neutron-scattering-target/cu_6mm.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/Neutron-scattering-target/cu_30mm.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/Neutron-scattering-target/cu_20mm.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/Neutron-scattering-target/cu_10mm.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/Neutron-scattering-target/ptrac/cu_10mmptrac.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/Neutron-scattering-target/ptrac/cu_3mmptrac.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/Neutron-scattering-target/ptrac/cu_2mmptrac.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/Neutron-scattering-target/ptrac/cu_4mmptrac.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/Neutron-scattering-target/ptrac/cu_5mmptrac.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/Neutron-scattering-target/ptrac/cu_0mmptrac.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/Neutron-scattering-target/ptrac/cu_1mmptrac.i',
	'/Users/devinpease/Documents/LBNL/SIMULATIONS/MCNP/Neutron-scattering-target/ptrac/cu_20mmptrac.i',
]

for file in files:
	try:
		pymcnp.Inp.from_mcnp_file(file)
	except pymcnp.utils.errors.InpError as err:
		print(file)
		raise err
