# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev112+g10f19be.d20230714'
__version_tuple__ = version_tuple = (0, 1, 'dev112', 'g10f19be.d20230714')
