import pymcnp
from ... import consts
from ... import classes


class Test_Rhp:
    class Test_Init(classes.Test_Init):
        element = pymcnp.inp.Rhp
        EXAMPLES_VALID = [
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'hx': consts.string.types.REAL,
                'hy': consts.string.types.REAL,
                'hz': consts.string.types.REAL,
                'r1': consts.string.types.REAL,
                'r2': consts.string.types.REAL,
                'r3': consts.string.types.REAL,
                's1': consts.string.types.REAL,
                's2': consts.string.types.REAL,
                's3': consts.string.types.REAL,
                't1': consts.string.types.REAL,
                't2': consts.string.types.REAL,
                't3': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': 1,
                'transform': 1,
                'vx': 3.1,
                'vy': 3.1,
                'vz': 3.1,
                'hx': 3.1,
                'hy': 3.1,
                'hz': 3.1,
                'r1': 3.1,
                'r2': 3.1,
                'r3': 3.1,
                's1': 3.1,
                's2': 3.1,
                's3': 3.1,
                't1': 3.1,
                't2': 3.1,
                't3': 3.1,
            },
            {
                'prefix': pymcnp.types.String('*'),
                'number': consts.ast.types.INTEGER,
                'transform': consts.ast.types.INTEGER,
                'vx': consts.ast.types.REAL,
                'vy': consts.ast.types.REAL,
                'vz': consts.ast.types.REAL,
                'hx': consts.ast.types.REAL,
                'hy': consts.ast.types.REAL,
                'hz': consts.ast.types.REAL,
                'r1': consts.ast.types.REAL,
                'r2': consts.ast.types.REAL,
                'r3': consts.ast.types.REAL,
                's1': consts.ast.types.REAL,
                's2': consts.ast.types.REAL,
                's3': consts.ast.types.REAL,
                't1': consts.ast.types.REAL,
                't2': consts.ast.types.REAL,
                't3': consts.ast.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'hx': consts.string.types.REAL,
                'hy': consts.string.types.REAL,
                'hz': consts.string.types.REAL,
                'r1': consts.string.types.REAL,
                'r2': consts.string.types.REAL,
                'r3': consts.string.types.REAL,
                's1': None,
                's2': consts.string.types.REAL,
                's3': consts.string.types.REAL,
                't1': consts.string.types.REAL,
                't2': consts.string.types.REAL,
                't3': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'hx': consts.string.types.REAL,
                'hy': consts.string.types.REAL,
                'hz': consts.string.types.REAL,
                'r1': consts.string.types.REAL,
                'r2': consts.string.types.REAL,
                'r3': consts.string.types.REAL,
                's1': consts.string.types.REAL,
                's2': None,
                's3': consts.string.types.REAL,
                't1': consts.string.types.REAL,
                't2': consts.string.types.REAL,
                't3': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'hx': consts.string.types.REAL,
                'hy': consts.string.types.REAL,
                'hz': consts.string.types.REAL,
                'r1': consts.string.types.REAL,
                'r2': consts.string.types.REAL,
                'r3': consts.string.types.REAL,
                's1': consts.string.types.REAL,
                's2': consts.string.types.REAL,
                's3': None,
                't1': consts.string.types.REAL,
                't2': consts.string.types.REAL,
                't3': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'hx': consts.string.types.REAL,
                'hy': consts.string.types.REAL,
                'hz': consts.string.types.REAL,
                'r1': consts.string.types.REAL,
                'r2': consts.string.types.REAL,
                'r3': consts.string.types.REAL,
                's1': consts.string.types.REAL,
                's2': consts.string.types.REAL,
                's3': consts.string.types.REAL,
                't1': None,
                't2': consts.string.types.REAL,
                't3': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'hx': consts.string.types.REAL,
                'hy': consts.string.types.REAL,
                'hz': consts.string.types.REAL,
                'r1': consts.string.types.REAL,
                'r2': consts.string.types.REAL,
                'r3': consts.string.types.REAL,
                's1': consts.string.types.REAL,
                's2': consts.string.types.REAL,
                's3': consts.string.types.REAL,
                't1': consts.string.types.REAL,
                't2': None,
                't3': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'hx': consts.string.types.REAL,
                'hy': consts.string.types.REAL,
                'hz': consts.string.types.REAL,
                'r1': consts.string.types.REAL,
                'r2': consts.string.types.REAL,
                'r3': consts.string.types.REAL,
                's1': consts.string.types.REAL,
                's2': consts.string.types.REAL,
                's3': consts.string.types.REAL,
                't1': consts.string.types.REAL,
                't2': consts.string.types.REAL,
                't3': None,
            },
            {
                'prefix': None,
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'hx': consts.string.types.REAL,
                'hy': consts.string.types.REAL,
                'hz': consts.string.types.REAL,
                'r1': consts.string.types.REAL,
                'r2': consts.string.types.REAL,
                'r3': consts.string.types.REAL,
                's1': consts.string.types.REAL,
                's2': consts.string.types.REAL,
                's3': consts.string.types.REAL,
                't1': consts.string.types.REAL,
                't2': consts.string.types.REAL,
                't3': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': None,
                'transform': consts.string.types.INTEGER,
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'hx': consts.string.types.REAL,
                'hy': consts.string.types.REAL,
                'hz': consts.string.types.REAL,
                'r1': consts.string.types.REAL,
                'r2': consts.string.types.REAL,
                'r3': consts.string.types.REAL,
                's1': consts.string.types.REAL,
                's2': consts.string.types.REAL,
                's3': consts.string.types.REAL,
                't1': consts.string.types.REAL,
                't2': consts.string.types.REAL,
                't3': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': None,
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'hx': consts.string.types.REAL,
                'hy': consts.string.types.REAL,
                'hz': consts.string.types.REAL,
                'r1': consts.string.types.REAL,
                'r2': consts.string.types.REAL,
                'r3': consts.string.types.REAL,
                's1': consts.string.types.REAL,
                's2': consts.string.types.REAL,
                's3': consts.string.types.REAL,
                't1': consts.string.types.REAL,
                't2': consts.string.types.REAL,
                't3': consts.string.types.REAL,
            },
        ]
        EXAMPLES_INVALID = [
            {
                'prefix': 'a',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'hx': consts.string.types.REAL,
                'hy': consts.string.types.REAL,
                'hz': consts.string.types.REAL,
                'r1': consts.string.types.REAL,
                'r2': consts.string.types.REAL,
                'r3': consts.string.types.REAL,
                's1': consts.string.types.REAL,
                's2': consts.string.types.REAL,
                's3': consts.string.types.REAL,
                't1': consts.string.types.REAL,
                't2': consts.string.types.REAL,
                't3': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': '0',
                'transform': consts.string.types.INTEGER,
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'hx': consts.string.types.REAL,
                'hy': consts.string.types.REAL,
                'hz': consts.string.types.REAL,
                'r1': consts.string.types.REAL,
                'r2': consts.string.types.REAL,
                'r3': consts.string.types.REAL,
                's1': consts.string.types.REAL,
                's2': consts.string.types.REAL,
                's3': consts.string.types.REAL,
                't1': consts.string.types.REAL,
                't2': consts.string.types.REAL,
                't3': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': '1000',
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'hx': consts.string.types.REAL,
                'hy': consts.string.types.REAL,
                'hz': consts.string.types.REAL,
                'r1': consts.string.types.REAL,
                'r2': consts.string.types.REAL,
                'r3': consts.string.types.REAL,
                's1': consts.string.types.REAL,
                's2': consts.string.types.REAL,
                's3': consts.string.types.REAL,
                't1': consts.string.types.REAL,
                't2': consts.string.types.REAL,
                't3': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'vx': None,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'hx': consts.string.types.REAL,
                'hy': consts.string.types.REAL,
                'hz': consts.string.types.REAL,
                'r1': consts.string.types.REAL,
                'r2': consts.string.types.REAL,
                'r3': consts.string.types.REAL,
                's1': consts.string.types.REAL,
                's2': consts.string.types.REAL,
                's3': consts.string.types.REAL,
                't1': consts.string.types.REAL,
                't2': consts.string.types.REAL,
                't3': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'vx': consts.string.types.REAL,
                'vy': None,
                'vz': consts.string.types.REAL,
                'hx': consts.string.types.REAL,
                'hy': consts.string.types.REAL,
                'hz': consts.string.types.REAL,
                'r1': consts.string.types.REAL,
                'r2': consts.string.types.REAL,
                'r3': consts.string.types.REAL,
                's1': consts.string.types.REAL,
                's2': consts.string.types.REAL,
                's3': consts.string.types.REAL,
                't1': consts.string.types.REAL,
                't2': consts.string.types.REAL,
                't3': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': None,
                'hx': consts.string.types.REAL,
                'hy': consts.string.types.REAL,
                'hz': consts.string.types.REAL,
                'r1': consts.string.types.REAL,
                'r2': consts.string.types.REAL,
                'r3': consts.string.types.REAL,
                's1': consts.string.types.REAL,
                's2': consts.string.types.REAL,
                's3': consts.string.types.REAL,
                't1': consts.string.types.REAL,
                't2': consts.string.types.REAL,
                't3': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'hx': None,
                'hy': consts.string.types.REAL,
                'hz': consts.string.types.REAL,
                'r1': consts.string.types.REAL,
                'r2': consts.string.types.REAL,
                'r3': consts.string.types.REAL,
                's1': consts.string.types.REAL,
                's2': consts.string.types.REAL,
                's3': consts.string.types.REAL,
                't1': consts.string.types.REAL,
                't2': consts.string.types.REAL,
                't3': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'hx': consts.string.types.REAL,
                'hy': None,
                'hz': consts.string.types.REAL,
                'r1': consts.string.types.REAL,
                'r2': consts.string.types.REAL,
                'r3': consts.string.types.REAL,
                's1': consts.string.types.REAL,
                's2': consts.string.types.REAL,
                's3': consts.string.types.REAL,
                't1': consts.string.types.REAL,
                't2': consts.string.types.REAL,
                't3': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'hx': consts.string.types.REAL,
                'hy': consts.string.types.REAL,
                'hz': None,
                'r1': consts.string.types.REAL,
                'r2': consts.string.types.REAL,
                'r3': consts.string.types.REAL,
                's1': consts.string.types.REAL,
                's2': consts.string.types.REAL,
                's3': consts.string.types.REAL,
                't1': consts.string.types.REAL,
                't2': consts.string.types.REAL,
                't3': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'hx': consts.string.types.REAL,
                'hy': consts.string.types.REAL,
                'hz': consts.string.types.REAL,
                'r1': None,
                'r2': consts.string.types.REAL,
                'r3': consts.string.types.REAL,
                's1': consts.string.types.REAL,
                's2': consts.string.types.REAL,
                's3': consts.string.types.REAL,
                't1': consts.string.types.REAL,
                't2': consts.string.types.REAL,
                't3': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'hx': consts.string.types.REAL,
                'hy': consts.string.types.REAL,
                'hz': consts.string.types.REAL,
                'r1': consts.string.types.REAL,
                'r2': None,
                'r3': consts.string.types.REAL,
                's1': consts.string.types.REAL,
                's2': consts.string.types.REAL,
                's3': consts.string.types.REAL,
                't1': consts.string.types.REAL,
                't2': consts.string.types.REAL,
                't3': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'hx': consts.string.types.REAL,
                'hy': consts.string.types.REAL,
                'hz': consts.string.types.REAL,
                'r1': consts.string.types.REAL,
                'r2': consts.string.types.REAL,
                'r3': None,
                's1': consts.string.types.REAL,
                's2': consts.string.types.REAL,
                's3': consts.string.types.REAL,
                't1': consts.string.types.REAL,
                't2': consts.string.types.REAL,
                't3': consts.string.types.REAL,
            },
        ]

    class Test_Mcnp(classes.Test_Mcnp):
        element = pymcnp.inp.Rhp
        EXAMPLES_VALID = [consts.string.inp.RHP]
        EXAMPLES_INVALID = ['hello']

    class Test_Show(classes.Test_Show):
        element = pymcnp.inp.Rhp
        EXAMPLES = [consts.string.inp.RHP]

    class Test_Operations(classes.Test_Operations):
        EXAMPLES = [(consts.ast.inp.RHP, consts.ast.inp.RHP)]
