import pymcnp
from ... import consts
from ... import classes


class Test_Kcode:
    class Test_Init(classes.Test_Init):
        element = pymcnp.inp.Kcode
        EXAMPLES_VALID = [
            {
                'nsrck': consts.string.types.INTEGER,
                'rkk': consts.string.types.REAL,
                'ikz': consts.string.types.INTEGER,
                'kct': consts.string.types.INTEGER,
                'msrk': consts.string.types.INTEGER,
                'knrm': consts.string.types.INTEGER,
                'mrkp': consts.string.types.INTEGER,
                'kc8': consts.string.types.INTEGER,
            },
            {'nsrck': 1, 'rkk': 3.1, 'ikz': 1, 'kct': 1, 'msrk': 1, 'knrm': 1, 'mrkp': 1, 'kc8': 1},
            {
                'nsrck': consts.ast.types.INTEGER,
                'rkk': consts.ast.types.REAL,
                'ikz': consts.ast.types.INTEGER,
                'kct': consts.ast.types.INTEGER,
                'msrk': consts.ast.types.INTEGER,
                'knrm': consts.ast.types.INTEGER,
                'mrkp': consts.ast.types.INTEGER,
                'kc8': consts.ast.types.INTEGER,
            },
            {
                'nsrck': None,
                'rkk': consts.string.types.REAL,
                'ikz': consts.string.types.INTEGER,
                'kct': consts.string.types.INTEGER,
                'msrk': consts.string.types.INTEGER,
                'knrm': consts.string.types.INTEGER,
                'mrkp': consts.string.types.INTEGER,
                'kc8': consts.string.types.INTEGER,
            },
            {
                'nsrck': consts.string.types.INTEGER,
                'rkk': None,
                'ikz': consts.string.types.INTEGER,
                'kct': consts.string.types.INTEGER,
                'msrk': consts.string.types.INTEGER,
                'knrm': consts.string.types.INTEGER,
                'mrkp': consts.string.types.INTEGER,
                'kc8': consts.string.types.INTEGER,
            },
            {
                'nsrck': consts.string.types.INTEGER,
                'rkk': consts.string.types.REAL,
                'ikz': None,
                'kct': consts.string.types.INTEGER,
                'msrk': consts.string.types.INTEGER,
                'knrm': consts.string.types.INTEGER,
                'mrkp': consts.string.types.INTEGER,
                'kc8': consts.string.types.INTEGER,
            },
            {
                'nsrck': consts.string.types.INTEGER,
                'rkk': consts.string.types.REAL,
                'ikz': consts.string.types.INTEGER,
                'kct': None,
                'msrk': consts.string.types.INTEGER,
                'knrm': consts.string.types.INTEGER,
                'mrkp': consts.string.types.INTEGER,
                'kc8': consts.string.types.INTEGER,
            },
            {
                'nsrck': consts.string.types.INTEGER,
                'rkk': consts.string.types.REAL,
                'ikz': consts.string.types.INTEGER,
                'kct': consts.string.types.INTEGER,
                'msrk': None,
                'knrm': consts.string.types.INTEGER,
                'mrkp': consts.string.types.INTEGER,
                'kc8': consts.string.types.INTEGER,
            },
            {
                'nsrck': consts.string.types.INTEGER,
                'rkk': consts.string.types.REAL,
                'ikz': consts.string.types.INTEGER,
                'kct': consts.string.types.INTEGER,
                'msrk': consts.string.types.INTEGER,
                'knrm': None,
                'mrkp': consts.string.types.INTEGER,
                'kc8': consts.string.types.INTEGER,
            },
            {
                'nsrck': consts.string.types.INTEGER,
                'rkk': consts.string.types.REAL,
                'ikz': consts.string.types.INTEGER,
                'kct': consts.string.types.INTEGER,
                'msrk': consts.string.types.INTEGER,
                'knrm': consts.string.types.INTEGER,
                'mrkp': None,
                'kc8': consts.string.types.INTEGER,
            },
            {
                'nsrck': consts.string.types.INTEGER,
                'rkk': consts.string.types.REAL,
                'ikz': consts.string.types.INTEGER,
                'kct': consts.string.types.INTEGER,
                'msrk': consts.string.types.INTEGER,
                'knrm': consts.string.types.INTEGER,
                'mrkp': consts.string.types.INTEGER,
                'kc8': None,
            },
        ]
        EXAMPLES_INVALID = [
            {
                'nsrck': -9999,
                'rkk': consts.string.types.REAL,
                'ikz': consts.string.types.INTEGER,
                'kct': consts.string.types.INTEGER,
                'msrk': consts.string.types.INTEGER,
                'knrm': consts.string.types.INTEGER,
                'mrkp': consts.string.types.INTEGER,
                'kc8': consts.string.types.INTEGER,
            },
            {
                'nsrck': consts.string.types.INTEGER,
                'rkk': consts.string.types.REAL,
                'ikz': consts.string.types.INTEGER,
                'kct': -9999,
                'msrk': consts.string.types.INTEGER,
                'knrm': consts.string.types.INTEGER,
                'mrkp': consts.string.types.INTEGER,
                'kc8': consts.string.types.INTEGER,
            },
            {
                'nsrck': consts.string.types.INTEGER,
                'rkk': consts.string.types.REAL,
                'ikz': consts.string.types.INTEGER,
                'kct': consts.string.types.INTEGER,
                'msrk': 100000000,
                'knrm': consts.string.types.INTEGER,
                'mrkp': consts.string.types.INTEGER,
                'kc8': consts.string.types.INTEGER,
            },
            {
                'nsrck': consts.string.types.INTEGER,
                'rkk': consts.string.types.REAL,
                'ikz': consts.string.types.INTEGER,
                'kct': consts.string.types.INTEGER,
                'msrk': consts.string.types.INTEGER,
                'knrm': -9999,
                'mrkp': consts.string.types.INTEGER,
                'kc8': consts.string.types.INTEGER,
            },
            {
                'nsrck': consts.string.types.INTEGER,
                'rkk': consts.string.types.REAL,
                'ikz': consts.string.types.INTEGER,
                'kct': consts.string.types.INTEGER,
                'msrk': consts.string.types.INTEGER,
                'knrm': consts.string.types.INTEGER,
                'mrkp': -9999,
                'kc8': consts.string.types.INTEGER,
            },
            {
                'nsrck': consts.string.types.INTEGER,
                'rkk': consts.string.types.REAL,
                'ikz': consts.string.types.INTEGER,
                'kct': consts.string.types.INTEGER,
                'msrk': consts.string.types.INTEGER,
                'knrm': consts.string.types.INTEGER,
                'mrkp': consts.string.types.INTEGER,
                'kc8': -9999,
            },
        ]

    class Test_Mcnp(classes.Test_Mcnp):
        element = pymcnp.inp.Kcode
        EXAMPLES_VALID = [consts.string.inp.KCODE]
        EXAMPLES_INVALID = ['hello']
