import pymcnp
from ... import consts
from ... import classes


class Test_Phys_4:
    class Test_Init(classes.Test_Init):
        element = pymcnp.inp.Phys_4
        EXAMPLES_VALID = [
            {
                'designator': consts.string.types.DESIGNATOR,
                'emax': consts.string.types.REAL,
                'istrg': consts.string.types.INTEGER,
                'xmunum': consts.string.types.INTEGER,
                'xmugam': consts.string.types.REAL,
                'i_mcs_model': consts.string.types.INTEGER,
                'i_int_model': consts.string.types.INTEGER,
                'i_els_model': '-1',
                'efac': '0.8',
                'ckvnum': '0.8',
                'drp': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'emax': 3.1,
                'istrg': 1,
                'xmunum': 1,
                'xmugam': 3.1,
                'i_mcs_model': 1,
                'i_int_model': 1,
                'i_els_model': -1,
                'efac': 0.8,
                'ckvnum': 0.8,
                'drp': 3.1,
            },
            {
                'designator': consts.ast.types.DESIGNATOR,
                'emax': consts.ast.types.REAL,
                'istrg': consts.ast.types.INTEGER,
                'xmunum': consts.ast.types.INTEGER,
                'xmugam': consts.ast.types.REAL,
                'i_mcs_model': consts.ast.types.INTEGER,
                'i_int_model': consts.ast.types.INTEGER,
                'i_els_model': pymcnp.types.Integer(-1),
                'efac': pymcnp.types.Real(0.8),
                'ckvnum': pymcnp.types.Real(0.8),
                'drp': consts.ast.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'emax': None,
                'istrg': consts.string.types.INTEGER,
                'xmunum': consts.string.types.INTEGER,
                'xmugam': consts.string.types.REAL,
                'i_mcs_model': consts.string.types.INTEGER,
                'i_int_model': consts.string.types.INTEGER,
                'i_els_model': '-1',
                'efac': '0.8',
                'ckvnum': '0.8',
                'drp': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'emax': consts.string.types.REAL,
                'istrg': None,
                'xmunum': consts.string.types.INTEGER,
                'xmugam': consts.string.types.REAL,
                'i_mcs_model': consts.string.types.INTEGER,
                'i_int_model': consts.string.types.INTEGER,
                'i_els_model': '-1',
                'efac': '0.8',
                'ckvnum': '0.8',
                'drp': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'emax': consts.string.types.REAL,
                'istrg': consts.string.types.INTEGER,
                'xmunum': None,
                'xmugam': consts.string.types.REAL,
                'i_mcs_model': consts.string.types.INTEGER,
                'i_int_model': consts.string.types.INTEGER,
                'i_els_model': '-1',
                'efac': '0.8',
                'ckvnum': '0.8',
                'drp': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'emax': consts.string.types.REAL,
                'istrg': consts.string.types.INTEGER,
                'xmunum': consts.string.types.INTEGER,
                'xmugam': None,
                'i_mcs_model': consts.string.types.INTEGER,
                'i_int_model': consts.string.types.INTEGER,
                'i_els_model': '-1',
                'efac': '0.8',
                'ckvnum': '0.8',
                'drp': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'emax': consts.string.types.REAL,
                'istrg': consts.string.types.INTEGER,
                'xmunum': consts.string.types.INTEGER,
                'xmugam': consts.string.types.REAL,
                'i_mcs_model': None,
                'i_int_model': consts.string.types.INTEGER,
                'i_els_model': '-1',
                'efac': '0.8',
                'ckvnum': '0.8',
                'drp': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'emax': consts.string.types.REAL,
                'istrg': consts.string.types.INTEGER,
                'xmunum': consts.string.types.INTEGER,
                'xmugam': consts.string.types.REAL,
                'i_mcs_model': consts.string.types.INTEGER,
                'i_int_model': None,
                'i_els_model': '-1',
                'efac': '0.8',
                'ckvnum': '0.8',
                'drp': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'emax': consts.string.types.REAL,
                'istrg': consts.string.types.INTEGER,
                'xmunum': consts.string.types.INTEGER,
                'xmugam': consts.string.types.REAL,
                'i_mcs_model': consts.string.types.INTEGER,
                'i_int_model': consts.string.types.INTEGER,
                'i_els_model': None,
                'efac': '0.8',
                'ckvnum': '0.8',
                'drp': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'emax': consts.string.types.REAL,
                'istrg': consts.string.types.INTEGER,
                'xmunum': consts.string.types.INTEGER,
                'xmugam': consts.string.types.REAL,
                'i_mcs_model': consts.string.types.INTEGER,
                'i_int_model': consts.string.types.INTEGER,
                'i_els_model': '-1',
                'efac': None,
                'ckvnum': '0.8',
                'drp': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'emax': consts.string.types.REAL,
                'istrg': consts.string.types.INTEGER,
                'xmunum': consts.string.types.INTEGER,
                'xmugam': consts.string.types.REAL,
                'i_mcs_model': consts.string.types.INTEGER,
                'i_int_model': consts.string.types.INTEGER,
                'i_els_model': '-1',
                'efac': '0.8',
                'ckvnum': None,
                'drp': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'emax': consts.string.types.REAL,
                'istrg': consts.string.types.INTEGER,
                'xmunum': consts.string.types.INTEGER,
                'xmugam': consts.string.types.REAL,
                'i_mcs_model': consts.string.types.INTEGER,
                'i_int_model': consts.string.types.INTEGER,
                'i_els_model': '-1',
                'efac': '0.8',
                'ckvnum': '0.8',
                'drp': None,
            },
        ]
        EXAMPLES_INVALID = [
            {
                'designator': None,
                'emax': consts.string.types.REAL,
                'istrg': consts.string.types.INTEGER,
                'xmunum': consts.string.types.INTEGER,
                'xmugam': consts.string.types.REAL,
                'i_mcs_model': consts.string.types.INTEGER,
                'i_int_model': consts.string.types.INTEGER,
                'i_els_model': '-1',
                'efac': '0.8',
                'ckvnum': '0.8',
                'drp': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'emax': consts.string.types.REAL,
                'istrg': -9999,
                'xmunum': consts.string.types.INTEGER,
                'xmugam': consts.string.types.REAL,
                'i_mcs_model': consts.string.types.INTEGER,
                'i_int_model': consts.string.types.INTEGER,
                'i_els_model': '-1',
                'efac': '0.8',
                'ckvnum': '0.8',
                'drp': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'emax': consts.string.types.REAL,
                'istrg': consts.string.types.INTEGER,
                'xmunum': -9999,
                'xmugam': consts.string.types.REAL,
                'i_mcs_model': consts.string.types.INTEGER,
                'i_int_model': consts.string.types.INTEGER,
                'i_els_model': '-1',
                'efac': '0.8',
                'ckvnum': '0.8',
                'drp': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'emax': consts.string.types.REAL,
                'istrg': consts.string.types.INTEGER,
                'xmunum': consts.string.types.INTEGER,
                'xmugam': consts.string.types.REAL,
                'i_mcs_model': -9999,
                'i_int_model': consts.string.types.INTEGER,
                'i_els_model': '-1',
                'efac': '0.8',
                'ckvnum': '0.8',
                'drp': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'emax': consts.string.types.REAL,
                'istrg': consts.string.types.INTEGER,
                'xmunum': consts.string.types.INTEGER,
                'xmugam': consts.string.types.REAL,
                'i_mcs_model': consts.string.types.INTEGER,
                'i_int_model': -9999,
                'i_els_model': '-1',
                'efac': '0.8',
                'ckvnum': '0.8',
                'drp': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'emax': consts.string.types.REAL,
                'istrg': consts.string.types.INTEGER,
                'xmunum': consts.string.types.INTEGER,
                'xmugam': consts.string.types.REAL,
                'i_mcs_model': consts.string.types.INTEGER,
                'i_int_model': consts.string.types.INTEGER,
                'i_els_model': '1',
                'efac': '0.8',
                'ckvnum': '0.8',
                'drp': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'emax': consts.string.types.REAL,
                'istrg': consts.string.types.INTEGER,
                'xmunum': consts.string.types.INTEGER,
                'xmugam': consts.string.types.REAL,
                'i_mcs_model': consts.string.types.INTEGER,
                'i_int_model': consts.string.types.INTEGER,
                'i_els_model': '-1',
                'efac': '3.1',
                'ckvnum': '0.8',
                'drp': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'emax': consts.string.types.REAL,
                'istrg': consts.string.types.INTEGER,
                'xmunum': consts.string.types.INTEGER,
                'xmugam': consts.string.types.REAL,
                'i_mcs_model': consts.string.types.INTEGER,
                'i_int_model': consts.string.types.INTEGER,
                'i_els_model': '-1',
                'efac': '0.8',
                'ckvnum': '3.1',
                'drp': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'emax': consts.string.types.REAL,
                'istrg': consts.string.types.INTEGER,
                'xmunum': consts.string.types.INTEGER,
                'xmugam': consts.string.types.REAL,
                'i_mcs_model': consts.string.types.INTEGER,
                'i_int_model': consts.string.types.INTEGER,
                'i_els_model': '-1',
                'efac': '0.8',
                'ckvnum': '0.8',
                'drp': -3.1,
            },
        ]

    class Test_Mcnp(classes.Test_Mcnp):
        element = pymcnp.inp.Phys_4
        EXAMPLES_VALID = [consts.string.inp.PHYS_4]
        EXAMPLES_INVALID = ['hello']
