import pymcnp
from ... import consts
from ... import classes


class Test_Box:
    class Test_Init(classes.Test_Init):
        element = pymcnp.inp.Box
        EXAMPLES_VALID = [
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'a1x': consts.string.types.REAL,
                'a1y': consts.string.types.REAL,
                'a1z': consts.string.types.REAL,
                'a2x': consts.string.types.REAL,
                'a2y': consts.string.types.REAL,
                'a2z': consts.string.types.REAL,
                'a3x': consts.string.types.REAL,
                'a3y': consts.string.types.REAL,
                'a3z': consts.string.types.REAL,
            },
            {'prefix': '*', 'number': 1, 'transform': 1, 'vx': 3.1, 'vy': 3.1, 'vz': 3.1, 'a1x': 3.1, 'a1y': 3.1, 'a1z': 3.1, 'a2x': 3.1, 'a2y': 3.1, 'a2z': 3.1, 'a3x': 3.1, 'a3y': 3.1, 'a3z': 3.1},
            {
                'prefix': pymcnp.types.String('*'),
                'number': consts.ast.types.INTEGER,
                'transform': consts.ast.types.INTEGER,
                'vx': consts.ast.types.REAL,
                'vy': consts.ast.types.REAL,
                'vz': consts.ast.types.REAL,
                'a1x': consts.ast.types.REAL,
                'a1y': consts.ast.types.REAL,
                'a1z': consts.ast.types.REAL,
                'a2x': consts.ast.types.REAL,
                'a2y': consts.ast.types.REAL,
                'a2z': consts.ast.types.REAL,
                'a3x': consts.ast.types.REAL,
                'a3y': consts.ast.types.REAL,
                'a3z': consts.ast.types.REAL,
            },
            {
                'prefix': None,
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'a1x': consts.string.types.REAL,
                'a1y': consts.string.types.REAL,
                'a1z': consts.string.types.REAL,
                'a2x': consts.string.types.REAL,
                'a2y': consts.string.types.REAL,
                'a2z': consts.string.types.REAL,
                'a3x': consts.string.types.REAL,
                'a3y': consts.string.types.REAL,
                'a3z': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': None,
                'transform': consts.string.types.INTEGER,
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'a1x': consts.string.types.REAL,
                'a1y': consts.string.types.REAL,
                'a1z': consts.string.types.REAL,
                'a2x': consts.string.types.REAL,
                'a2y': consts.string.types.REAL,
                'a2z': consts.string.types.REAL,
                'a3x': consts.string.types.REAL,
                'a3y': consts.string.types.REAL,
                'a3z': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': None,
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'a1x': consts.string.types.REAL,
                'a1y': consts.string.types.REAL,
                'a1z': consts.string.types.REAL,
                'a2x': consts.string.types.REAL,
                'a2y': consts.string.types.REAL,
                'a2z': consts.string.types.REAL,
                'a3x': consts.string.types.REAL,
                'a3y': consts.string.types.REAL,
                'a3z': consts.string.types.REAL,
            },
        ]
        EXAMPLES_INVALID = [
            {
                'prefix': 'a',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'a1x': consts.string.types.REAL,
                'a1y': consts.string.types.REAL,
                'a1z': consts.string.types.REAL,
                'a2x': consts.string.types.REAL,
                'a2y': consts.string.types.REAL,
                'a2z': consts.string.types.REAL,
                'a3x': consts.string.types.REAL,
                'a3y': consts.string.types.REAL,
                'a3z': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': '0',
                'transform': consts.string.types.INTEGER,
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'a1x': consts.string.types.REAL,
                'a1y': consts.string.types.REAL,
                'a1z': consts.string.types.REAL,
                'a2x': consts.string.types.REAL,
                'a2y': consts.string.types.REAL,
                'a2z': consts.string.types.REAL,
                'a3x': consts.string.types.REAL,
                'a3y': consts.string.types.REAL,
                'a3z': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': '1000',
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'a1x': consts.string.types.REAL,
                'a1y': consts.string.types.REAL,
                'a1z': consts.string.types.REAL,
                'a2x': consts.string.types.REAL,
                'a2y': consts.string.types.REAL,
                'a2z': consts.string.types.REAL,
                'a3x': consts.string.types.REAL,
                'a3y': consts.string.types.REAL,
                'a3z': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'vx': None,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'a1x': consts.string.types.REAL,
                'a1y': consts.string.types.REAL,
                'a1z': consts.string.types.REAL,
                'a2x': consts.string.types.REAL,
                'a2y': consts.string.types.REAL,
                'a2z': consts.string.types.REAL,
                'a3x': consts.string.types.REAL,
                'a3y': consts.string.types.REAL,
                'a3z': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'vx': consts.string.types.REAL,
                'vy': None,
                'vz': consts.string.types.REAL,
                'a1x': consts.string.types.REAL,
                'a1y': consts.string.types.REAL,
                'a1z': consts.string.types.REAL,
                'a2x': consts.string.types.REAL,
                'a2y': consts.string.types.REAL,
                'a2z': consts.string.types.REAL,
                'a3x': consts.string.types.REAL,
                'a3y': consts.string.types.REAL,
                'a3z': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': None,
                'a1x': consts.string.types.REAL,
                'a1y': consts.string.types.REAL,
                'a1z': consts.string.types.REAL,
                'a2x': consts.string.types.REAL,
                'a2y': consts.string.types.REAL,
                'a2z': consts.string.types.REAL,
                'a3x': consts.string.types.REAL,
                'a3y': consts.string.types.REAL,
                'a3z': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'a1x': None,
                'a1y': consts.string.types.REAL,
                'a1z': consts.string.types.REAL,
                'a2x': consts.string.types.REAL,
                'a2y': consts.string.types.REAL,
                'a2z': consts.string.types.REAL,
                'a3x': consts.string.types.REAL,
                'a3y': consts.string.types.REAL,
                'a3z': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'a1x': consts.string.types.REAL,
                'a1y': None,
                'a1z': consts.string.types.REAL,
                'a2x': consts.string.types.REAL,
                'a2y': consts.string.types.REAL,
                'a2z': consts.string.types.REAL,
                'a3x': consts.string.types.REAL,
                'a3y': consts.string.types.REAL,
                'a3z': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'a1x': consts.string.types.REAL,
                'a1y': consts.string.types.REAL,
                'a1z': None,
                'a2x': consts.string.types.REAL,
                'a2y': consts.string.types.REAL,
                'a2z': consts.string.types.REAL,
                'a3x': consts.string.types.REAL,
                'a3y': consts.string.types.REAL,
                'a3z': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'a1x': consts.string.types.REAL,
                'a1y': consts.string.types.REAL,
                'a1z': consts.string.types.REAL,
                'a2x': None,
                'a2y': consts.string.types.REAL,
                'a2z': consts.string.types.REAL,
                'a3x': consts.string.types.REAL,
                'a3y': consts.string.types.REAL,
                'a3z': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'a1x': consts.string.types.REAL,
                'a1y': consts.string.types.REAL,
                'a1z': consts.string.types.REAL,
                'a2x': consts.string.types.REAL,
                'a2y': None,
                'a2z': consts.string.types.REAL,
                'a3x': consts.string.types.REAL,
                'a3y': consts.string.types.REAL,
                'a3z': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'a1x': consts.string.types.REAL,
                'a1y': consts.string.types.REAL,
                'a1z': consts.string.types.REAL,
                'a2x': consts.string.types.REAL,
                'a2y': consts.string.types.REAL,
                'a2z': None,
                'a3x': consts.string.types.REAL,
                'a3y': consts.string.types.REAL,
                'a3z': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'a1x': consts.string.types.REAL,
                'a1y': consts.string.types.REAL,
                'a1z': consts.string.types.REAL,
                'a2x': consts.string.types.REAL,
                'a2y': consts.string.types.REAL,
                'a2z': consts.string.types.REAL,
                'a3x': None,
                'a3y': consts.string.types.REAL,
                'a3z': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'a1x': consts.string.types.REAL,
                'a1y': consts.string.types.REAL,
                'a1z': consts.string.types.REAL,
                'a2x': consts.string.types.REAL,
                'a2y': consts.string.types.REAL,
                'a2z': consts.string.types.REAL,
                'a3x': consts.string.types.REAL,
                'a3y': None,
                'a3z': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'a1x': consts.string.types.REAL,
                'a1y': consts.string.types.REAL,
                'a1z': consts.string.types.REAL,
                'a2x': consts.string.types.REAL,
                'a2y': consts.string.types.REAL,
                'a2z': consts.string.types.REAL,
                'a3x': consts.string.types.REAL,
                'a3y': consts.string.types.REAL,
                'a3z': None,
            },
        ]

    class Test_Mcnp(classes.Test_Mcnp):
        element = pymcnp.inp.Box
        EXAMPLES_VALID = [
            # 4.1
            '8 box -2.5 -2.5 0 5 0 0 0 5 0 0 0 5',
            consts.string.inp.BOX,
        ]
        EXAMPLES_INVALID = ['hello']

    class Test_Show(classes.Test_Show):
        element = pymcnp.inp.Box
        EXAMPLES = [consts.string.inp.BOX]

    class Test_Operations(classes.Test_Operations):
        EXAMPLES = [(consts.ast.inp.BOX, consts.ast.inp.BOX)]
