import pymcnp
from ... import consts
from ... import classes


class Test_Fir:
    class Test_Init(classes.Test_Init):
        element = pymcnp.inp.Fir
        EXAMPLES_VALID = [
            {
                'suffix': '5',
                'designator': consts.string.types.DESIGNATOR,
                'x1': consts.string.types.REAL,
                'y1': consts.string.types.REAL,
                'z1': consts.string.types.REAL,
                'ro': '0',
                'x2': consts.string.types.REAL,
                'y2': consts.string.types.REAL,
                'z2': consts.string.types.REAL,
                'f1': '-1',
                'f2': consts.string.types.REAL,
                'f3': '-1',
            },
            {'suffix': 5, 'designator': consts.string.types.DESIGNATOR, 'x1': 3.1, 'y1': 3.1, 'z1': 3.1, 'ro': 0, 'x2': 3.1, 'y2': 3.1, 'z2': 3.1, 'f1': -1, 'f2': 3.1, 'f3': -1},
            {
                'suffix': pymcnp.types.Integer(5),
                'designator': consts.ast.types.DESIGNATOR,
                'x1': consts.ast.types.REAL,
                'y1': consts.ast.types.REAL,
                'z1': consts.ast.types.REAL,
                'ro': pymcnp.types.Real(0),
                'x2': consts.ast.types.REAL,
                'y2': consts.ast.types.REAL,
                'z2': consts.ast.types.REAL,
                'f1': pymcnp.types.Real(-1),
                'f2': consts.ast.types.REAL,
                'f3': pymcnp.types.Real(-1),
            },
            {
                'suffix': '5',
                'designator': None,
                'x1': consts.string.types.REAL,
                'y1': consts.string.types.REAL,
                'z1': consts.string.types.REAL,
                'ro': '0',
                'x2': consts.string.types.REAL,
                'y2': consts.string.types.REAL,
                'z2': consts.string.types.REAL,
                'f1': '-1',
                'f2': consts.string.types.REAL,
                'f3': '-1',
            },
        ]
        EXAMPLES_INVALID = [
            {
                'suffix': None,
                'designator': consts.string.types.DESIGNATOR,
                'x1': consts.string.types.REAL,
                'y1': consts.string.types.REAL,
                'z1': consts.string.types.REAL,
                'ro': '0',
                'x2': consts.string.types.REAL,
                'y2': consts.string.types.REAL,
                'z2': consts.string.types.REAL,
                'f1': '-1',
                'f2': consts.string.types.REAL,
                'f3': '-1',
            },
            {
                'suffix': '5',
                'designator': consts.string.types.DESIGNATOR,
                'x1': None,
                'y1': consts.string.types.REAL,
                'z1': consts.string.types.REAL,
                'ro': '0',
                'x2': consts.string.types.REAL,
                'y2': consts.string.types.REAL,
                'z2': consts.string.types.REAL,
                'f1': '-1',
                'f2': consts.string.types.REAL,
                'f3': '-1',
            },
            {
                'suffix': '5',
                'designator': consts.string.types.DESIGNATOR,
                'x1': consts.string.types.REAL,
                'y1': None,
                'z1': consts.string.types.REAL,
                'ro': '0',
                'x2': consts.string.types.REAL,
                'y2': consts.string.types.REAL,
                'z2': consts.string.types.REAL,
                'f1': '-1',
                'f2': consts.string.types.REAL,
                'f3': '-1',
            },
            {
                'suffix': '5',
                'designator': consts.string.types.DESIGNATOR,
                'x1': consts.string.types.REAL,
                'y1': consts.string.types.REAL,
                'z1': None,
                'ro': '0',
                'x2': consts.string.types.REAL,
                'y2': consts.string.types.REAL,
                'z2': consts.string.types.REAL,
                'f1': '-1',
                'f2': consts.string.types.REAL,
                'f3': '-1',
            },
            {
                'suffix': '5',
                'designator': consts.string.types.DESIGNATOR,
                'x1': consts.string.types.REAL,
                'y1': consts.string.types.REAL,
                'z1': consts.string.types.REAL,
                'ro': None,
                'x2': consts.string.types.REAL,
                'y2': consts.string.types.REAL,
                'z2': consts.string.types.REAL,
                'f1': '-1',
                'f2': consts.string.types.REAL,
                'f3': '-1',
            },
            {
                'suffix': '5',
                'designator': consts.string.types.DESIGNATOR,
                'x1': consts.string.types.REAL,
                'y1': consts.string.types.REAL,
                'z1': consts.string.types.REAL,
                'ro': '0',
                'x2': None,
                'y2': consts.string.types.REAL,
                'z2': consts.string.types.REAL,
                'f1': '-1',
                'f2': consts.string.types.REAL,
                'f3': '-1',
            },
            {
                'suffix': '5',
                'designator': consts.string.types.DESIGNATOR,
                'x1': consts.string.types.REAL,
                'y1': consts.string.types.REAL,
                'z1': consts.string.types.REAL,
                'ro': '0',
                'x2': consts.string.types.REAL,
                'y2': None,
                'z2': consts.string.types.REAL,
                'f1': '-1',
                'f2': consts.string.types.REAL,
                'f3': '-1',
            },
            {
                'suffix': '5',
                'designator': consts.string.types.DESIGNATOR,
                'x1': consts.string.types.REAL,
                'y1': consts.string.types.REAL,
                'z1': consts.string.types.REAL,
                'ro': '0',
                'x2': consts.string.types.REAL,
                'y2': consts.string.types.REAL,
                'z2': None,
                'f1': '-1',
                'f2': consts.string.types.REAL,
                'f3': '-1',
            },
            {
                'suffix': '5',
                'designator': consts.string.types.DESIGNATOR,
                'x1': consts.string.types.REAL,
                'y1': consts.string.types.REAL,
                'z1': consts.string.types.REAL,
                'ro': '0',
                'x2': consts.string.types.REAL,
                'y2': consts.string.types.REAL,
                'z2': consts.string.types.REAL,
                'f1': None,
                'f2': consts.string.types.REAL,
                'f3': '-1',
            },
            {
                'suffix': '5',
                'designator': consts.string.types.DESIGNATOR,
                'x1': consts.string.types.REAL,
                'y1': consts.string.types.REAL,
                'z1': consts.string.types.REAL,
                'ro': '0',
                'x2': consts.string.types.REAL,
                'y2': consts.string.types.REAL,
                'z2': consts.string.types.REAL,
                'f1': '-1',
                'f2': None,
                'f3': '-1',
            },
            {
                'suffix': '5',
                'designator': consts.string.types.DESIGNATOR,
                'x1': consts.string.types.REAL,
                'y1': consts.string.types.REAL,
                'z1': consts.string.types.REAL,
                'ro': '0',
                'x2': consts.string.types.REAL,
                'y2': consts.string.types.REAL,
                'z2': consts.string.types.REAL,
                'f1': '-1',
                'f2': consts.string.types.REAL,
                'f3': None,
            },
            {
                'suffix': '1',
                'designator': consts.string.types.DESIGNATOR,
                'x1': consts.string.types.REAL,
                'y1': consts.string.types.REAL,
                'z1': consts.string.types.REAL,
                'ro': '0',
                'x2': consts.string.types.REAL,
                'y2': consts.string.types.REAL,
                'z2': consts.string.types.REAL,
                'f1': '-1',
                'f2': consts.string.types.REAL,
                'f3': '-1',
            },
            {
                'suffix': '5',
                'designator': consts.string.types.DESIGNATOR,
                'x1': consts.string.types.REAL,
                'y1': consts.string.types.REAL,
                'z1': consts.string.types.REAL,
                'ro': '3.1',
                'x2': consts.string.types.REAL,
                'y2': consts.string.types.REAL,
                'z2': consts.string.types.REAL,
                'f1': '-1',
                'f2': consts.string.types.REAL,
                'f3': '-1',
            },
            {
                'suffix': '5',
                'designator': consts.string.types.DESIGNATOR,
                'x1': consts.string.types.REAL,
                'y1': consts.string.types.REAL,
                'z1': consts.string.types.REAL,
                'ro': '0',
                'x2': consts.string.types.REAL,
                'y2': consts.string.types.REAL,
                'z2': consts.string.types.REAL,
                'f1': '3.1',
                'f2': consts.string.types.REAL,
                'f3': '-1',
            },
            {
                'suffix': '5',
                'designator': consts.string.types.DESIGNATOR,
                'x1': consts.string.types.REAL,
                'y1': consts.string.types.REAL,
                'z1': consts.string.types.REAL,
                'ro': '0',
                'x2': consts.string.types.REAL,
                'y2': consts.string.types.REAL,
                'z2': consts.string.types.REAL,
                'f1': '-1',
                'f2': consts.string.types.REAL,
                'f3': '3.1',
            },
        ]

    class Test_Mcnp(classes.Test_Mcnp):
        element = pymcnp.inp.Fir
        EXAMPLES_VALID = [consts.string.inp.FIR]
        EXAMPLES_INVALID = ['hello']
