import pymcnp
from ... import consts
from ... import classes


class Test_Sq:
    class Test_Init(classes.Test_Init):
        element = pymcnp.inp.Sq
        EXAMPLES_VALID = [
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'a': consts.string.types.REAL,
                'b': consts.string.types.REAL,
                'c': consts.string.types.REAL,
                'd': consts.string.types.REAL,
                'e': consts.string.types.REAL,
                'f': consts.string.types.REAL,
                'g': consts.string.types.REAL,
                'x': consts.string.types.REAL,
                'y': consts.string.types.REAL,
                'z': consts.string.types.REAL,
            },
            {'prefix': '*', 'number': 1, 'transform': 1, 'a': 3.1, 'b': 3.1, 'c': 3.1, 'd': 3.1, 'e': 3.1, 'f': 3.1, 'g': 3.1, 'x': 3.1, 'y': 3.1, 'z': 3.1},
            {
                'prefix': pymcnp.types.String('*'),
                'number': consts.ast.types.INTEGER,
                'transform': consts.ast.types.INTEGER,
                'a': consts.ast.types.REAL,
                'b': consts.ast.types.REAL,
                'c': consts.ast.types.REAL,
                'd': consts.ast.types.REAL,
                'e': consts.ast.types.REAL,
                'f': consts.ast.types.REAL,
                'g': consts.ast.types.REAL,
                'x': consts.ast.types.REAL,
                'y': consts.ast.types.REAL,
                'z': consts.ast.types.REAL,
            },
            {
                'prefix': None,
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'a': consts.string.types.REAL,
                'b': consts.string.types.REAL,
                'c': consts.string.types.REAL,
                'd': consts.string.types.REAL,
                'e': consts.string.types.REAL,
                'f': consts.string.types.REAL,
                'g': consts.string.types.REAL,
                'x': consts.string.types.REAL,
                'y': consts.string.types.REAL,
                'z': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': None,
                'transform': consts.string.types.INTEGER,
                'a': consts.string.types.REAL,
                'b': consts.string.types.REAL,
                'c': consts.string.types.REAL,
                'd': consts.string.types.REAL,
                'e': consts.string.types.REAL,
                'f': consts.string.types.REAL,
                'g': consts.string.types.REAL,
                'x': consts.string.types.REAL,
                'y': consts.string.types.REAL,
                'z': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': None,
                'a': consts.string.types.REAL,
                'b': consts.string.types.REAL,
                'c': consts.string.types.REAL,
                'd': consts.string.types.REAL,
                'e': consts.string.types.REAL,
                'f': consts.string.types.REAL,
                'g': consts.string.types.REAL,
                'x': consts.string.types.REAL,
                'y': consts.string.types.REAL,
                'z': consts.string.types.REAL,
            },
        ]
        EXAMPLES_INVALID = [
            {
                'prefix': 'a',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'a': consts.string.types.REAL,
                'b': consts.string.types.REAL,
                'c': consts.string.types.REAL,
                'd': consts.string.types.REAL,
                'e': consts.string.types.REAL,
                'f': consts.string.types.REAL,
                'g': consts.string.types.REAL,
                'x': consts.string.types.REAL,
                'y': consts.string.types.REAL,
                'z': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': '0',
                'transform': consts.string.types.INTEGER,
                'a': consts.string.types.REAL,
                'b': consts.string.types.REAL,
                'c': consts.string.types.REAL,
                'd': consts.string.types.REAL,
                'e': consts.string.types.REAL,
                'f': consts.string.types.REAL,
                'g': consts.string.types.REAL,
                'x': consts.string.types.REAL,
                'y': consts.string.types.REAL,
                'z': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': '1000',
                'a': consts.string.types.REAL,
                'b': consts.string.types.REAL,
                'c': consts.string.types.REAL,
                'd': consts.string.types.REAL,
                'e': consts.string.types.REAL,
                'f': consts.string.types.REAL,
                'g': consts.string.types.REAL,
                'x': consts.string.types.REAL,
                'y': consts.string.types.REAL,
                'z': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'a': None,
                'b': consts.string.types.REAL,
                'c': consts.string.types.REAL,
                'd': consts.string.types.REAL,
                'e': consts.string.types.REAL,
                'f': consts.string.types.REAL,
                'g': consts.string.types.REAL,
                'x': consts.string.types.REAL,
                'y': consts.string.types.REAL,
                'z': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'a': consts.string.types.REAL,
                'b': None,
                'c': consts.string.types.REAL,
                'd': consts.string.types.REAL,
                'e': consts.string.types.REAL,
                'f': consts.string.types.REAL,
                'g': consts.string.types.REAL,
                'x': consts.string.types.REAL,
                'y': consts.string.types.REAL,
                'z': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'a': consts.string.types.REAL,
                'b': consts.string.types.REAL,
                'c': None,
                'd': consts.string.types.REAL,
                'e': consts.string.types.REAL,
                'f': consts.string.types.REAL,
                'g': consts.string.types.REAL,
                'x': consts.string.types.REAL,
                'y': consts.string.types.REAL,
                'z': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'a': consts.string.types.REAL,
                'b': consts.string.types.REAL,
                'c': consts.string.types.REAL,
                'd': None,
                'e': consts.string.types.REAL,
                'f': consts.string.types.REAL,
                'g': consts.string.types.REAL,
                'x': consts.string.types.REAL,
                'y': consts.string.types.REAL,
                'z': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'a': consts.string.types.REAL,
                'b': consts.string.types.REAL,
                'c': consts.string.types.REAL,
                'd': consts.string.types.REAL,
                'e': None,
                'f': consts.string.types.REAL,
                'g': consts.string.types.REAL,
                'x': consts.string.types.REAL,
                'y': consts.string.types.REAL,
                'z': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'a': consts.string.types.REAL,
                'b': consts.string.types.REAL,
                'c': consts.string.types.REAL,
                'd': consts.string.types.REAL,
                'e': consts.string.types.REAL,
                'f': None,
                'g': consts.string.types.REAL,
                'x': consts.string.types.REAL,
                'y': consts.string.types.REAL,
                'z': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'a': consts.string.types.REAL,
                'b': consts.string.types.REAL,
                'c': consts.string.types.REAL,
                'd': consts.string.types.REAL,
                'e': consts.string.types.REAL,
                'f': consts.string.types.REAL,
                'g': None,
                'x': consts.string.types.REAL,
                'y': consts.string.types.REAL,
                'z': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'a': consts.string.types.REAL,
                'b': consts.string.types.REAL,
                'c': consts.string.types.REAL,
                'd': consts.string.types.REAL,
                'e': consts.string.types.REAL,
                'f': consts.string.types.REAL,
                'g': consts.string.types.REAL,
                'x': None,
                'y': consts.string.types.REAL,
                'z': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'a': consts.string.types.REAL,
                'b': consts.string.types.REAL,
                'c': consts.string.types.REAL,
                'd': consts.string.types.REAL,
                'e': consts.string.types.REAL,
                'f': consts.string.types.REAL,
                'g': consts.string.types.REAL,
                'x': consts.string.types.REAL,
                'y': None,
                'z': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'a': consts.string.types.REAL,
                'b': consts.string.types.REAL,
                'c': consts.string.types.REAL,
                'd': consts.string.types.REAL,
                'e': consts.string.types.REAL,
                'f': consts.string.types.REAL,
                'g': consts.string.types.REAL,
                'x': consts.string.types.REAL,
                'y': consts.string.types.REAL,
                'z': None,
            },
        ]

    class Test_Mcnp(classes.Test_Mcnp):
        element = pymcnp.inp.Sq
        EXAMPLES_VALID = [
            # 3.2
            '12 SQ -0.083333333 1 1 0 0 0 68.52083 -26.5 0 0.',
            '3 SQ 1 -1.5 1 0 0 0 -0.625 0 2.5 0',
            # 3.3
            '999 SQ 25 100 0 0 0 0 -4 0 0 0 $ surface for cell CCC',
            consts.string.inp.SQ,
        ]
        EXAMPLES_INVALID = ['hello']

    class Test_Operations(classes.Test_Operations):
        EXAMPLES = [
            (consts.ast.inp.SQ, consts.ast.inp.SQ),
        ]
