import pymcnp
from ... import consts
from ... import classes


class Test_Lea:
    class Test_Init(classes.Test_Init):
        element = pymcnp.inp.Lea
        EXAMPLES_VALID = [
            {
                'ipht': consts.string.types.INTEGER,
                'icc': consts.string.types.INTEGER,
                'nobalc': consts.string.types.INTEGER,
                'nobale': consts.string.types.INTEGER,
                'ifbrk': consts.string.types.INTEGER,
                'ilvden': consts.string.types.INTEGER,
                'ievap': consts.string.types.INTEGER,
                'nofis': consts.string.types.INTEGER,
            },
            {'ipht': 1, 'icc': 1, 'nobalc': 1, 'nobale': 1, 'ifbrk': 1, 'ilvden': 1, 'ievap': 1, 'nofis': 1},
            {
                'ipht': consts.ast.types.INTEGER,
                'icc': consts.ast.types.INTEGER,
                'nobalc': consts.ast.types.INTEGER,
                'nobale': consts.ast.types.INTEGER,
                'ifbrk': consts.ast.types.INTEGER,
                'ilvden': consts.ast.types.INTEGER,
                'ievap': consts.ast.types.INTEGER,
                'nofis': consts.ast.types.INTEGER,
            },
            {
                'ipht': None,
                'icc': consts.string.types.INTEGER,
                'nobalc': consts.string.types.INTEGER,
                'nobale': consts.string.types.INTEGER,
                'ifbrk': consts.string.types.INTEGER,
                'ilvden': consts.string.types.INTEGER,
                'ievap': consts.string.types.INTEGER,
                'nofis': consts.string.types.INTEGER,
            },
            {
                'ipht': consts.string.types.INTEGER,
                'icc': None,
                'nobalc': consts.string.types.INTEGER,
                'nobale': consts.string.types.INTEGER,
                'ifbrk': consts.string.types.INTEGER,
                'ilvden': consts.string.types.INTEGER,
                'ievap': consts.string.types.INTEGER,
                'nofis': consts.string.types.INTEGER,
            },
            {
                'ipht': consts.string.types.INTEGER,
                'icc': consts.string.types.INTEGER,
                'nobalc': None,
                'nobale': consts.string.types.INTEGER,
                'ifbrk': consts.string.types.INTEGER,
                'ilvden': consts.string.types.INTEGER,
                'ievap': consts.string.types.INTEGER,
                'nofis': consts.string.types.INTEGER,
            },
            {
                'ipht': consts.string.types.INTEGER,
                'icc': consts.string.types.INTEGER,
                'nobalc': consts.string.types.INTEGER,
                'nobale': None,
                'ifbrk': consts.string.types.INTEGER,
                'ilvden': consts.string.types.INTEGER,
                'ievap': consts.string.types.INTEGER,
                'nofis': consts.string.types.INTEGER,
            },
            {
                'ipht': consts.string.types.INTEGER,
                'icc': consts.string.types.INTEGER,
                'nobalc': consts.string.types.INTEGER,
                'nobale': consts.string.types.INTEGER,
                'ifbrk': None,
                'ilvden': consts.string.types.INTEGER,
                'ievap': consts.string.types.INTEGER,
                'nofis': consts.string.types.INTEGER,
            },
            {
                'ipht': consts.string.types.INTEGER,
                'icc': consts.string.types.INTEGER,
                'nobalc': consts.string.types.INTEGER,
                'nobale': consts.string.types.INTEGER,
                'ifbrk': consts.string.types.INTEGER,
                'ilvden': None,
                'ievap': consts.string.types.INTEGER,
                'nofis': consts.string.types.INTEGER,
            },
            {
                'ipht': consts.string.types.INTEGER,
                'icc': consts.string.types.INTEGER,
                'nobalc': consts.string.types.INTEGER,
                'nobale': consts.string.types.INTEGER,
                'ifbrk': consts.string.types.INTEGER,
                'ilvden': consts.string.types.INTEGER,
                'ievap': None,
                'nofis': consts.string.types.INTEGER,
            },
            {
                'ipht': consts.string.types.INTEGER,
                'icc': consts.string.types.INTEGER,
                'nobalc': consts.string.types.INTEGER,
                'nobale': consts.string.types.INTEGER,
                'ifbrk': consts.string.types.INTEGER,
                'ilvden': consts.string.types.INTEGER,
                'ievap': consts.string.types.INTEGER,
                'nofis': None,
            },
        ]
        EXAMPLES_INVALID = [
            {
                'ipht': -9999,
                'icc': consts.string.types.INTEGER,
                'nobalc': consts.string.types.INTEGER,
                'nobale': consts.string.types.INTEGER,
                'ifbrk': consts.string.types.INTEGER,
                'ilvden': consts.string.types.INTEGER,
                'ievap': consts.string.types.INTEGER,
                'nofis': consts.string.types.INTEGER,
            },
            {
                'ipht': consts.string.types.INTEGER,
                'icc': -9999,
                'nobalc': consts.string.types.INTEGER,
                'nobale': consts.string.types.INTEGER,
                'ifbrk': consts.string.types.INTEGER,
                'ilvden': consts.string.types.INTEGER,
                'ievap': consts.string.types.INTEGER,
                'nofis': consts.string.types.INTEGER,
            },
            {
                'ipht': consts.string.types.INTEGER,
                'icc': consts.string.types.INTEGER,
                'nobalc': -9999,
                'nobale': consts.string.types.INTEGER,
                'ifbrk': consts.string.types.INTEGER,
                'ilvden': consts.string.types.INTEGER,
                'ievap': consts.string.types.INTEGER,
                'nofis': consts.string.types.INTEGER,
            },
            {
                'ipht': consts.string.types.INTEGER,
                'icc': consts.string.types.INTEGER,
                'nobalc': consts.string.types.INTEGER,
                'nobale': -9999,
                'ifbrk': consts.string.types.INTEGER,
                'ilvden': consts.string.types.INTEGER,
                'ievap': consts.string.types.INTEGER,
                'nofis': consts.string.types.INTEGER,
            },
            {
                'ipht': consts.string.types.INTEGER,
                'icc': consts.string.types.INTEGER,
                'nobalc': consts.string.types.INTEGER,
                'nobale': consts.string.types.INTEGER,
                'ifbrk': -9999,
                'ilvden': consts.string.types.INTEGER,
                'ievap': consts.string.types.INTEGER,
                'nofis': consts.string.types.INTEGER,
            },
            {
                'ipht': consts.string.types.INTEGER,
                'icc': consts.string.types.INTEGER,
                'nobalc': consts.string.types.INTEGER,
                'nobale': consts.string.types.INTEGER,
                'ifbrk': consts.string.types.INTEGER,
                'ilvden': -9999,
                'ievap': consts.string.types.INTEGER,
                'nofis': consts.string.types.INTEGER,
            },
            {
                'ipht': consts.string.types.INTEGER,
                'icc': consts.string.types.INTEGER,
                'nobalc': consts.string.types.INTEGER,
                'nobale': consts.string.types.INTEGER,
                'ifbrk': consts.string.types.INTEGER,
                'ilvden': consts.string.types.INTEGER,
                'ievap': -9999,
                'nofis': consts.string.types.INTEGER,
            },
            {
                'ipht': consts.string.types.INTEGER,
                'icc': consts.string.types.INTEGER,
                'nobalc': consts.string.types.INTEGER,
                'nobale': consts.string.types.INTEGER,
                'ifbrk': consts.string.types.INTEGER,
                'ilvden': consts.string.types.INTEGER,
                'ievap': consts.string.types.INTEGER,
                'nofis': -9999,
            },
        ]

    class Test_Mcnp(classes.Test_Mcnp):
        element = pymcnp.inp.Lea
        EXAMPLES_VALID = [consts.string.inp.LEA]
        EXAMPLES_INVALID = ['hello']
