import pymcnp
from ... import consts
from ... import classes


class Test_Ell:
    class Test_Init(classes.Test_Init):
        element = pymcnp.inp.Ell
        EXAMPLES_VALID = [
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'v1x': consts.string.types.REAL,
                'v1y': consts.string.types.REAL,
                'v1z': consts.string.types.REAL,
                'v2x': consts.string.types.REAL,
                'v2y': consts.string.types.REAL,
                'v2z': consts.string.types.REAL,
                'rm': consts.string.types.REAL,
            },
            {'prefix': '*', 'number': 1, 'transform': 1, 'v1x': 3.1, 'v1y': 3.1, 'v1z': 3.1, 'v2x': 3.1, 'v2y': 3.1, 'v2z': 3.1, 'rm': 3.1},
            {
                'prefix': pymcnp.types.String('*'),
                'number': consts.ast.types.INTEGER,
                'transform': consts.ast.types.INTEGER,
                'v1x': consts.ast.types.REAL,
                'v1y': consts.ast.types.REAL,
                'v1z': consts.ast.types.REAL,
                'v2x': consts.ast.types.REAL,
                'v2y': consts.ast.types.REAL,
                'v2z': consts.ast.types.REAL,
                'rm': consts.ast.types.REAL,
            },
            {
                'prefix': None,
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'v1x': consts.string.types.REAL,
                'v1y': consts.string.types.REAL,
                'v1z': consts.string.types.REAL,
                'v2x': consts.string.types.REAL,
                'v2y': consts.string.types.REAL,
                'v2z': consts.string.types.REAL,
                'rm': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': None,
                'transform': consts.string.types.INTEGER,
                'v1x': consts.string.types.REAL,
                'v1y': consts.string.types.REAL,
                'v1z': consts.string.types.REAL,
                'v2x': consts.string.types.REAL,
                'v2y': consts.string.types.REAL,
                'v2z': consts.string.types.REAL,
                'rm': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': None,
                'v1x': consts.string.types.REAL,
                'v1y': consts.string.types.REAL,
                'v1z': consts.string.types.REAL,
                'v2x': consts.string.types.REAL,
                'v2y': consts.string.types.REAL,
                'v2z': consts.string.types.REAL,
                'rm': consts.string.types.REAL,
            },
        ]
        EXAMPLES_INVALID = [
            {
                'prefix': 'a',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'v1x': consts.string.types.REAL,
                'v1y': consts.string.types.REAL,
                'v1z': consts.string.types.REAL,
                'v2x': consts.string.types.REAL,
                'v2y': consts.string.types.REAL,
                'v2z': consts.string.types.REAL,
                'rm': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': '0',
                'transform': consts.string.types.INTEGER,
                'v1x': consts.string.types.REAL,
                'v1y': consts.string.types.REAL,
                'v1z': consts.string.types.REAL,
                'v2x': consts.string.types.REAL,
                'v2y': consts.string.types.REAL,
                'v2z': consts.string.types.REAL,
                'rm': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': '1000',
                'v1x': consts.string.types.REAL,
                'v1y': consts.string.types.REAL,
                'v1z': consts.string.types.REAL,
                'v2x': consts.string.types.REAL,
                'v2y': consts.string.types.REAL,
                'v2z': consts.string.types.REAL,
                'rm': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'v1x': None,
                'v1y': consts.string.types.REAL,
                'v1z': consts.string.types.REAL,
                'v2x': consts.string.types.REAL,
                'v2y': consts.string.types.REAL,
                'v2z': consts.string.types.REAL,
                'rm': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'v1x': consts.string.types.REAL,
                'v1y': None,
                'v1z': consts.string.types.REAL,
                'v2x': consts.string.types.REAL,
                'v2y': consts.string.types.REAL,
                'v2z': consts.string.types.REAL,
                'rm': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'v1x': consts.string.types.REAL,
                'v1y': consts.string.types.REAL,
                'v1z': None,
                'v2x': consts.string.types.REAL,
                'v2y': consts.string.types.REAL,
                'v2z': consts.string.types.REAL,
                'rm': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'v1x': consts.string.types.REAL,
                'v1y': consts.string.types.REAL,
                'v1z': consts.string.types.REAL,
                'v2x': None,
                'v2y': consts.string.types.REAL,
                'v2z': consts.string.types.REAL,
                'rm': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'v1x': consts.string.types.REAL,
                'v1y': consts.string.types.REAL,
                'v1z': consts.string.types.REAL,
                'v2x': consts.string.types.REAL,
                'v2y': None,
                'v2z': consts.string.types.REAL,
                'rm': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'v1x': consts.string.types.REAL,
                'v1y': consts.string.types.REAL,
                'v1z': consts.string.types.REAL,
                'v2x': consts.string.types.REAL,
                'v2y': consts.string.types.REAL,
                'v2z': None,
                'rm': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'v1x': consts.string.types.REAL,
                'v1y': consts.string.types.REAL,
                'v1z': consts.string.types.REAL,
                'v2x': consts.string.types.REAL,
                'v2y': consts.string.types.REAL,
                'v2z': consts.string.types.REAL,
                'rm': None,
            },
        ]

    class Test_Mcnp(classes.Test_Mcnp):
        element = pymcnp.inp.Ell
        EXAMPLES_VALID = [consts.string.inp.ELL]
        EXAMPLES_INVALID = ['hello']

    class Test_Show(classes.Test_Show):
        element = pymcnp.inp.Ell
        EXAMPLES = [
            consts.string.inp.ELL,
            '1 ell 1 2 3 4 5 6 7',
            '1 ell 1 2 3 4 5 6 -7',
        ]

    class Test_Operations(classes.Test_Operations):
        EXAMPLES = [(consts.ast.inp.ELL, consts.ast.inp.ELL)]
