import pymcnp
from ... import consts
from ... import classes


class Test_Gq:
    class Test_Init(classes.Test_Init):
        element = pymcnp.inp.Gq
        EXAMPLES_VALID = [
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'a': consts.string.types.REAL,
                'b': consts.string.types.REAL,
                'c': consts.string.types.REAL,
                'd': consts.string.types.REAL,
                'e': consts.string.types.REAL,
                'f': consts.string.types.REAL,
                'g': consts.string.types.REAL,
                'h': consts.string.types.REAL,
                'j': consts.string.types.REAL,
                'k': consts.string.types.REAL,
            },
            {'prefix': '*', 'number': 1, 'transform': 1, 'a': 3.1, 'b': 3.1, 'c': 3.1, 'd': 3.1, 'e': 3.1, 'f': 3.1, 'g': 3.1, 'h': 3.1, 'j': 3.1, 'k': 3.1},
            {
                'prefix': pymcnp.types.String('*'),
                'number': consts.ast.types.INTEGER,
                'transform': consts.ast.types.INTEGER,
                'a': consts.ast.types.REAL,
                'b': consts.ast.types.REAL,
                'c': consts.ast.types.REAL,
                'd': consts.ast.types.REAL,
                'e': consts.ast.types.REAL,
                'f': consts.ast.types.REAL,
                'g': consts.ast.types.REAL,
                'h': consts.ast.types.REAL,
                'j': consts.ast.types.REAL,
                'k': consts.ast.types.REAL,
            },
            {
                'prefix': None,
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'a': consts.string.types.REAL,
                'b': consts.string.types.REAL,
                'c': consts.string.types.REAL,
                'd': consts.string.types.REAL,
                'e': consts.string.types.REAL,
                'f': consts.string.types.REAL,
                'g': consts.string.types.REAL,
                'h': consts.string.types.REAL,
                'j': consts.string.types.REAL,
                'k': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': None,
                'transform': consts.string.types.INTEGER,
                'a': consts.string.types.REAL,
                'b': consts.string.types.REAL,
                'c': consts.string.types.REAL,
                'd': consts.string.types.REAL,
                'e': consts.string.types.REAL,
                'f': consts.string.types.REAL,
                'g': consts.string.types.REAL,
                'h': consts.string.types.REAL,
                'j': consts.string.types.REAL,
                'k': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': None,
                'a': consts.string.types.REAL,
                'b': consts.string.types.REAL,
                'c': consts.string.types.REAL,
                'd': consts.string.types.REAL,
                'e': consts.string.types.REAL,
                'f': consts.string.types.REAL,
                'g': consts.string.types.REAL,
                'h': consts.string.types.REAL,
                'j': consts.string.types.REAL,
                'k': consts.string.types.REAL,
            },
        ]
        EXAMPLES_INVALID = [
            {
                'prefix': 'a',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'a': consts.string.types.REAL,
                'b': consts.string.types.REAL,
                'c': consts.string.types.REAL,
                'd': consts.string.types.REAL,
                'e': consts.string.types.REAL,
                'f': consts.string.types.REAL,
                'g': consts.string.types.REAL,
                'h': consts.string.types.REAL,
                'j': consts.string.types.REAL,
                'k': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': '0',
                'transform': consts.string.types.INTEGER,
                'a': consts.string.types.REAL,
                'b': consts.string.types.REAL,
                'c': consts.string.types.REAL,
                'd': consts.string.types.REAL,
                'e': consts.string.types.REAL,
                'f': consts.string.types.REAL,
                'g': consts.string.types.REAL,
                'h': consts.string.types.REAL,
                'j': consts.string.types.REAL,
                'k': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': '1000',
                'a': consts.string.types.REAL,
                'b': consts.string.types.REAL,
                'c': consts.string.types.REAL,
                'd': consts.string.types.REAL,
                'e': consts.string.types.REAL,
                'f': consts.string.types.REAL,
                'g': consts.string.types.REAL,
                'h': consts.string.types.REAL,
                'j': consts.string.types.REAL,
                'k': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'a': None,
                'b': consts.string.types.REAL,
                'c': consts.string.types.REAL,
                'd': consts.string.types.REAL,
                'e': consts.string.types.REAL,
                'f': consts.string.types.REAL,
                'g': consts.string.types.REAL,
                'h': consts.string.types.REAL,
                'j': consts.string.types.REAL,
                'k': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'a': consts.string.types.REAL,
                'b': None,
                'c': consts.string.types.REAL,
                'd': consts.string.types.REAL,
                'e': consts.string.types.REAL,
                'f': consts.string.types.REAL,
                'g': consts.string.types.REAL,
                'h': consts.string.types.REAL,
                'j': consts.string.types.REAL,
                'k': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'a': consts.string.types.REAL,
                'b': consts.string.types.REAL,
                'c': None,
                'd': consts.string.types.REAL,
                'e': consts.string.types.REAL,
                'f': consts.string.types.REAL,
                'g': consts.string.types.REAL,
                'h': consts.string.types.REAL,
                'j': consts.string.types.REAL,
                'k': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'a': consts.string.types.REAL,
                'b': consts.string.types.REAL,
                'c': consts.string.types.REAL,
                'd': None,
                'e': consts.string.types.REAL,
                'f': consts.string.types.REAL,
                'g': consts.string.types.REAL,
                'h': consts.string.types.REAL,
                'j': consts.string.types.REAL,
                'k': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'a': consts.string.types.REAL,
                'b': consts.string.types.REAL,
                'c': consts.string.types.REAL,
                'd': consts.string.types.REAL,
                'e': None,
                'f': consts.string.types.REAL,
                'g': consts.string.types.REAL,
                'h': consts.string.types.REAL,
                'j': consts.string.types.REAL,
                'k': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'a': consts.string.types.REAL,
                'b': consts.string.types.REAL,
                'c': consts.string.types.REAL,
                'd': consts.string.types.REAL,
                'e': consts.string.types.REAL,
                'f': None,
                'g': consts.string.types.REAL,
                'h': consts.string.types.REAL,
                'j': consts.string.types.REAL,
                'k': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'a': consts.string.types.REAL,
                'b': consts.string.types.REAL,
                'c': consts.string.types.REAL,
                'd': consts.string.types.REAL,
                'e': consts.string.types.REAL,
                'f': consts.string.types.REAL,
                'g': None,
                'h': consts.string.types.REAL,
                'j': consts.string.types.REAL,
                'k': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'a': consts.string.types.REAL,
                'b': consts.string.types.REAL,
                'c': consts.string.types.REAL,
                'd': consts.string.types.REAL,
                'e': consts.string.types.REAL,
                'f': consts.string.types.REAL,
                'g': consts.string.types.REAL,
                'h': None,
                'j': consts.string.types.REAL,
                'k': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'a': consts.string.types.REAL,
                'b': consts.string.types.REAL,
                'c': consts.string.types.REAL,
                'd': consts.string.types.REAL,
                'e': consts.string.types.REAL,
                'f': consts.string.types.REAL,
                'g': consts.string.types.REAL,
                'h': consts.string.types.REAL,
                'j': None,
                'k': consts.string.types.REAL,
            },
            {
                'prefix': '*',
                'number': consts.string.types.INTEGER,
                'transform': consts.string.types.INTEGER,
                'a': consts.string.types.REAL,
                'b': consts.string.types.REAL,
                'c': consts.string.types.REAL,
                'd': consts.string.types.REAL,
                'e': consts.string.types.REAL,
                'f': consts.string.types.REAL,
                'g': consts.string.types.REAL,
                'h': consts.string.types.REAL,
                'j': consts.string.types.REAL,
                'k': None,
            },
        ]

    class Test_Mcnp(classes.Test_Mcnp):
        element = pymcnp.inp.Gq
        EXAMPLES_VALID = [
            # 3.2
            '11 GQ 1 0.25 0.75 0 -0.866\n 0 -12 -2 3.464 39',
            consts.string.inp.GQ,
        ]
        EXAMPLES_INVALID = ['hello']

    class Test_Operations(classes.Test_Operations):
        EXAMPLES = [(consts.ast.inp.GQ, consts.ast.inp.GQ)]
