import pymcnp
from ... import consts
from ... import classes


class Test_Phys_3:
    class Test_Init(classes.Test_Init):
        element = pymcnp.inp.Phys_3
        EXAMPLES_VALID = [
            {
                'emax': consts.string.types.REAL,
                'ean': consts.string.types.REAL,
                'tabl': consts.string.types.REAL,
                'istrg': consts.string.types.INTEGER,
                'recl': '0.8',
                'i_mcs_model': consts.string.types.INTEGER,
                'i_int_model': consts.string.types.INTEGER,
                'i_els_model': '-1',
                'efac': '0.8',
                'ckvnum': '0.8',
                'drp': consts.string.types.REAL,
            },
            {'emax': 3.1, 'ean': 3.1, 'tabl': 3.1, 'istrg': 1, 'recl': 0.8, 'i_mcs_model': 1, 'i_int_model': 1, 'i_els_model': -1, 'efac': 0.8, 'ckvnum': 0.8, 'drp': 3.1},
            {
                'emax': consts.ast.types.REAL,
                'ean': consts.ast.types.REAL,
                'tabl': consts.ast.types.REAL,
                'istrg': consts.ast.types.INTEGER,
                'recl': pymcnp.types.Real(0.8),
                'i_mcs_model': consts.ast.types.INTEGER,
                'i_int_model': consts.ast.types.INTEGER,
                'i_els_model': pymcnp.types.Integer(-1),
                'efac': pymcnp.types.Real(0.8),
                'ckvnum': pymcnp.types.Real(0.8),
                'drp': consts.ast.types.REAL,
            },
            {
                'emax': None,
                'ean': consts.string.types.REAL,
                'tabl': consts.string.types.REAL,
                'istrg': consts.string.types.INTEGER,
                'recl': '0.8',
                'i_mcs_model': consts.string.types.INTEGER,
                'i_int_model': consts.string.types.INTEGER,
                'i_els_model': '-1',
                'efac': '0.8',
                'ckvnum': '0.8',
                'drp': consts.string.types.REAL,
            },
            {
                'emax': consts.string.types.REAL,
                'ean': None,
                'tabl': consts.string.types.REAL,
                'istrg': consts.string.types.INTEGER,
                'recl': '0.8',
                'i_mcs_model': consts.string.types.INTEGER,
                'i_int_model': consts.string.types.INTEGER,
                'i_els_model': '-1',
                'efac': '0.8',
                'ckvnum': '0.8',
                'drp': consts.string.types.REAL,
            },
            {
                'emax': consts.string.types.REAL,
                'ean': consts.string.types.REAL,
                'tabl': None,
                'istrg': consts.string.types.INTEGER,
                'recl': '0.8',
                'i_mcs_model': consts.string.types.INTEGER,
                'i_int_model': consts.string.types.INTEGER,
                'i_els_model': '-1',
                'efac': '0.8',
                'ckvnum': '0.8',
                'drp': consts.string.types.REAL,
            },
            {
                'emax': consts.string.types.REAL,
                'ean': consts.string.types.REAL,
                'tabl': consts.string.types.REAL,
                'istrg': None,
                'recl': '0.8',
                'i_mcs_model': consts.string.types.INTEGER,
                'i_int_model': consts.string.types.INTEGER,
                'i_els_model': '-1',
                'efac': '0.8',
                'ckvnum': '0.8',
                'drp': consts.string.types.REAL,
            },
            {
                'emax': consts.string.types.REAL,
                'ean': consts.string.types.REAL,
                'tabl': consts.string.types.REAL,
                'istrg': consts.string.types.INTEGER,
                'recl': None,
                'i_mcs_model': consts.string.types.INTEGER,
                'i_int_model': consts.string.types.INTEGER,
                'i_els_model': '-1',
                'efac': '0.8',
                'ckvnum': '0.8',
                'drp': consts.string.types.REAL,
            },
            {
                'emax': consts.string.types.REAL,
                'ean': consts.string.types.REAL,
                'tabl': consts.string.types.REAL,
                'istrg': consts.string.types.INTEGER,
                'recl': '0.8',
                'i_mcs_model': None,
                'i_int_model': consts.string.types.INTEGER,
                'i_els_model': '-1',
                'efac': '0.8',
                'ckvnum': '0.8',
                'drp': consts.string.types.REAL,
            },
            {
                'emax': consts.string.types.REAL,
                'ean': consts.string.types.REAL,
                'tabl': consts.string.types.REAL,
                'istrg': consts.string.types.INTEGER,
                'recl': '0.8',
                'i_mcs_model': consts.string.types.INTEGER,
                'i_int_model': None,
                'i_els_model': '-1',
                'efac': '0.8',
                'ckvnum': '0.8',
                'drp': consts.string.types.REAL,
            },
            {
                'emax': consts.string.types.REAL,
                'ean': consts.string.types.REAL,
                'tabl': consts.string.types.REAL,
                'istrg': consts.string.types.INTEGER,
                'recl': '0.8',
                'i_mcs_model': consts.string.types.INTEGER,
                'i_int_model': consts.string.types.INTEGER,
                'i_els_model': None,
                'efac': '0.8',
                'ckvnum': '0.8',
                'drp': consts.string.types.REAL,
            },
            {
                'emax': consts.string.types.REAL,
                'ean': consts.string.types.REAL,
                'tabl': consts.string.types.REAL,
                'istrg': consts.string.types.INTEGER,
                'recl': '0.8',
                'i_mcs_model': consts.string.types.INTEGER,
                'i_int_model': consts.string.types.INTEGER,
                'i_els_model': '-1',
                'efac': None,
                'ckvnum': '0.8',
                'drp': consts.string.types.REAL,
            },
            {
                'emax': consts.string.types.REAL,
                'ean': consts.string.types.REAL,
                'tabl': consts.string.types.REAL,
                'istrg': consts.string.types.INTEGER,
                'recl': '0.8',
                'i_mcs_model': consts.string.types.INTEGER,
                'i_int_model': consts.string.types.INTEGER,
                'i_els_model': '-1',
                'efac': '0.8',
                'ckvnum': None,
                'drp': consts.string.types.REAL,
            },
            {
                'emax': consts.string.types.REAL,
                'ean': consts.string.types.REAL,
                'tabl': consts.string.types.REAL,
                'istrg': consts.string.types.INTEGER,
                'recl': '0.8',
                'i_mcs_model': consts.string.types.INTEGER,
                'i_int_model': consts.string.types.INTEGER,
                'i_els_model': '-1',
                'efac': '0.8',
                'ckvnum': '0.8',
                'drp': None,
            },
        ]
        EXAMPLES_INVALID = [
            {
                'emax': consts.string.types.REAL,
                'ean': consts.string.types.REAL,
                'tabl': -3.1,
                'istrg': consts.string.types.INTEGER,
                'recl': '0.8',
                'i_mcs_model': consts.string.types.INTEGER,
                'i_int_model': consts.string.types.INTEGER,
                'i_els_model': '-1',
                'efac': '0.8',
                'ckvnum': '0.8',
                'drp': consts.string.types.REAL,
            },
            {
                'emax': consts.string.types.REAL,
                'ean': consts.string.types.REAL,
                'tabl': consts.string.types.REAL,
                'istrg': -9999,
                'recl': '0.8',
                'i_mcs_model': consts.string.types.INTEGER,
                'i_int_model': consts.string.types.INTEGER,
                'i_els_model': '-1',
                'efac': '0.8',
                'ckvnum': '0.8',
                'drp': consts.string.types.REAL,
            },
            {
                'emax': consts.string.types.REAL,
                'ean': consts.string.types.REAL,
                'tabl': consts.string.types.REAL,
                'istrg': consts.string.types.INTEGER,
                'recl': '3.1',
                'i_mcs_model': consts.string.types.INTEGER,
                'i_int_model': consts.string.types.INTEGER,
                'i_els_model': '-1',
                'efac': '0.8',
                'ckvnum': '0.8',
                'drp': consts.string.types.REAL,
            },
            {
                'emax': consts.string.types.REAL,
                'ean': consts.string.types.REAL,
                'tabl': consts.string.types.REAL,
                'istrg': consts.string.types.INTEGER,
                'recl': '0.8',
                'i_mcs_model': -9999,
                'i_int_model': consts.string.types.INTEGER,
                'i_els_model': '-1',
                'efac': '0.8',
                'ckvnum': '0.8',
                'drp': consts.string.types.REAL,
            },
            {
                'emax': consts.string.types.REAL,
                'ean': consts.string.types.REAL,
                'tabl': consts.string.types.REAL,
                'istrg': consts.string.types.INTEGER,
                'recl': '0.8',
                'i_mcs_model': consts.string.types.INTEGER,
                'i_int_model': -9999,
                'i_els_model': '-1',
                'efac': '0.8',
                'ckvnum': '0.8',
                'drp': consts.string.types.REAL,
            },
            {
                'emax': consts.string.types.REAL,
                'ean': consts.string.types.REAL,
                'tabl': consts.string.types.REAL,
                'istrg': consts.string.types.INTEGER,
                'recl': '0.8',
                'i_mcs_model': consts.string.types.INTEGER,
                'i_int_model': consts.string.types.INTEGER,
                'i_els_model': '1',
                'efac': '0.8',
                'ckvnum': '0.8',
                'drp': consts.string.types.REAL,
            },
            {
                'emax': consts.string.types.REAL,
                'ean': consts.string.types.REAL,
                'tabl': consts.string.types.REAL,
                'istrg': consts.string.types.INTEGER,
                'recl': '0.8',
                'i_mcs_model': consts.string.types.INTEGER,
                'i_int_model': consts.string.types.INTEGER,
                'i_els_model': '-1',
                'efac': '3.1',
                'ckvnum': '0.8',
                'drp': consts.string.types.REAL,
            },
            {
                'emax': consts.string.types.REAL,
                'ean': consts.string.types.REAL,
                'tabl': consts.string.types.REAL,
                'istrg': consts.string.types.INTEGER,
                'recl': '0.8',
                'i_mcs_model': consts.string.types.INTEGER,
                'i_int_model': consts.string.types.INTEGER,
                'i_els_model': '-1',
                'efac': '0.8',
                'ckvnum': '3.1',
                'drp': consts.string.types.REAL,
            },
            {
                'emax': consts.string.types.REAL,
                'ean': consts.string.types.REAL,
                'tabl': consts.string.types.REAL,
                'istrg': consts.string.types.INTEGER,
                'recl': '0.8',
                'i_mcs_model': consts.string.types.INTEGER,
                'i_int_model': consts.string.types.INTEGER,
                'i_els_model': '-1',
                'efac': '0.8',
                'ckvnum': '0.8',
                'drp': -3.1,
            },
        ]

    class Test_Mcnp(classes.Test_Mcnp):
        element = pymcnp.inp.Phys_3
        EXAMPLES_VALID = [consts.string.inp.PHYS_3]
        EXAMPLES_INVALID = ['hello']
