import pymcnp
from ... import consts
from ... import classes


class Test_Wwp:
    class Test_Init(classes.Test_Init):
        element = pymcnp.inp.Wwp
        EXAMPLES_VALID = [
            {
                'designator': consts.string.types.DESIGNATOR,
                'wupn': consts.string.types.REAL,
                'wsurvn': consts.string.types.REAL,
                'mxspln': consts.string.types.REAL,
                'mwhere': consts.string.types.INTEGER,
                'switchn': consts.string.types.REAL,
                'mtime': consts.string.types.INTEGER,
                'wnrom': consts.string.types.REAL,
                'etsplt': consts.string.types.INTEGER,
                'wu': consts.string.types.REAL,
                'nmfp': consts.string.types.REAL,
            },
            {'designator': consts.string.types.DESIGNATOR, 'wupn': 3.1, 'wsurvn': 3.1, 'mxspln': 3.1, 'mwhere': 1, 'switchn': 3.1, 'mtime': 1, 'wnrom': 3.1, 'etsplt': 1, 'wu': 3.1, 'nmfp': 3.1},
            {
                'designator': consts.ast.types.DESIGNATOR,
                'wupn': consts.ast.types.REAL,
                'wsurvn': consts.ast.types.REAL,
                'mxspln': consts.ast.types.REAL,
                'mwhere': consts.ast.types.INTEGER,
                'switchn': consts.ast.types.REAL,
                'mtime': consts.ast.types.INTEGER,
                'wnrom': consts.ast.types.REAL,
                'etsplt': consts.ast.types.INTEGER,
                'wu': consts.ast.types.REAL,
                'nmfp': consts.ast.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'wupn': None,
                'wsurvn': consts.string.types.REAL,
                'mxspln': consts.string.types.REAL,
                'mwhere': consts.string.types.INTEGER,
                'switchn': consts.string.types.REAL,
                'mtime': consts.string.types.INTEGER,
                'wnrom': consts.string.types.REAL,
                'etsplt': consts.string.types.INTEGER,
                'wu': consts.string.types.REAL,
                'nmfp': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'wupn': consts.string.types.REAL,
                'wsurvn': None,
                'mxspln': consts.string.types.REAL,
                'mwhere': consts.string.types.INTEGER,
                'switchn': consts.string.types.REAL,
                'mtime': consts.string.types.INTEGER,
                'wnrom': consts.string.types.REAL,
                'etsplt': consts.string.types.INTEGER,
                'wu': consts.string.types.REAL,
                'nmfp': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'wupn': consts.string.types.REAL,
                'wsurvn': consts.string.types.REAL,
                'mxspln': None,
                'mwhere': consts.string.types.INTEGER,
                'switchn': consts.string.types.REAL,
                'mtime': consts.string.types.INTEGER,
                'wnrom': consts.string.types.REAL,
                'etsplt': consts.string.types.INTEGER,
                'wu': consts.string.types.REAL,
                'nmfp': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'wupn': consts.string.types.REAL,
                'wsurvn': consts.string.types.REAL,
                'mxspln': consts.string.types.REAL,
                'mwhere': None,
                'switchn': consts.string.types.REAL,
                'mtime': consts.string.types.INTEGER,
                'wnrom': consts.string.types.REAL,
                'etsplt': consts.string.types.INTEGER,
                'wu': consts.string.types.REAL,
                'nmfp': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'wupn': consts.string.types.REAL,
                'wsurvn': consts.string.types.REAL,
                'mxspln': consts.string.types.REAL,
                'mwhere': consts.string.types.INTEGER,
                'switchn': None,
                'mtime': consts.string.types.INTEGER,
                'wnrom': consts.string.types.REAL,
                'etsplt': consts.string.types.INTEGER,
                'wu': consts.string.types.REAL,
                'nmfp': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'wupn': consts.string.types.REAL,
                'wsurvn': consts.string.types.REAL,
                'mxspln': consts.string.types.REAL,
                'mwhere': consts.string.types.INTEGER,
                'switchn': consts.string.types.REAL,
                'mtime': None,
                'wnrom': consts.string.types.REAL,
                'etsplt': consts.string.types.INTEGER,
                'wu': consts.string.types.REAL,
                'nmfp': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'wupn': consts.string.types.REAL,
                'wsurvn': consts.string.types.REAL,
                'mxspln': consts.string.types.REAL,
                'mwhere': consts.string.types.INTEGER,
                'switchn': consts.string.types.REAL,
                'mtime': consts.string.types.INTEGER,
                'wnrom': None,
                'etsplt': consts.string.types.INTEGER,
                'wu': consts.string.types.REAL,
                'nmfp': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'wupn': consts.string.types.REAL,
                'wsurvn': consts.string.types.REAL,
                'mxspln': consts.string.types.REAL,
                'mwhere': consts.string.types.INTEGER,
                'switchn': consts.string.types.REAL,
                'mtime': consts.string.types.INTEGER,
                'wnrom': consts.string.types.REAL,
                'etsplt': None,
                'wu': consts.string.types.REAL,
                'nmfp': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'wupn': consts.string.types.REAL,
                'wsurvn': consts.string.types.REAL,
                'mxspln': consts.string.types.REAL,
                'mwhere': consts.string.types.INTEGER,
                'switchn': consts.string.types.REAL,
                'mtime': consts.string.types.INTEGER,
                'wnrom': consts.string.types.REAL,
                'etsplt': consts.string.types.INTEGER,
                'wu': None,
                'nmfp': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'wupn': consts.string.types.REAL,
                'wsurvn': consts.string.types.REAL,
                'mxspln': consts.string.types.REAL,
                'mwhere': consts.string.types.INTEGER,
                'switchn': consts.string.types.REAL,
                'mtime': consts.string.types.INTEGER,
                'wnrom': consts.string.types.REAL,
                'etsplt': consts.string.types.INTEGER,
                'wu': consts.string.types.REAL,
                'nmfp': None,
            },
        ]
        EXAMPLES_INVALID = [
            {
                'designator': None,
                'wupn': consts.string.types.REAL,
                'wsurvn': consts.string.types.REAL,
                'mxspln': consts.string.types.REAL,
                'mwhere': consts.string.types.INTEGER,
                'switchn': consts.string.types.REAL,
                'mtime': consts.string.types.INTEGER,
                'wnrom': consts.string.types.REAL,
                'etsplt': consts.string.types.INTEGER,
                'wu': consts.string.types.REAL,
                'nmfp': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'wupn': -3.1,
                'wsurvn': consts.string.types.REAL,
                'mxspln': consts.string.types.REAL,
                'mwhere': consts.string.types.INTEGER,
                'switchn': consts.string.types.REAL,
                'mtime': consts.string.types.INTEGER,
                'wnrom': consts.string.types.REAL,
                'etsplt': consts.string.types.INTEGER,
                'wu': consts.string.types.REAL,
                'nmfp': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'wupn': consts.string.types.REAL,
                'wsurvn': -3.1,
                'mxspln': consts.string.types.REAL,
                'mwhere': consts.string.types.INTEGER,
                'switchn': consts.string.types.REAL,
                'mtime': consts.string.types.INTEGER,
                'wnrom': consts.string.types.REAL,
                'etsplt': consts.string.types.INTEGER,
                'wu': consts.string.types.REAL,
                'nmfp': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'wupn': consts.string.types.REAL,
                'wsurvn': consts.string.types.REAL,
                'mxspln': -3.1,
                'mwhere': consts.string.types.INTEGER,
                'switchn': consts.string.types.REAL,
                'mtime': consts.string.types.INTEGER,
                'wnrom': consts.string.types.REAL,
                'etsplt': consts.string.types.INTEGER,
                'wu': consts.string.types.REAL,
                'nmfp': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'wupn': consts.string.types.REAL,
                'wsurvn': consts.string.types.REAL,
                'mxspln': consts.string.types.REAL,
                'mwhere': -9999,
                'switchn': consts.string.types.REAL,
                'mtime': consts.string.types.INTEGER,
                'wnrom': consts.string.types.REAL,
                'etsplt': consts.string.types.INTEGER,
                'wu': consts.string.types.REAL,
                'nmfp': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'wupn': consts.string.types.REAL,
                'wsurvn': consts.string.types.REAL,
                'mxspln': consts.string.types.REAL,
                'mwhere': consts.string.types.INTEGER,
                'switchn': consts.string.types.REAL,
                'mtime': consts.string.types.INTEGER,
                'wnrom': consts.string.types.REAL,
                'etsplt': -9999,
                'wu': consts.string.types.REAL,
                'nmfp': consts.string.types.REAL,
            },
        ]

    class Test_Mcnp(classes.Test_Mcnp):
        element = pymcnp.inp.Wwp
        EXAMPLES_VALID = [consts.string.inp.WWP]
        EXAMPLES_INVALID = ['hello']
