import pymcnp
from ... import consts
from ... import classes


class Test_Dxt:
    class Test_Init(classes.Test_Init):
        element = pymcnp.inp.Dxt
        EXAMPLES_VALID = [
            {
                'designator': consts.string.types.DESIGNATOR,
                'spheres_1': consts.string.inp.dxt.SHELL,
                'spheres_2': consts.string.inp.dxt.SHELL,
                'spheres_3': consts.string.inp.dxt.SHELL,
                'spheres_4': consts.string.inp.dxt.SHELL,
                'spheres_5': consts.string.inp.dxt.SHELL,
                'spheres_6': consts.string.inp.dxt.SHELL,
                'spheres_7': consts.string.inp.dxt.SHELL,
                'spheres_8': consts.string.inp.dxt.SHELL,
                'spheres_9': consts.string.inp.dxt.SHELL,
                'spheres_10': consts.string.inp.dxt.SHELL,
                'cutoff_1': consts.string.types.REAL,
                'cutoff_2': consts.string.types.REAL,
                'weight': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'spheres_1': consts.string.inp.dxt.SHELL,
                'spheres_2': consts.string.inp.dxt.SHELL,
                'spheres_3': consts.string.inp.dxt.SHELL,
                'spheres_4': consts.string.inp.dxt.SHELL,
                'spheres_5': consts.string.inp.dxt.SHELL,
                'spheres_6': consts.string.inp.dxt.SHELL,
                'spheres_7': consts.string.inp.dxt.SHELL,
                'spheres_8': consts.string.inp.dxt.SHELL,
                'spheres_9': consts.string.inp.dxt.SHELL,
                'spheres_10': consts.string.inp.dxt.SHELL,
                'cutoff_1': 3.1,
                'cutoff_2': 3.1,
                'weight': 3.1,
            },
            {
                'designator': consts.ast.types.DESIGNATOR,
                'spheres_1': consts.ast.inp.dxt.SHELL,
                'spheres_2': consts.ast.inp.dxt.SHELL,
                'spheres_3': consts.ast.inp.dxt.SHELL,
                'spheres_4': consts.ast.inp.dxt.SHELL,
                'spheres_5': consts.ast.inp.dxt.SHELL,
                'spheres_6': consts.ast.inp.dxt.SHELL,
                'spheres_7': consts.ast.inp.dxt.SHELL,
                'spheres_8': consts.ast.inp.dxt.SHELL,
                'spheres_9': consts.ast.inp.dxt.SHELL,
                'spheres_10': consts.ast.inp.dxt.SHELL,
                'cutoff_1': consts.ast.types.REAL,
                'cutoff_2': consts.ast.types.REAL,
                'weight': consts.ast.types.REAL,
            },
        ]
        EXAMPLES_INVALID = [
            {
                'designator': None,
                'spheres_1': consts.string.inp.dxt.SHELL,
                'spheres_2': consts.string.inp.dxt.SHELL,
                'spheres_3': consts.string.inp.dxt.SHELL,
                'spheres_4': consts.string.inp.dxt.SHELL,
                'spheres_5': consts.string.inp.dxt.SHELL,
                'spheres_6': consts.string.inp.dxt.SHELL,
                'spheres_7': consts.string.inp.dxt.SHELL,
                'spheres_8': consts.string.inp.dxt.SHELL,
                'spheres_9': consts.string.inp.dxt.SHELL,
                'spheres_10': consts.string.inp.dxt.SHELL,
                'cutoff_1': consts.string.types.REAL,
                'cutoff_2': consts.string.types.REAL,
                'weight': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'spheres_1': None,
                'spheres_2': consts.string.inp.dxt.SHELL,
                'spheres_3': consts.string.inp.dxt.SHELL,
                'spheres_4': consts.string.inp.dxt.SHELL,
                'spheres_5': consts.string.inp.dxt.SHELL,
                'spheres_6': consts.string.inp.dxt.SHELL,
                'spheres_7': consts.string.inp.dxt.SHELL,
                'spheres_8': consts.string.inp.dxt.SHELL,
                'spheres_9': consts.string.inp.dxt.SHELL,
                'spheres_10': consts.string.inp.dxt.SHELL,
                'cutoff_1': consts.string.types.REAL,
                'cutoff_2': consts.string.types.REAL,
                'weight': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'spheres_1': consts.string.inp.dxt.SHELL,
                'spheres_2': None,
                'spheres_3': consts.string.inp.dxt.SHELL,
                'spheres_4': consts.string.inp.dxt.SHELL,
                'spheres_5': consts.string.inp.dxt.SHELL,
                'spheres_6': consts.string.inp.dxt.SHELL,
                'spheres_7': consts.string.inp.dxt.SHELL,
                'spheres_8': consts.string.inp.dxt.SHELL,
                'spheres_9': consts.string.inp.dxt.SHELL,
                'spheres_10': consts.string.inp.dxt.SHELL,
                'cutoff_1': consts.string.types.REAL,
                'cutoff_2': consts.string.types.REAL,
                'weight': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'spheres_1': consts.string.inp.dxt.SHELL,
                'spheres_2': consts.string.inp.dxt.SHELL,
                'spheres_3': None,
                'spheres_4': consts.string.inp.dxt.SHELL,
                'spheres_5': consts.string.inp.dxt.SHELL,
                'spheres_6': consts.string.inp.dxt.SHELL,
                'spheres_7': consts.string.inp.dxt.SHELL,
                'spheres_8': consts.string.inp.dxt.SHELL,
                'spheres_9': consts.string.inp.dxt.SHELL,
                'spheres_10': consts.string.inp.dxt.SHELL,
                'cutoff_1': consts.string.types.REAL,
                'cutoff_2': consts.string.types.REAL,
                'weight': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'spheres_1': consts.string.inp.dxt.SHELL,
                'spheres_2': consts.string.inp.dxt.SHELL,
                'spheres_3': consts.string.inp.dxt.SHELL,
                'spheres_4': None,
                'spheres_5': consts.string.inp.dxt.SHELL,
                'spheres_6': consts.string.inp.dxt.SHELL,
                'spheres_7': consts.string.inp.dxt.SHELL,
                'spheres_8': consts.string.inp.dxt.SHELL,
                'spheres_9': consts.string.inp.dxt.SHELL,
                'spheres_10': consts.string.inp.dxt.SHELL,
                'cutoff_1': consts.string.types.REAL,
                'cutoff_2': consts.string.types.REAL,
                'weight': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'spheres_1': consts.string.inp.dxt.SHELL,
                'spheres_2': consts.string.inp.dxt.SHELL,
                'spheres_3': consts.string.inp.dxt.SHELL,
                'spheres_4': consts.string.inp.dxt.SHELL,
                'spheres_5': None,
                'spheres_6': consts.string.inp.dxt.SHELL,
                'spheres_7': consts.string.inp.dxt.SHELL,
                'spheres_8': consts.string.inp.dxt.SHELL,
                'spheres_9': consts.string.inp.dxt.SHELL,
                'spheres_10': consts.string.inp.dxt.SHELL,
                'cutoff_1': consts.string.types.REAL,
                'cutoff_2': consts.string.types.REAL,
                'weight': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'spheres_1': consts.string.inp.dxt.SHELL,
                'spheres_2': consts.string.inp.dxt.SHELL,
                'spheres_3': consts.string.inp.dxt.SHELL,
                'spheres_4': consts.string.inp.dxt.SHELL,
                'spheres_5': consts.string.inp.dxt.SHELL,
                'spheres_6': None,
                'spheres_7': consts.string.inp.dxt.SHELL,
                'spheres_8': consts.string.inp.dxt.SHELL,
                'spheres_9': consts.string.inp.dxt.SHELL,
                'spheres_10': consts.string.inp.dxt.SHELL,
                'cutoff_1': consts.string.types.REAL,
                'cutoff_2': consts.string.types.REAL,
                'weight': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'spheres_1': consts.string.inp.dxt.SHELL,
                'spheres_2': consts.string.inp.dxt.SHELL,
                'spheres_3': consts.string.inp.dxt.SHELL,
                'spheres_4': consts.string.inp.dxt.SHELL,
                'spheres_5': consts.string.inp.dxt.SHELL,
                'spheres_6': consts.string.inp.dxt.SHELL,
                'spheres_7': None,
                'spheres_8': consts.string.inp.dxt.SHELL,
                'spheres_9': consts.string.inp.dxt.SHELL,
                'spheres_10': consts.string.inp.dxt.SHELL,
                'cutoff_1': consts.string.types.REAL,
                'cutoff_2': consts.string.types.REAL,
                'weight': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'spheres_1': consts.string.inp.dxt.SHELL,
                'spheres_2': consts.string.inp.dxt.SHELL,
                'spheres_3': consts.string.inp.dxt.SHELL,
                'spheres_4': consts.string.inp.dxt.SHELL,
                'spheres_5': consts.string.inp.dxt.SHELL,
                'spheres_6': consts.string.inp.dxt.SHELL,
                'spheres_7': consts.string.inp.dxt.SHELL,
                'spheres_8': None,
                'spheres_9': consts.string.inp.dxt.SHELL,
                'spheres_10': consts.string.inp.dxt.SHELL,
                'cutoff_1': consts.string.types.REAL,
                'cutoff_2': consts.string.types.REAL,
                'weight': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'spheres_1': consts.string.inp.dxt.SHELL,
                'spheres_2': consts.string.inp.dxt.SHELL,
                'spheres_3': consts.string.inp.dxt.SHELL,
                'spheres_4': consts.string.inp.dxt.SHELL,
                'spheres_5': consts.string.inp.dxt.SHELL,
                'spheres_6': consts.string.inp.dxt.SHELL,
                'spheres_7': consts.string.inp.dxt.SHELL,
                'spheres_8': consts.string.inp.dxt.SHELL,
                'spheres_9': None,
                'spheres_10': consts.string.inp.dxt.SHELL,
                'cutoff_1': consts.string.types.REAL,
                'cutoff_2': consts.string.types.REAL,
                'weight': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'spheres_1': consts.string.inp.dxt.SHELL,
                'spheres_2': consts.string.inp.dxt.SHELL,
                'spheres_3': consts.string.inp.dxt.SHELL,
                'spheres_4': consts.string.inp.dxt.SHELL,
                'spheres_5': consts.string.inp.dxt.SHELL,
                'spheres_6': consts.string.inp.dxt.SHELL,
                'spheres_7': consts.string.inp.dxt.SHELL,
                'spheres_8': consts.string.inp.dxt.SHELL,
                'spheres_9': consts.string.inp.dxt.SHELL,
                'spheres_10': None,
                'cutoff_1': consts.string.types.REAL,
                'cutoff_2': consts.string.types.REAL,
                'weight': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'spheres_1': consts.string.inp.dxt.SHELL,
                'spheres_2': consts.string.inp.dxt.SHELL,
                'spheres_3': consts.string.inp.dxt.SHELL,
                'spheres_4': consts.string.inp.dxt.SHELL,
                'spheres_5': consts.string.inp.dxt.SHELL,
                'spheres_6': consts.string.inp.dxt.SHELL,
                'spheres_7': consts.string.inp.dxt.SHELL,
                'spheres_8': consts.string.inp.dxt.SHELL,
                'spheres_9': consts.string.inp.dxt.SHELL,
                'spheres_10': consts.string.inp.dxt.SHELL,
                'cutoff_1': None,
                'cutoff_2': consts.string.types.REAL,
                'weight': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'spheres_1': consts.string.inp.dxt.SHELL,
                'spheres_2': consts.string.inp.dxt.SHELL,
                'spheres_3': consts.string.inp.dxt.SHELL,
                'spheres_4': consts.string.inp.dxt.SHELL,
                'spheres_5': consts.string.inp.dxt.SHELL,
                'spheres_6': consts.string.inp.dxt.SHELL,
                'spheres_7': consts.string.inp.dxt.SHELL,
                'spheres_8': consts.string.inp.dxt.SHELL,
                'spheres_9': consts.string.inp.dxt.SHELL,
                'spheres_10': consts.string.inp.dxt.SHELL,
                'cutoff_1': consts.string.types.REAL,
                'cutoff_2': None,
                'weight': consts.string.types.REAL,
            },
            {
                'designator': consts.string.types.DESIGNATOR,
                'spheres_1': consts.string.inp.dxt.SHELL,
                'spheres_2': consts.string.inp.dxt.SHELL,
                'spheres_3': consts.string.inp.dxt.SHELL,
                'spheres_4': consts.string.inp.dxt.SHELL,
                'spheres_5': consts.string.inp.dxt.SHELL,
                'spheres_6': consts.string.inp.dxt.SHELL,
                'spheres_7': consts.string.inp.dxt.SHELL,
                'spheres_8': consts.string.inp.dxt.SHELL,
                'spheres_9': consts.string.inp.dxt.SHELL,
                'spheres_10': consts.string.inp.dxt.SHELL,
                'cutoff_1': consts.string.types.REAL,
                'cutoff_2': consts.string.types.REAL,
                'weight': None,
            },
        ]

    class Test_Mcnp(classes.Test_Mcnp):
        element = pymcnp.inp.Dxt
        EXAMPLES_VALID = [consts.string.inp.DXT]
        EXAMPLES_INVALID = ['hello']
