import pymcnp
from ... import consts
from ... import classes


class Test_Phys_2:
    class Test_Init(classes.Test_Init):
        element = pymcnp.inp.Phys_2
        EXAMPLES_VALID = [
            {
                'emax': consts.string.types.REAL,
                'ides': consts.string.types.INTEGER,
                'iphot': consts.string.types.INTEGER,
                'ibad': consts.string.types.INTEGER,
                'istrg': consts.string.types.INTEGER,
                'bnum': consts.string.types.REAL,
                'xnum': consts.string.types.REAL,
                'rnok': consts.string.types.INTEGER,
                'enum': consts.string.types.INTEGER,
                'numb': consts.string.types.INTEGER,
                'i_mcs_model': '-1',
                'j': 'j j',
                'efac': '0.8',
                'electron_method_boundary': consts.string.types.REAL,
                'ckvnum': '0.8',
            },
            {
                'emax': 3.1,
                'ides': 1,
                'iphot': 1,
                'ibad': 1,
                'istrg': 1,
                'bnum': 3.1,
                'xnum': 3.1,
                'rnok': 1,
                'enum': 1,
                'numb': 1,
                'i_mcs_model': -1,
                'j': pymcnp.types.String('j j'),
                'efac': 0.8,
                'electron_method_boundary': 3.1,
                'ckvnum': 0.8,
            },
            {
                'emax': consts.ast.types.REAL,
                'ides': consts.ast.types.INTEGER,
                'iphot': consts.ast.types.INTEGER,
                'ibad': consts.ast.types.INTEGER,
                'istrg': consts.ast.types.INTEGER,
                'bnum': consts.ast.types.REAL,
                'xnum': consts.ast.types.REAL,
                'rnok': consts.ast.types.INTEGER,
                'enum': consts.ast.types.INTEGER,
                'numb': consts.ast.types.INTEGER,
                'i_mcs_model': pymcnp.types.Integer(-1),
                'j': pymcnp.types.String('j j'),
                'efac': pymcnp.types.Real(0.8),
                'electron_method_boundary': consts.ast.types.REAL,
                'ckvnum': pymcnp.types.Real(0.8),
            },
            {
                'emax': None,
                'ides': consts.string.types.INTEGER,
                'iphot': consts.string.types.INTEGER,
                'ibad': consts.string.types.INTEGER,
                'istrg': consts.string.types.INTEGER,
                'bnum': consts.string.types.REAL,
                'xnum': consts.string.types.REAL,
                'rnok': consts.string.types.INTEGER,
                'enum': consts.string.types.INTEGER,
                'numb': consts.string.types.INTEGER,
                'i_mcs_model': '-1',
                'j': 'j j',
                'efac': '0.8',
                'electron_method_boundary': consts.string.types.REAL,
                'ckvnum': '0.8',
            },
            {
                'emax': consts.string.types.REAL,
                'ides': None,
                'iphot': consts.string.types.INTEGER,
                'ibad': consts.string.types.INTEGER,
                'istrg': consts.string.types.INTEGER,
                'bnum': consts.string.types.REAL,
                'xnum': consts.string.types.REAL,
                'rnok': consts.string.types.INTEGER,
                'enum': consts.string.types.INTEGER,
                'numb': consts.string.types.INTEGER,
                'i_mcs_model': '-1',
                'j': 'j j',
                'efac': '0.8',
                'electron_method_boundary': consts.string.types.REAL,
                'ckvnum': '0.8',
            },
            {
                'emax': consts.string.types.REAL,
                'ides': consts.string.types.INTEGER,
                'iphot': None,
                'ibad': consts.string.types.INTEGER,
                'istrg': consts.string.types.INTEGER,
                'bnum': consts.string.types.REAL,
                'xnum': consts.string.types.REAL,
                'rnok': consts.string.types.INTEGER,
                'enum': consts.string.types.INTEGER,
                'numb': consts.string.types.INTEGER,
                'i_mcs_model': '-1',
                'j': 'j j',
                'efac': '0.8',
                'electron_method_boundary': consts.string.types.REAL,
                'ckvnum': '0.8',
            },
            {
                'emax': consts.string.types.REAL,
                'ides': consts.string.types.INTEGER,
                'iphot': consts.string.types.INTEGER,
                'ibad': None,
                'istrg': consts.string.types.INTEGER,
                'bnum': consts.string.types.REAL,
                'xnum': consts.string.types.REAL,
                'rnok': consts.string.types.INTEGER,
                'enum': consts.string.types.INTEGER,
                'numb': consts.string.types.INTEGER,
                'i_mcs_model': '-1',
                'j': 'j j',
                'efac': '0.8',
                'electron_method_boundary': consts.string.types.REAL,
                'ckvnum': '0.8',
            },
            {
                'emax': consts.string.types.REAL,
                'ides': consts.string.types.INTEGER,
                'iphot': consts.string.types.INTEGER,
                'ibad': consts.string.types.INTEGER,
                'istrg': None,
                'bnum': consts.string.types.REAL,
                'xnum': consts.string.types.REAL,
                'rnok': consts.string.types.INTEGER,
                'enum': consts.string.types.INTEGER,
                'numb': consts.string.types.INTEGER,
                'i_mcs_model': '-1',
                'j': 'j j',
                'efac': '0.8',
                'electron_method_boundary': consts.string.types.REAL,
                'ckvnum': '0.8',
            },
            {
                'emax': consts.string.types.REAL,
                'ides': consts.string.types.INTEGER,
                'iphot': consts.string.types.INTEGER,
                'ibad': consts.string.types.INTEGER,
                'istrg': consts.string.types.INTEGER,
                'bnum': None,
                'xnum': consts.string.types.REAL,
                'rnok': consts.string.types.INTEGER,
                'enum': consts.string.types.INTEGER,
                'numb': consts.string.types.INTEGER,
                'i_mcs_model': '-1',
                'j': 'j j',
                'efac': '0.8',
                'electron_method_boundary': consts.string.types.REAL,
                'ckvnum': '0.8',
            },
            {
                'emax': consts.string.types.REAL,
                'ides': consts.string.types.INTEGER,
                'iphot': consts.string.types.INTEGER,
                'ibad': consts.string.types.INTEGER,
                'istrg': consts.string.types.INTEGER,
                'bnum': consts.string.types.REAL,
                'xnum': None,
                'rnok': consts.string.types.INTEGER,
                'enum': consts.string.types.INTEGER,
                'numb': consts.string.types.INTEGER,
                'i_mcs_model': '-1',
                'j': 'j j',
                'efac': '0.8',
                'electron_method_boundary': consts.string.types.REAL,
                'ckvnum': '0.8',
            },
            {
                'emax': consts.string.types.REAL,
                'ides': consts.string.types.INTEGER,
                'iphot': consts.string.types.INTEGER,
                'ibad': consts.string.types.INTEGER,
                'istrg': consts.string.types.INTEGER,
                'bnum': consts.string.types.REAL,
                'xnum': consts.string.types.REAL,
                'rnok': None,
                'enum': consts.string.types.INTEGER,
                'numb': consts.string.types.INTEGER,
                'i_mcs_model': '-1',
                'j': 'j j',
                'efac': '0.8',
                'electron_method_boundary': consts.string.types.REAL,
                'ckvnum': '0.8',
            },
            {
                'emax': consts.string.types.REAL,
                'ides': consts.string.types.INTEGER,
                'iphot': consts.string.types.INTEGER,
                'ibad': consts.string.types.INTEGER,
                'istrg': consts.string.types.INTEGER,
                'bnum': consts.string.types.REAL,
                'xnum': consts.string.types.REAL,
                'rnok': consts.string.types.INTEGER,
                'enum': None,
                'numb': consts.string.types.INTEGER,
                'i_mcs_model': '-1',
                'j': 'j j',
                'efac': '0.8',
                'electron_method_boundary': consts.string.types.REAL,
                'ckvnum': '0.8',
            },
            {
                'emax': consts.string.types.REAL,
                'ides': consts.string.types.INTEGER,
                'iphot': consts.string.types.INTEGER,
                'ibad': consts.string.types.INTEGER,
                'istrg': consts.string.types.INTEGER,
                'bnum': consts.string.types.REAL,
                'xnum': consts.string.types.REAL,
                'rnok': consts.string.types.INTEGER,
                'enum': consts.string.types.INTEGER,
                'numb': None,
                'i_mcs_model': '-1',
                'j': 'j j',
                'efac': '0.8',
                'electron_method_boundary': consts.string.types.REAL,
                'ckvnum': '0.8',
            },
            {
                'emax': consts.string.types.REAL,
                'ides': consts.string.types.INTEGER,
                'iphot': consts.string.types.INTEGER,
                'ibad': consts.string.types.INTEGER,
                'istrg': consts.string.types.INTEGER,
                'bnum': consts.string.types.REAL,
                'xnum': consts.string.types.REAL,
                'rnok': consts.string.types.INTEGER,
                'enum': consts.string.types.INTEGER,
                'numb': consts.string.types.INTEGER,
                'i_mcs_model': None,
                'j': 'j j',
                'efac': '0.8',
                'electron_method_boundary': consts.string.types.REAL,
                'ckvnum': '0.8',
            },
            {
                'emax': consts.string.types.REAL,
                'ides': consts.string.types.INTEGER,
                'iphot': consts.string.types.INTEGER,
                'ibad': consts.string.types.INTEGER,
                'istrg': consts.string.types.INTEGER,
                'bnum': consts.string.types.REAL,
                'xnum': consts.string.types.REAL,
                'rnok': consts.string.types.INTEGER,
                'enum': consts.string.types.INTEGER,
                'numb': consts.string.types.INTEGER,
                'i_mcs_model': '-1',
                'j': None,
                'efac': '0.8',
                'electron_method_boundary': consts.string.types.REAL,
                'ckvnum': '0.8',
            },
            {
                'emax': consts.string.types.REAL,
                'ides': consts.string.types.INTEGER,
                'iphot': consts.string.types.INTEGER,
                'ibad': consts.string.types.INTEGER,
                'istrg': consts.string.types.INTEGER,
                'bnum': consts.string.types.REAL,
                'xnum': consts.string.types.REAL,
                'rnok': consts.string.types.INTEGER,
                'enum': consts.string.types.INTEGER,
                'numb': consts.string.types.INTEGER,
                'i_mcs_model': '-1',
                'j': 'j j',
                'efac': None,
                'electron_method_boundary': consts.string.types.REAL,
                'ckvnum': '0.8',
            },
            {
                'emax': consts.string.types.REAL,
                'ides': consts.string.types.INTEGER,
                'iphot': consts.string.types.INTEGER,
                'ibad': consts.string.types.INTEGER,
                'istrg': consts.string.types.INTEGER,
                'bnum': consts.string.types.REAL,
                'xnum': consts.string.types.REAL,
                'rnok': consts.string.types.INTEGER,
                'enum': consts.string.types.INTEGER,
                'numb': consts.string.types.INTEGER,
                'i_mcs_model': '-1',
                'j': 'j j',
                'efac': '0.8',
                'electron_method_boundary': None,
                'ckvnum': '0.8',
            },
            {
                'emax': consts.string.types.REAL,
                'ides': consts.string.types.INTEGER,
                'iphot': consts.string.types.INTEGER,
                'ibad': consts.string.types.INTEGER,
                'istrg': consts.string.types.INTEGER,
                'bnum': consts.string.types.REAL,
                'xnum': consts.string.types.REAL,
                'rnok': consts.string.types.INTEGER,
                'enum': consts.string.types.INTEGER,
                'numb': consts.string.types.INTEGER,
                'i_mcs_model': '-1',
                'j': 'j j',
                'efac': '0.8',
                'electron_method_boundary': consts.string.types.REAL,
                'ckvnum': None,
            },
        ]
        EXAMPLES_INVALID = [
            {
                'emax': consts.string.types.REAL,
                'ides': -9999,
                'iphot': consts.string.types.INTEGER,
                'ibad': consts.string.types.INTEGER,
                'istrg': consts.string.types.INTEGER,
                'bnum': consts.string.types.REAL,
                'xnum': consts.string.types.REAL,
                'rnok': consts.string.types.INTEGER,
                'enum': consts.string.types.INTEGER,
                'numb': consts.string.types.INTEGER,
                'i_mcs_model': '-1',
                'j': 'j j',
                'efac': '0.8',
                'electron_method_boundary': consts.string.types.REAL,
                'ckvnum': '0.8',
            },
            {
                'emax': consts.string.types.REAL,
                'ides': consts.string.types.INTEGER,
                'iphot': -9999,
                'ibad': consts.string.types.INTEGER,
                'istrg': consts.string.types.INTEGER,
                'bnum': consts.string.types.REAL,
                'xnum': consts.string.types.REAL,
                'rnok': consts.string.types.INTEGER,
                'enum': consts.string.types.INTEGER,
                'numb': consts.string.types.INTEGER,
                'i_mcs_model': '-1',
                'j': 'j j',
                'efac': '0.8',
                'electron_method_boundary': consts.string.types.REAL,
                'ckvnum': '0.8',
            },
            {
                'emax': consts.string.types.REAL,
                'ides': consts.string.types.INTEGER,
                'iphot': consts.string.types.INTEGER,
                'ibad': -9999,
                'istrg': consts.string.types.INTEGER,
                'bnum': consts.string.types.REAL,
                'xnum': consts.string.types.REAL,
                'rnok': consts.string.types.INTEGER,
                'enum': consts.string.types.INTEGER,
                'numb': consts.string.types.INTEGER,
                'i_mcs_model': '-1',
                'j': 'j j',
                'efac': '0.8',
                'electron_method_boundary': consts.string.types.REAL,
                'ckvnum': '0.8',
            },
            {
                'emax': consts.string.types.REAL,
                'ides': consts.string.types.INTEGER,
                'iphot': consts.string.types.INTEGER,
                'ibad': consts.string.types.INTEGER,
                'istrg': -9999,
                'bnum': consts.string.types.REAL,
                'xnum': consts.string.types.REAL,
                'rnok': consts.string.types.INTEGER,
                'enum': consts.string.types.INTEGER,
                'numb': consts.string.types.INTEGER,
                'i_mcs_model': '-1',
                'j': 'j j',
                'efac': '0.8',
                'electron_method_boundary': consts.string.types.REAL,
                'ckvnum': '0.8',
            },
            {
                'emax': consts.string.types.REAL,
                'ides': consts.string.types.INTEGER,
                'iphot': consts.string.types.INTEGER,
                'ibad': consts.string.types.INTEGER,
                'istrg': consts.string.types.INTEGER,
                'bnum': consts.string.types.REAL,
                'xnum': -3.1,
                'rnok': consts.string.types.INTEGER,
                'enum': consts.string.types.INTEGER,
                'numb': consts.string.types.INTEGER,
                'i_mcs_model': '-1',
                'j': 'j j',
                'efac': '0.8',
                'electron_method_boundary': consts.string.types.REAL,
                'ckvnum': '0.8',
            },
            {
                'emax': consts.string.types.REAL,
                'ides': consts.string.types.INTEGER,
                'iphot': consts.string.types.INTEGER,
                'ibad': consts.string.types.INTEGER,
                'istrg': consts.string.types.INTEGER,
                'bnum': consts.string.types.REAL,
                'xnum': consts.string.types.REAL,
                'rnok': -9999,
                'enum': consts.string.types.INTEGER,
                'numb': consts.string.types.INTEGER,
                'i_mcs_model': '-1',
                'j': 'j j',
                'efac': '0.8',
                'electron_method_boundary': consts.string.types.REAL,
                'ckvnum': '0.8',
            },
            {
                'emax': consts.string.types.REAL,
                'ides': consts.string.types.INTEGER,
                'iphot': consts.string.types.INTEGER,
                'ibad': consts.string.types.INTEGER,
                'istrg': consts.string.types.INTEGER,
                'bnum': consts.string.types.REAL,
                'xnum': consts.string.types.REAL,
                'rnok': consts.string.types.INTEGER,
                'enum': -9999,
                'numb': consts.string.types.INTEGER,
                'i_mcs_model': '-1',
                'j': 'j j',
                'efac': '0.8',
                'electron_method_boundary': consts.string.types.REAL,
                'ckvnum': '0.8',
            },
            {
                'emax': consts.string.types.REAL,
                'ides': consts.string.types.INTEGER,
                'iphot': consts.string.types.INTEGER,
                'ibad': consts.string.types.INTEGER,
                'istrg': consts.string.types.INTEGER,
                'bnum': consts.string.types.REAL,
                'xnum': consts.string.types.REAL,
                'rnok': consts.string.types.INTEGER,
                'enum': consts.string.types.INTEGER,
                'numb': -9999,
                'i_mcs_model': '-1',
                'j': 'j j',
                'efac': '0.8',
                'electron_method_boundary': consts.string.types.REAL,
                'ckvnum': '0.8',
            },
            {
                'emax': consts.string.types.REAL,
                'ides': consts.string.types.INTEGER,
                'iphot': consts.string.types.INTEGER,
                'ibad': consts.string.types.INTEGER,
                'istrg': consts.string.types.INTEGER,
                'bnum': consts.string.types.REAL,
                'xnum': consts.string.types.REAL,
                'rnok': consts.string.types.INTEGER,
                'enum': consts.string.types.INTEGER,
                'numb': consts.string.types.INTEGER,
                'i_mcs_model': '1',
                'j': 'j j',
                'efac': '0.8',
                'electron_method_boundary': consts.string.types.REAL,
                'ckvnum': '0.8',
            },
            {
                'emax': consts.string.types.REAL,
                'ides': consts.string.types.INTEGER,
                'iphot': consts.string.types.INTEGER,
                'ibad': consts.string.types.INTEGER,
                'istrg': consts.string.types.INTEGER,
                'bnum': consts.string.types.REAL,
                'xnum': consts.string.types.REAL,
                'rnok': consts.string.types.INTEGER,
                'enum': consts.string.types.INTEGER,
                'numb': consts.string.types.INTEGER,
                'i_mcs_model': '-1',
                'j': 'none',
                'efac': '0.8',
                'electron_method_boundary': consts.string.types.REAL,
                'ckvnum': '0.8',
            },
            {
                'emax': consts.string.types.REAL,
                'ides': consts.string.types.INTEGER,
                'iphot': consts.string.types.INTEGER,
                'ibad': consts.string.types.INTEGER,
                'istrg': consts.string.types.INTEGER,
                'bnum': consts.string.types.REAL,
                'xnum': consts.string.types.REAL,
                'rnok': consts.string.types.INTEGER,
                'enum': consts.string.types.INTEGER,
                'numb': consts.string.types.INTEGER,
                'i_mcs_model': '-1',
                'j': 'j j',
                'efac': '3.1',
                'electron_method_boundary': consts.string.types.REAL,
                'ckvnum': '0.8',
            },
            {
                'emax': consts.string.types.REAL,
                'ides': consts.string.types.INTEGER,
                'iphot': consts.string.types.INTEGER,
                'ibad': consts.string.types.INTEGER,
                'istrg': consts.string.types.INTEGER,
                'bnum': consts.string.types.REAL,
                'xnum': consts.string.types.REAL,
                'rnok': consts.string.types.INTEGER,
                'enum': consts.string.types.INTEGER,
                'numb': consts.string.types.INTEGER,
                'i_mcs_model': '-1',
                'j': 'j j',
                'efac': '0.8',
                'electron_method_boundary': consts.string.types.REAL,
                'ckvnum': '3.1',
            },
        ]

    class Test_Mcnp(classes.Test_Mcnp):
        element = pymcnp.inp.Phys_2
        EXAMPLES_VALID = [consts.string.inp.PHYS_2]
        EXAMPLES_INVALID = ['hello']
