import pymcnp
from .... import consts
from .... import classes


class Test_N:
    class Test_Init(classes.Test_Init):
        element = pymcnp.ptrac.header.N
        EXAMPLES_VALID = [
            {
                'n1': consts.ast.types.INTEGER,
                'n2': consts.ast.types.INTEGER,
                'n3': consts.ast.types.INTEGER,
                'n4': consts.ast.types.INTEGER,
                'n5': consts.ast.types.INTEGER,
                'n6': consts.ast.types.INTEGER,
                'n7': consts.ast.types.INTEGER,
                'n8': consts.ast.types.INTEGER,
                'n9': consts.ast.types.INTEGER,
                'n10': consts.ast.types.INTEGER,
                'n11': consts.ast.types.INTEGER,
                'n12': consts.ast.types.INTEGER,
                'n13': consts.ast.types.INTEGER,
                'n14': consts.ast.types.INTEGER,
                'n15': consts.ast.types.INTEGER,
                'n16': consts.ast.types.INTEGER,
                'n17': consts.ast.types.INTEGER,
                'n18': consts.ast.types.INTEGER,
                'n19': consts.ast.types.INTEGER,
                'n20': consts.ast.types.INTEGER,
            }
        ]
        EXAMPLES_INVALID = [
            {
                'n1': None,
                'n2': consts.ast.types.INTEGER,
                'n3': consts.ast.types.INTEGER,
                'n4': consts.ast.types.INTEGER,
                'n5': consts.ast.types.INTEGER,
                'n6': consts.ast.types.INTEGER,
                'n7': consts.ast.types.INTEGER,
                'n8': consts.ast.types.INTEGER,
                'n9': consts.ast.types.INTEGER,
                'n10': consts.ast.types.INTEGER,
                'n11': consts.ast.types.INTEGER,
                'n12': consts.ast.types.INTEGER,
                'n13': consts.ast.types.INTEGER,
                'n14': consts.ast.types.INTEGER,
                'n15': consts.ast.types.INTEGER,
                'n16': consts.ast.types.INTEGER,
                'n17': consts.ast.types.INTEGER,
                'n18': consts.ast.types.INTEGER,
                'n19': consts.ast.types.INTEGER,
                'n20': consts.ast.types.INTEGER,
            },
            {
                'n1': consts.ast.types.INTEGER,
                'n2': None,
                'n3': consts.ast.types.INTEGER,
                'n4': consts.ast.types.INTEGER,
                'n5': consts.ast.types.INTEGER,
                'n6': consts.ast.types.INTEGER,
                'n7': consts.ast.types.INTEGER,
                'n8': consts.ast.types.INTEGER,
                'n9': consts.ast.types.INTEGER,
                'n10': consts.ast.types.INTEGER,
                'n11': consts.ast.types.INTEGER,
                'n12': consts.ast.types.INTEGER,
                'n13': consts.ast.types.INTEGER,
                'n14': consts.ast.types.INTEGER,
                'n15': consts.ast.types.INTEGER,
                'n16': consts.ast.types.INTEGER,
                'n17': consts.ast.types.INTEGER,
                'n18': consts.ast.types.INTEGER,
                'n19': consts.ast.types.INTEGER,
                'n20': consts.ast.types.INTEGER,
            },
            {
                'n1': consts.ast.types.INTEGER,
                'n2': consts.ast.types.INTEGER,
                'n3': None,
                'n4': consts.ast.types.INTEGER,
                'n5': consts.ast.types.INTEGER,
                'n6': consts.ast.types.INTEGER,
                'n7': consts.ast.types.INTEGER,
                'n8': consts.ast.types.INTEGER,
                'n9': consts.ast.types.INTEGER,
                'n10': consts.ast.types.INTEGER,
                'n11': consts.ast.types.INTEGER,
                'n12': consts.ast.types.INTEGER,
                'n13': consts.ast.types.INTEGER,
                'n14': consts.ast.types.INTEGER,
                'n15': consts.ast.types.INTEGER,
                'n16': consts.ast.types.INTEGER,
                'n17': consts.ast.types.INTEGER,
                'n18': consts.ast.types.INTEGER,
                'n19': consts.ast.types.INTEGER,
                'n20': consts.ast.types.INTEGER,
            },
            {
                'n1': consts.ast.types.INTEGER,
                'n2': consts.ast.types.INTEGER,
                'n3': consts.ast.types.INTEGER,
                'n4': None,
                'n5': consts.ast.types.INTEGER,
                'n6': consts.ast.types.INTEGER,
                'n7': consts.ast.types.INTEGER,
                'n8': consts.ast.types.INTEGER,
                'n9': consts.ast.types.INTEGER,
                'n10': consts.ast.types.INTEGER,
                'n11': consts.ast.types.INTEGER,
                'n12': consts.ast.types.INTEGER,
                'n13': consts.ast.types.INTEGER,
                'n14': consts.ast.types.INTEGER,
                'n15': consts.ast.types.INTEGER,
                'n16': consts.ast.types.INTEGER,
                'n17': consts.ast.types.INTEGER,
                'n18': consts.ast.types.INTEGER,
                'n19': consts.ast.types.INTEGER,
                'n20': consts.ast.types.INTEGER,
            },
            {
                'n1': consts.ast.types.INTEGER,
                'n2': consts.ast.types.INTEGER,
                'n3': consts.ast.types.INTEGER,
                'n4': consts.ast.types.INTEGER,
                'n5': None,
                'n6': consts.ast.types.INTEGER,
                'n7': consts.ast.types.INTEGER,
                'n8': consts.ast.types.INTEGER,
                'n9': consts.ast.types.INTEGER,
                'n10': consts.ast.types.INTEGER,
                'n11': consts.ast.types.INTEGER,
                'n12': consts.ast.types.INTEGER,
                'n13': consts.ast.types.INTEGER,
                'n14': consts.ast.types.INTEGER,
                'n15': consts.ast.types.INTEGER,
                'n16': consts.ast.types.INTEGER,
                'n17': consts.ast.types.INTEGER,
                'n18': consts.ast.types.INTEGER,
                'n19': consts.ast.types.INTEGER,
                'n20': consts.ast.types.INTEGER,
            },
            {
                'n1': consts.ast.types.INTEGER,
                'n2': consts.ast.types.INTEGER,
                'n3': consts.ast.types.INTEGER,
                'n4': consts.ast.types.INTEGER,
                'n5': consts.ast.types.INTEGER,
                'n6': None,
                'n7': consts.ast.types.INTEGER,
                'n8': consts.ast.types.INTEGER,
                'n9': consts.ast.types.INTEGER,
                'n10': consts.ast.types.INTEGER,
                'n11': consts.ast.types.INTEGER,
                'n12': consts.ast.types.INTEGER,
                'n13': consts.ast.types.INTEGER,
                'n14': consts.ast.types.INTEGER,
                'n15': consts.ast.types.INTEGER,
                'n16': consts.ast.types.INTEGER,
                'n17': consts.ast.types.INTEGER,
                'n18': consts.ast.types.INTEGER,
                'n19': consts.ast.types.INTEGER,
                'n20': consts.ast.types.INTEGER,
            },
            {
                'n1': consts.ast.types.INTEGER,
                'n2': consts.ast.types.INTEGER,
                'n3': consts.ast.types.INTEGER,
                'n4': consts.ast.types.INTEGER,
                'n5': consts.ast.types.INTEGER,
                'n6': consts.ast.types.INTEGER,
                'n7': None,
                'n8': consts.ast.types.INTEGER,
                'n9': consts.ast.types.INTEGER,
                'n10': consts.ast.types.INTEGER,
                'n11': consts.ast.types.INTEGER,
                'n12': consts.ast.types.INTEGER,
                'n13': consts.ast.types.INTEGER,
                'n14': consts.ast.types.INTEGER,
                'n15': consts.ast.types.INTEGER,
                'n16': consts.ast.types.INTEGER,
                'n17': consts.ast.types.INTEGER,
                'n18': consts.ast.types.INTEGER,
                'n19': consts.ast.types.INTEGER,
                'n20': consts.ast.types.INTEGER,
            },
            {
                'n1': consts.ast.types.INTEGER,
                'n2': consts.ast.types.INTEGER,
                'n3': consts.ast.types.INTEGER,
                'n4': consts.ast.types.INTEGER,
                'n5': consts.ast.types.INTEGER,
                'n6': consts.ast.types.INTEGER,
                'n7': consts.ast.types.INTEGER,
                'n8': None,
                'n9': consts.ast.types.INTEGER,
                'n10': consts.ast.types.INTEGER,
                'n11': consts.ast.types.INTEGER,
                'n12': consts.ast.types.INTEGER,
                'n13': consts.ast.types.INTEGER,
                'n14': consts.ast.types.INTEGER,
                'n15': consts.ast.types.INTEGER,
                'n16': consts.ast.types.INTEGER,
                'n17': consts.ast.types.INTEGER,
                'n18': consts.ast.types.INTEGER,
                'n19': consts.ast.types.INTEGER,
                'n20': consts.ast.types.INTEGER,
            },
            {
                'n1': consts.ast.types.INTEGER,
                'n2': consts.ast.types.INTEGER,
                'n3': consts.ast.types.INTEGER,
                'n4': consts.ast.types.INTEGER,
                'n5': consts.ast.types.INTEGER,
                'n6': consts.ast.types.INTEGER,
                'n7': consts.ast.types.INTEGER,
                'n8': consts.ast.types.INTEGER,
                'n9': None,
                'n10': consts.ast.types.INTEGER,
                'n11': consts.ast.types.INTEGER,
                'n12': consts.ast.types.INTEGER,
                'n13': consts.ast.types.INTEGER,
                'n14': consts.ast.types.INTEGER,
                'n15': consts.ast.types.INTEGER,
                'n16': consts.ast.types.INTEGER,
                'n17': consts.ast.types.INTEGER,
                'n18': consts.ast.types.INTEGER,
                'n19': consts.ast.types.INTEGER,
                'n20': consts.ast.types.INTEGER,
            },
            {
                'n1': consts.ast.types.INTEGER,
                'n2': consts.ast.types.INTEGER,
                'n3': consts.ast.types.INTEGER,
                'n4': consts.ast.types.INTEGER,
                'n5': consts.ast.types.INTEGER,
                'n6': consts.ast.types.INTEGER,
                'n7': consts.ast.types.INTEGER,
                'n8': consts.ast.types.INTEGER,
                'n9': consts.ast.types.INTEGER,
                'n10': None,
                'n11': consts.ast.types.INTEGER,
                'n12': consts.ast.types.INTEGER,
                'n13': consts.ast.types.INTEGER,
                'n14': consts.ast.types.INTEGER,
                'n15': consts.ast.types.INTEGER,
                'n16': consts.ast.types.INTEGER,
                'n17': consts.ast.types.INTEGER,
                'n18': consts.ast.types.INTEGER,
                'n19': consts.ast.types.INTEGER,
                'n20': consts.ast.types.INTEGER,
            },
            {
                'n1': consts.ast.types.INTEGER,
                'n2': consts.ast.types.INTEGER,
                'n3': consts.ast.types.INTEGER,
                'n4': consts.ast.types.INTEGER,
                'n5': consts.ast.types.INTEGER,
                'n6': consts.ast.types.INTEGER,
                'n7': consts.ast.types.INTEGER,
                'n8': consts.ast.types.INTEGER,
                'n9': consts.ast.types.INTEGER,
                'n10': consts.ast.types.INTEGER,
                'n11': None,
                'n12': consts.ast.types.INTEGER,
                'n13': consts.ast.types.INTEGER,
                'n14': consts.ast.types.INTEGER,
                'n15': consts.ast.types.INTEGER,
                'n16': consts.ast.types.INTEGER,
                'n17': consts.ast.types.INTEGER,
                'n18': consts.ast.types.INTEGER,
                'n19': consts.ast.types.INTEGER,
                'n20': consts.ast.types.INTEGER,
            },
            {
                'n1': consts.ast.types.INTEGER,
                'n2': consts.ast.types.INTEGER,
                'n3': consts.ast.types.INTEGER,
                'n4': consts.ast.types.INTEGER,
                'n5': consts.ast.types.INTEGER,
                'n6': consts.ast.types.INTEGER,
                'n7': consts.ast.types.INTEGER,
                'n8': consts.ast.types.INTEGER,
                'n9': consts.ast.types.INTEGER,
                'n10': consts.ast.types.INTEGER,
                'n11': consts.ast.types.INTEGER,
                'n12': None,
                'n13': consts.ast.types.INTEGER,
                'n14': consts.ast.types.INTEGER,
                'n15': consts.ast.types.INTEGER,
                'n16': consts.ast.types.INTEGER,
                'n17': consts.ast.types.INTEGER,
                'n18': consts.ast.types.INTEGER,
                'n19': consts.ast.types.INTEGER,
                'n20': consts.ast.types.INTEGER,
            },
            {
                'n1': consts.ast.types.INTEGER,
                'n2': consts.ast.types.INTEGER,
                'n3': consts.ast.types.INTEGER,
                'n4': consts.ast.types.INTEGER,
                'n5': consts.ast.types.INTEGER,
                'n6': consts.ast.types.INTEGER,
                'n7': consts.ast.types.INTEGER,
                'n8': consts.ast.types.INTEGER,
                'n9': consts.ast.types.INTEGER,
                'n10': consts.ast.types.INTEGER,
                'n11': consts.ast.types.INTEGER,
                'n12': consts.ast.types.INTEGER,
                'n13': None,
                'n14': consts.ast.types.INTEGER,
                'n15': consts.ast.types.INTEGER,
                'n16': consts.ast.types.INTEGER,
                'n17': consts.ast.types.INTEGER,
                'n18': consts.ast.types.INTEGER,
                'n19': consts.ast.types.INTEGER,
                'n20': consts.ast.types.INTEGER,
            },
            {
                'n1': consts.ast.types.INTEGER,
                'n2': consts.ast.types.INTEGER,
                'n3': consts.ast.types.INTEGER,
                'n4': consts.ast.types.INTEGER,
                'n5': consts.ast.types.INTEGER,
                'n6': consts.ast.types.INTEGER,
                'n7': consts.ast.types.INTEGER,
                'n8': consts.ast.types.INTEGER,
                'n9': consts.ast.types.INTEGER,
                'n10': consts.ast.types.INTEGER,
                'n11': consts.ast.types.INTEGER,
                'n12': consts.ast.types.INTEGER,
                'n13': consts.ast.types.INTEGER,
                'n14': None,
                'n15': consts.ast.types.INTEGER,
                'n16': consts.ast.types.INTEGER,
                'n17': consts.ast.types.INTEGER,
                'n18': consts.ast.types.INTEGER,
                'n19': consts.ast.types.INTEGER,
                'n20': consts.ast.types.INTEGER,
            },
            {
                'n1': consts.ast.types.INTEGER,
                'n2': consts.ast.types.INTEGER,
                'n3': consts.ast.types.INTEGER,
                'n4': consts.ast.types.INTEGER,
                'n5': consts.ast.types.INTEGER,
                'n6': consts.ast.types.INTEGER,
                'n7': consts.ast.types.INTEGER,
                'n8': consts.ast.types.INTEGER,
                'n9': consts.ast.types.INTEGER,
                'n10': consts.ast.types.INTEGER,
                'n11': consts.ast.types.INTEGER,
                'n12': consts.ast.types.INTEGER,
                'n13': consts.ast.types.INTEGER,
                'n14': consts.ast.types.INTEGER,
                'n15': None,
                'n16': consts.ast.types.INTEGER,
                'n17': consts.ast.types.INTEGER,
                'n18': consts.ast.types.INTEGER,
                'n19': consts.ast.types.INTEGER,
                'n20': consts.ast.types.INTEGER,
            },
            {
                'n1': consts.ast.types.INTEGER,
                'n2': consts.ast.types.INTEGER,
                'n3': consts.ast.types.INTEGER,
                'n4': consts.ast.types.INTEGER,
                'n5': consts.ast.types.INTEGER,
                'n6': consts.ast.types.INTEGER,
                'n7': consts.ast.types.INTEGER,
                'n8': consts.ast.types.INTEGER,
                'n9': consts.ast.types.INTEGER,
                'n10': consts.ast.types.INTEGER,
                'n11': consts.ast.types.INTEGER,
                'n12': consts.ast.types.INTEGER,
                'n13': consts.ast.types.INTEGER,
                'n14': consts.ast.types.INTEGER,
                'n15': consts.ast.types.INTEGER,
                'n16': None,
                'n17': consts.ast.types.INTEGER,
                'n18': consts.ast.types.INTEGER,
                'n19': consts.ast.types.INTEGER,
                'n20': consts.ast.types.INTEGER,
            },
            {
                'n1': consts.ast.types.INTEGER,
                'n2': consts.ast.types.INTEGER,
                'n3': consts.ast.types.INTEGER,
                'n4': consts.ast.types.INTEGER,
                'n5': consts.ast.types.INTEGER,
                'n6': consts.ast.types.INTEGER,
                'n7': consts.ast.types.INTEGER,
                'n8': consts.ast.types.INTEGER,
                'n9': consts.ast.types.INTEGER,
                'n10': consts.ast.types.INTEGER,
                'n11': consts.ast.types.INTEGER,
                'n12': consts.ast.types.INTEGER,
                'n13': consts.ast.types.INTEGER,
                'n14': consts.ast.types.INTEGER,
                'n15': consts.ast.types.INTEGER,
                'n16': consts.ast.types.INTEGER,
                'n17': None,
                'n18': consts.ast.types.INTEGER,
                'n19': consts.ast.types.INTEGER,
                'n20': consts.ast.types.INTEGER,
            },
            {
                'n1': consts.ast.types.INTEGER,
                'n2': consts.ast.types.INTEGER,
                'n3': consts.ast.types.INTEGER,
                'n4': consts.ast.types.INTEGER,
                'n5': consts.ast.types.INTEGER,
                'n6': consts.ast.types.INTEGER,
                'n7': consts.ast.types.INTEGER,
                'n8': consts.ast.types.INTEGER,
                'n9': consts.ast.types.INTEGER,
                'n10': consts.ast.types.INTEGER,
                'n11': consts.ast.types.INTEGER,
                'n12': consts.ast.types.INTEGER,
                'n13': consts.ast.types.INTEGER,
                'n14': consts.ast.types.INTEGER,
                'n15': consts.ast.types.INTEGER,
                'n16': consts.ast.types.INTEGER,
                'n17': consts.ast.types.INTEGER,
                'n18': None,
                'n19': consts.ast.types.INTEGER,
                'n20': consts.ast.types.INTEGER,
            },
            {
                'n1': consts.ast.types.INTEGER,
                'n2': consts.ast.types.INTEGER,
                'n3': consts.ast.types.INTEGER,
                'n4': consts.ast.types.INTEGER,
                'n5': consts.ast.types.INTEGER,
                'n6': consts.ast.types.INTEGER,
                'n7': consts.ast.types.INTEGER,
                'n8': consts.ast.types.INTEGER,
                'n9': consts.ast.types.INTEGER,
                'n10': consts.ast.types.INTEGER,
                'n11': consts.ast.types.INTEGER,
                'n12': consts.ast.types.INTEGER,
                'n13': consts.ast.types.INTEGER,
                'n14': consts.ast.types.INTEGER,
                'n15': consts.ast.types.INTEGER,
                'n16': consts.ast.types.INTEGER,
                'n17': consts.ast.types.INTEGER,
                'n18': consts.ast.types.INTEGER,
                'n19': None,
                'n20': consts.ast.types.INTEGER,
            },
            {
                'n1': consts.ast.types.INTEGER,
                'n2': consts.ast.types.INTEGER,
                'n3': consts.ast.types.INTEGER,
                'n4': consts.ast.types.INTEGER,
                'n5': consts.ast.types.INTEGER,
                'n6': consts.ast.types.INTEGER,
                'n7': consts.ast.types.INTEGER,
                'n8': consts.ast.types.INTEGER,
                'n9': consts.ast.types.INTEGER,
                'n10': consts.ast.types.INTEGER,
                'n11': consts.ast.types.INTEGER,
                'n12': consts.ast.types.INTEGER,
                'n13': consts.ast.types.INTEGER,
                'n14': consts.ast.types.INTEGER,
                'n15': consts.ast.types.INTEGER,
                'n16': consts.ast.types.INTEGER,
                'n17': consts.ast.types.INTEGER,
                'n18': consts.ast.types.INTEGER,
                'n19': consts.ast.types.INTEGER,
                'n20': None,
            },
        ]

    class Test_Mcnp(classes.Test_Mcnp):
        element = pymcnp.ptrac.header.N
        EXAMPLES_VALID = [consts.string.ptrac.header.N]
        EXAMPLES_INVALID = ['hello']
