import pymcnp
from ... import consts
from ... import classes


class Test_Transformation_0:
    class Test_Init(classes.Test_Init):
        element = pymcnp.types.Transformation_0
        EXAMPLES_VALID = [
            {
                'o1': consts.ast.types.REAL,
                'o2': consts.ast.types.REAL,
                'o3': consts.ast.types.REAL,
                'xx': consts.ast.types.REAL,
                'xy': consts.ast.types.REAL,
                'xz': consts.ast.types.REAL,
                'yx': consts.ast.types.REAL,
                'yy': consts.ast.types.REAL,
                'yz': consts.ast.types.REAL,
                'zx': consts.ast.types.REAL,
                'zy': consts.ast.types.REAL,
                'zz': consts.ast.types.REAL,
                'm': consts.ast.types.INTEGER,
            },
            {
                'o1': consts.ast.types.REAL,
                'o2': consts.ast.types.REAL,
                'o3': consts.ast.types.REAL,
                'xx': consts.ast.types.REAL,
                'xy': consts.ast.types.REAL,
                'xz': consts.ast.types.REAL,
                'yx': consts.ast.types.REAL,
                'yy': consts.ast.types.REAL,
                'yz': consts.ast.types.REAL,
                'zx': consts.ast.types.REAL,
                'zy': consts.ast.types.REAL,
                'zz': consts.ast.types.REAL,
                'm': None,
            },
        ]
        EXAMPLES_INVALID = [
            {
                'o1': None,
                'o2': consts.ast.types.REAL,
                'o3': consts.ast.types.REAL,
                'xx': consts.ast.types.REAL,
                'xy': consts.ast.types.REAL,
                'xz': consts.ast.types.REAL,
                'yx': consts.ast.types.REAL,
                'yy': consts.ast.types.REAL,
                'yz': consts.ast.types.REAL,
                'zx': consts.ast.types.REAL,
                'zy': consts.ast.types.REAL,
                'zz': consts.ast.types.REAL,
                'm': consts.ast.types.INTEGER,
            },
            {
                'o1': consts.ast.types.REAL,
                'o2': None,
                'o3': consts.ast.types.REAL,
                'xx': consts.ast.types.REAL,
                'xy': consts.ast.types.REAL,
                'xz': consts.ast.types.REAL,
                'yx': consts.ast.types.REAL,
                'yy': consts.ast.types.REAL,
                'yz': consts.ast.types.REAL,
                'zx': consts.ast.types.REAL,
                'zy': consts.ast.types.REAL,
                'zz': consts.ast.types.REAL,
                'm': consts.ast.types.INTEGER,
            },
            {
                'o1': consts.ast.types.REAL,
                'o2': consts.ast.types.REAL,
                'o3': None,
                'xx': consts.ast.types.REAL,
                'xy': consts.ast.types.REAL,
                'xz': consts.ast.types.REAL,
                'yx': consts.ast.types.REAL,
                'yy': consts.ast.types.REAL,
                'yz': consts.ast.types.REAL,
                'zx': consts.ast.types.REAL,
                'zy': consts.ast.types.REAL,
                'zz': consts.ast.types.REAL,
                'm': consts.ast.types.INTEGER,
            },
            {
                'o1': consts.ast.types.REAL,
                'o2': consts.ast.types.REAL,
                'o3': consts.ast.types.REAL,
                'xx': None,
                'xy': consts.ast.types.REAL,
                'xz': consts.ast.types.REAL,
                'yx': consts.ast.types.REAL,
                'yy': consts.ast.types.REAL,
                'yz': consts.ast.types.REAL,
                'zx': consts.ast.types.REAL,
                'zy': consts.ast.types.REAL,
                'zz': consts.ast.types.REAL,
                'm': consts.ast.types.INTEGER,
            },
            {
                'o1': consts.ast.types.REAL,
                'o2': consts.ast.types.REAL,
                'o3': consts.ast.types.REAL,
                'xx': consts.ast.types.REAL,
                'xy': None,
                'xz': consts.ast.types.REAL,
                'yx': consts.ast.types.REAL,
                'yy': consts.ast.types.REAL,
                'yz': consts.ast.types.REAL,
                'zx': consts.ast.types.REAL,
                'zy': consts.ast.types.REAL,
                'zz': consts.ast.types.REAL,
                'm': consts.ast.types.INTEGER,
            },
            {
                'o1': consts.ast.types.REAL,
                'o2': consts.ast.types.REAL,
                'o3': consts.ast.types.REAL,
                'xx': consts.ast.types.REAL,
                'xy': consts.ast.types.REAL,
                'xz': None,
                'yx': consts.ast.types.REAL,
                'yy': consts.ast.types.REAL,
                'yz': consts.ast.types.REAL,
                'zx': consts.ast.types.REAL,
                'zy': consts.ast.types.REAL,
                'zz': consts.ast.types.REAL,
                'm': consts.ast.types.INTEGER,
            },
            {
                'o1': consts.ast.types.REAL,
                'o2': consts.ast.types.REAL,
                'o3': consts.ast.types.REAL,
                'xx': consts.ast.types.REAL,
                'xy': consts.ast.types.REAL,
                'xz': consts.ast.types.REAL,
                'yx': None,
                'yy': consts.ast.types.REAL,
                'yz': consts.ast.types.REAL,
                'zx': consts.ast.types.REAL,
                'zy': consts.ast.types.REAL,
                'zz': consts.ast.types.REAL,
                'm': consts.ast.types.INTEGER,
            },
            {
                'o1': consts.ast.types.REAL,
                'o2': consts.ast.types.REAL,
                'o3': consts.ast.types.REAL,
                'xx': consts.ast.types.REAL,
                'xy': consts.ast.types.REAL,
                'xz': consts.ast.types.REAL,
                'yx': consts.ast.types.REAL,
                'yy': None,
                'yz': consts.ast.types.REAL,
                'zx': consts.ast.types.REAL,
                'zy': consts.ast.types.REAL,
                'zz': consts.ast.types.REAL,
                'm': consts.ast.types.INTEGER,
            },
            {
                'o1': consts.ast.types.REAL,
                'o2': consts.ast.types.REAL,
                'o3': consts.ast.types.REAL,
                'xx': consts.ast.types.REAL,
                'xy': consts.ast.types.REAL,
                'xz': consts.ast.types.REAL,
                'yx': consts.ast.types.REAL,
                'yy': consts.ast.types.REAL,
                'yz': None,
                'zx': consts.ast.types.REAL,
                'zy': consts.ast.types.REAL,
                'zz': consts.ast.types.REAL,
                'm': consts.ast.types.INTEGER,
            },
            {
                'o1': consts.ast.types.REAL,
                'o2': consts.ast.types.REAL,
                'o3': consts.ast.types.REAL,
                'xx': consts.ast.types.REAL,
                'xy': consts.ast.types.REAL,
                'xz': consts.ast.types.REAL,
                'yx': consts.ast.types.REAL,
                'yy': consts.ast.types.REAL,
                'yz': consts.ast.types.REAL,
                'zx': None,
                'zy': consts.ast.types.REAL,
                'zz': consts.ast.types.REAL,
                'm': consts.ast.types.INTEGER,
            },
            {
                'o1': consts.ast.types.REAL,
                'o2': consts.ast.types.REAL,
                'o3': consts.ast.types.REAL,
                'xx': consts.ast.types.REAL,
                'xy': consts.ast.types.REAL,
                'xz': consts.ast.types.REAL,
                'yx': consts.ast.types.REAL,
                'yy': consts.ast.types.REAL,
                'yz': consts.ast.types.REAL,
                'zx': consts.ast.types.REAL,
                'zy': None,
                'zz': consts.ast.types.REAL,
                'm': consts.ast.types.INTEGER,
            },
            {
                'o1': consts.ast.types.REAL,
                'o2': consts.ast.types.REAL,
                'o3': consts.ast.types.REAL,
                'xx': consts.ast.types.REAL,
                'xy': consts.ast.types.REAL,
                'xz': consts.ast.types.REAL,
                'yx': consts.ast.types.REAL,
                'yy': consts.ast.types.REAL,
                'yz': consts.ast.types.REAL,
                'zx': consts.ast.types.REAL,
                'zy': consts.ast.types.REAL,
                'zz': None,
                'm': consts.ast.types.INTEGER,
            },
            {
                'o1': consts.ast.types.REAL,
                'o2': consts.ast.types.REAL,
                'o3': consts.ast.types.REAL,
                'xx': consts.ast.types.REAL,
                'xy': consts.ast.types.REAL,
                'xz': consts.ast.types.REAL,
                'yx': consts.ast.types.REAL,
                'yy': consts.ast.types.REAL,
                'yz': consts.ast.types.REAL,
                'zx': consts.ast.types.REAL,
                'zy': consts.ast.types.REAL,
                'zz': consts.ast.types.REAL,
                'm': pymcnp.types.Integer(2),
            },
        ]

    class Test_Mcnp(classes.Test_Mcnp):
        element = pymcnp.types.Transformation_0
        EXAMPLES_VALID = [
            consts.string.types.TRANSFORMATION_0,
        ]
        EXAMPLES_INVALID = [
            'hello',
        ]


class Test_Transformation_1:
    class Test_Init(classes.Test_Init):
        element = pymcnp.types.Transformation_1
        EXAMPLES_VALID = [
            {
                'o1': consts.ast.types.REAL,
                'o2': consts.ast.types.REAL,
                'o3': consts.ast.types.REAL,
                'xx': consts.ast.types.REAL,
                'xy': consts.ast.types.REAL,
                'xz': consts.ast.types.REAL,
                'yx': consts.ast.types.REAL,
                'yy': consts.ast.types.REAL,
                'yz': consts.ast.types.REAL,
                'm': consts.ast.types.INTEGER,
            },
            {
                'o1': consts.ast.types.REAL,
                'o2': consts.ast.types.REAL,
                'o3': consts.ast.types.REAL,
                'xx': consts.ast.types.REAL,
                'xy': consts.ast.types.REAL,
                'xz': consts.ast.types.REAL,
                'yx': consts.ast.types.REAL,
                'yy': consts.ast.types.REAL,
                'yz': consts.ast.types.REAL,
                'm': None,
            },
        ]
        EXAMPLES_INVALID = [
            {
                'o1': None,
                'o2': consts.ast.types.REAL,
                'o3': consts.ast.types.REAL,
                'xx': consts.ast.types.REAL,
                'xy': consts.ast.types.REAL,
                'xz': consts.ast.types.REAL,
                'yx': consts.ast.types.REAL,
                'yy': consts.ast.types.REAL,
                'yz': consts.ast.types.REAL,
                'm': consts.ast.types.INTEGER,
            },
            {
                'o1': consts.ast.types.REAL,
                'o2': None,
                'o3': consts.ast.types.REAL,
                'xx': consts.ast.types.REAL,
                'xy': consts.ast.types.REAL,
                'xz': consts.ast.types.REAL,
                'yx': consts.ast.types.REAL,
                'yy': consts.ast.types.REAL,
                'yz': consts.ast.types.REAL,
                'm': consts.ast.types.INTEGER,
            },
            {
                'o1': consts.ast.types.REAL,
                'o2': consts.ast.types.REAL,
                'o3': None,
                'xx': consts.ast.types.REAL,
                'xy': consts.ast.types.REAL,
                'xz': consts.ast.types.REAL,
                'yx': consts.ast.types.REAL,
                'yy': consts.ast.types.REAL,
                'yz': consts.ast.types.REAL,
                'm': consts.ast.types.INTEGER,
            },
            {
                'o1': consts.ast.types.REAL,
                'o2': consts.ast.types.REAL,
                'o3': consts.ast.types.REAL,
                'xx': None,
                'xy': consts.ast.types.REAL,
                'xz': consts.ast.types.REAL,
                'yx': consts.ast.types.REAL,
                'yy': consts.ast.types.REAL,
                'yz': consts.ast.types.REAL,
                'm': consts.ast.types.INTEGER,
            },
            {
                'o1': consts.ast.types.REAL,
                'o2': consts.ast.types.REAL,
                'o3': consts.ast.types.REAL,
                'xx': consts.ast.types.REAL,
                'xy': None,
                'xz': consts.ast.types.REAL,
                'yx': consts.ast.types.REAL,
                'yy': consts.ast.types.REAL,
                'yz': consts.ast.types.REAL,
                'm': consts.ast.types.INTEGER,
            },
            {
                'o1': consts.ast.types.REAL,
                'o2': consts.ast.types.REAL,
                'o3': consts.ast.types.REAL,
                'xx': consts.ast.types.REAL,
                'xy': consts.ast.types.REAL,
                'xz': None,
                'yx': consts.ast.types.REAL,
                'yy': consts.ast.types.REAL,
                'yz': consts.ast.types.REAL,
                'm': consts.ast.types.INTEGER,
            },
            {
                'o1': consts.ast.types.REAL,
                'o2': consts.ast.types.REAL,
                'o3': consts.ast.types.REAL,
                'xx': consts.ast.types.REAL,
                'xy': consts.ast.types.REAL,
                'xz': consts.ast.types.REAL,
                'yx': None,
                'yy': consts.ast.types.REAL,
                'yz': consts.ast.types.REAL,
                'm': consts.ast.types.INTEGER,
            },
            {
                'o1': consts.ast.types.REAL,
                'o2': consts.ast.types.REAL,
                'o3': consts.ast.types.REAL,
                'xx': consts.ast.types.REAL,
                'xy': consts.ast.types.REAL,
                'xz': consts.ast.types.REAL,
                'yx': consts.ast.types.REAL,
                'yy': None,
                'yz': consts.ast.types.REAL,
                'm': consts.ast.types.INTEGER,
            },
            {
                'o1': consts.ast.types.REAL,
                'o2': consts.ast.types.REAL,
                'o3': consts.ast.types.REAL,
                'xx': consts.ast.types.REAL,
                'xy': consts.ast.types.REAL,
                'xz': consts.ast.types.REAL,
                'yx': consts.ast.types.REAL,
                'yy': consts.ast.types.REAL,
                'yz': None,
                'm': consts.ast.types.INTEGER,
            },
            {
                'o1': consts.ast.types.REAL,
                'o2': consts.ast.types.REAL,
                'o3': consts.ast.types.REAL,
                'xx': consts.ast.types.REAL,
                'xy': consts.ast.types.REAL,
                'xz': consts.ast.types.REAL,
                'yx': consts.ast.types.REAL,
                'yy': consts.ast.types.REAL,
                'yz': consts.ast.types.REAL,
                'm': pymcnp.types.Integer(2),
            },
        ]

    class Test_Mcnp(classes.Test_Mcnp):
        element = pymcnp.types.Transformation_1
        EXAMPLES_VALID = [
            consts.string.types.TRANSFORMATION_1,
        ]
        EXAMPLES_INVALID = [
            'hello',
        ]


class Test_Transformation_2:
    class Test_Init(classes.Test_Init):
        element = pymcnp.types.Transformation_2
        EXAMPLES_VALID = [
            {
                'o1': consts.ast.types.REAL,
                'o2': consts.ast.types.REAL,
                'o3': consts.ast.types.REAL,
                'xx': consts.ast.types.REAL,
                'xy': consts.ast.types.REAL,
                'xz': consts.ast.types.REAL,
                'yx': consts.ast.types.REAL,
                'yy': consts.ast.types.REAL,
                'm': consts.ast.types.INTEGER,
            },
            {
                'o1': consts.ast.types.REAL,
                'o2': consts.ast.types.REAL,
                'o3': consts.ast.types.REAL,
                'xx': consts.ast.types.REAL,
                'xy': consts.ast.types.REAL,
                'xz': consts.ast.types.REAL,
                'yx': consts.ast.types.REAL,
                'yy': consts.ast.types.REAL,
                'm': None,
            },
        ]
        EXAMPLES_INVALID = [
            {
                'o1': None,
                'o2': consts.ast.types.REAL,
                'o3': consts.ast.types.REAL,
                'xx': consts.ast.types.REAL,
                'xy': consts.ast.types.REAL,
                'xz': consts.ast.types.REAL,
                'yx': consts.ast.types.REAL,
                'yy': consts.ast.types.REAL,
                'm': consts.ast.types.INTEGER,
            },
            {
                'o1': consts.ast.types.REAL,
                'o2': None,
                'o3': consts.ast.types.REAL,
                'xx': consts.ast.types.REAL,
                'xy': consts.ast.types.REAL,
                'xz': consts.ast.types.REAL,
                'yx': consts.ast.types.REAL,
                'yy': consts.ast.types.REAL,
                'm': consts.ast.types.INTEGER,
            },
            {
                'o1': consts.ast.types.REAL,
                'o2': consts.ast.types.REAL,
                'o3': None,
                'xx': consts.ast.types.REAL,
                'xy': consts.ast.types.REAL,
                'xz': consts.ast.types.REAL,
                'yx': consts.ast.types.REAL,
                'yy': consts.ast.types.REAL,
                'm': consts.ast.types.INTEGER,
            },
            {
                'o1': consts.ast.types.REAL,
                'o2': consts.ast.types.REAL,
                'o3': consts.ast.types.REAL,
                'xx': None,
                'xy': consts.ast.types.REAL,
                'xz': consts.ast.types.REAL,
                'yx': consts.ast.types.REAL,
                'yy': consts.ast.types.REAL,
                'm': consts.ast.types.INTEGER,
            },
            {
                'o1': consts.ast.types.REAL,
                'o2': consts.ast.types.REAL,
                'o3': consts.ast.types.REAL,
                'xx': consts.ast.types.REAL,
                'xy': None,
                'xz': consts.ast.types.REAL,
                'yx': consts.ast.types.REAL,
                'yy': consts.ast.types.REAL,
                'm': consts.ast.types.INTEGER,
            },
            {
                'o1': consts.ast.types.REAL,
                'o2': consts.ast.types.REAL,
                'o3': consts.ast.types.REAL,
                'xx': consts.ast.types.REAL,
                'xy': consts.ast.types.REAL,
                'xz': None,
                'yx': consts.ast.types.REAL,
                'yy': consts.ast.types.REAL,
                'm': consts.ast.types.INTEGER,
            },
            {
                'o1': consts.ast.types.REAL,
                'o2': consts.ast.types.REAL,
                'o3': consts.ast.types.REAL,
                'xx': consts.ast.types.REAL,
                'xy': consts.ast.types.REAL,
                'xz': consts.ast.types.REAL,
                'yx': None,
                'yy': consts.ast.types.REAL,
                'm': consts.ast.types.INTEGER,
            },
            {
                'o1': consts.ast.types.REAL,
                'o2': consts.ast.types.REAL,
                'o3': consts.ast.types.REAL,
                'xx': consts.ast.types.REAL,
                'xy': consts.ast.types.REAL,
                'xz': consts.ast.types.REAL,
                'yx': consts.ast.types.REAL,
                'yy': None,
                'm': consts.ast.types.INTEGER,
            },
            {
                'o1': consts.ast.types.REAL,
                'o2': consts.ast.types.REAL,
                'o3': consts.ast.types.REAL,
                'xx': consts.ast.types.REAL,
                'xy': consts.ast.types.REAL,
                'xz': consts.ast.types.REAL,
                'yx': consts.ast.types.REAL,
                'yy': consts.ast.types.REAL,
                'm': pymcnp.types.Integer(2),
            },
        ]

    class Test_Mcnp(classes.Test_Mcnp):
        element = pymcnp.types.Transformation_2
        EXAMPLES_VALID = [
            consts.string.types.TRANSFORMATION_2,
        ]
        EXAMPLES_INVALID = [
            'hello',
        ]


class Test_Transformation_3:
    class Test_Init(classes.Test_Init):
        element = pymcnp.types.Transformation_3
        EXAMPLES_VALID = [
            {
                'o1': consts.ast.types.REAL,
                'o2': consts.ast.types.REAL,
                'o3': consts.ast.types.REAL,
                'xx': consts.ast.types.REAL,
                'xy': consts.ast.types.REAL,
                'xz': consts.ast.types.REAL,
                'm': consts.ast.types.INTEGER,
            },
            {
                'o1': consts.ast.types.REAL,
                'o2': consts.ast.types.REAL,
                'o3': consts.ast.types.REAL,
                'xx': consts.ast.types.REAL,
                'xy': consts.ast.types.REAL,
                'xz': consts.ast.types.REAL,
                'm': None,
            },
        ]
        EXAMPLES_INVALID = [
            {
                'o1': None,
                'o2': consts.ast.types.REAL,
                'o3': consts.ast.types.REAL,
                'xx': consts.ast.types.REAL,
                'xy': consts.ast.types.REAL,
                'xz': consts.ast.types.REAL,
                'm': consts.ast.types.INTEGER,
            },
            {
                'o1': consts.ast.types.REAL,
                'o2': None,
                'o3': consts.ast.types.REAL,
                'xx': consts.ast.types.REAL,
                'xy': consts.ast.types.REAL,
                'xz': consts.ast.types.REAL,
                'm': consts.ast.types.INTEGER,
            },
            {
                'o1': consts.ast.types.REAL,
                'o2': consts.ast.types.REAL,
                'o3': None,
                'xx': consts.ast.types.REAL,
                'xy': consts.ast.types.REAL,
                'xz': consts.ast.types.REAL,
                'm': consts.ast.types.INTEGER,
            },
            {
                'o1': consts.ast.types.REAL,
                'o2': consts.ast.types.REAL,
                'o3': consts.ast.types.REAL,
                'xx': None,
                'xy': consts.ast.types.REAL,
                'xz': consts.ast.types.REAL,
                'm': consts.ast.types.INTEGER,
            },
            {
                'o1': consts.ast.types.REAL,
                'o2': consts.ast.types.REAL,
                'o3': consts.ast.types.REAL,
                'xx': consts.ast.types.REAL,
                'xy': None,
                'xz': consts.ast.types.REAL,
                'm': consts.ast.types.INTEGER,
            },
            {
                'o1': consts.ast.types.REAL,
                'o2': consts.ast.types.REAL,
                'o3': consts.ast.types.REAL,
                'xx': consts.ast.types.REAL,
                'xy': consts.ast.types.REAL,
                'xz': None,
                'm': consts.ast.types.INTEGER,
            },
            {
                'o1': consts.ast.types.REAL,
                'o2': consts.ast.types.REAL,
                'o3': consts.ast.types.REAL,
                'xx': consts.ast.types.REAL,
                'xy': consts.ast.types.REAL,
                'xz': consts.ast.types.REAL,
                'm': pymcnp.types.Integer(2),
            },
        ]

    class Test_Mcnp(classes.Test_Mcnp):
        element = pymcnp.types.Transformation_3
        EXAMPLES_VALID = [
            consts.string.types.TRANSFORMATION_3,
        ]
        EXAMPLES_INVALID = [
            'hello',
        ]


class Test_Transformation_4:
    class Test_Init(classes.Test_Init):
        element = pymcnp.types.Transformation_4
        EXAMPLES_VALID = [
            {
                'o1': consts.ast.types.REAL,
                'o2': consts.ast.types.REAL,
                'o3': consts.ast.types.REAL,
                'm': consts.ast.types.INTEGER,
            },
            {
                'o1': consts.ast.types.REAL,
                'o2': consts.ast.types.REAL,
                'o3': consts.ast.types.REAL,
                'm': None,
            },
        ]
        EXAMPLES_INVALID = [
            {
                'o1': None,
                'o2': consts.ast.types.REAL,
                'o3': consts.ast.types.REAL,
                'm': consts.ast.types.INTEGER,
            },
            {
                'o1': consts.ast.types.REAL,
                'o2': None,
                'o3': consts.ast.types.REAL,
                'm': consts.ast.types.INTEGER,
            },
            {
                'o1': consts.ast.types.REAL,
                'o2': consts.ast.types.REAL,
                'o3': None,
                'm': consts.ast.types.INTEGER,
            },
            {
                'o1': consts.ast.types.REAL,
                'o2': consts.ast.types.REAL,
                'o3': consts.ast.types.REAL,
                'm': pymcnp.types.Integer(2),
            },
        ]

    class Test_Mcnp(classes.Test_Mcnp):
        element = pymcnp.types.Transformation_4
        EXAMPLES_VALID = [
            consts.string.types.TRANSFORMATION_4,
        ]
        EXAMPLES_INVALID = [
            'hello',
        ]
