import enum
import typing


class McnpCode(enum.Enum):
    """
    Represents MCNP error codes.

    Notes:
        1XXX - Syntax
        2XXX - Semantics
        X0XX - Inp
        X1XX - Cell
        X2XX - Surface
        X3XX - Data
        X4XX - Comment
        X5XX - Types
    """

    SYNTAX_INP = 1000

    SYNTAX_CELL = 1100
    SYNTAX_CELL_KEYWORD = 1101
    SYNTAX_CELL_OPTION = 1102
    SYNTAX_CELL_ENTRY = 1103

    SYNTAX_SURFACE = 1200
    SYNTAX_SURFACE_KEYWORD = 1201
    SYNTAX_SURFACE_OPTION = 1202
    SYNTAX_SURFACE_ENTRY = 1203

    SYNTAX_DATA = 1301
    SYNTAX_DATA_KEYWORD = 1302
    SYNTAX_DATA_OPTION = 1303
    SYNTAX_DAWWG_OPTION = 1304
    SYNTAX_BLOCK_OPTION = 1305
    SYNTAX_EMBED_OPTION = 1306
    SYNTAX_EMBEE_OPTION = 1307
    SYNTAX_M_OPTION = 1308
    SYNTAX_ACT_OPTION = 1309
    SYNTAX_FMULT_OPTION = 1310
    SYNTAX_TROPT_OPTION = 1311
    SYNTAX_BFLD_OPTION = 1312
    SYNTAX_SDEF_OPTION = 1313
    SYNTAX_SSW_OPTION = 1314
    SYNTAX_SSR_OPTION = 1315
    SYNTAX_KOPTS_OPTION = 1316
    SYNTAX_PERT_OPTION = 1317
    SYNTAX_KPERT_OPTION = 1318
    SYNTAX_KSEN_OPTION = 1319
    SYNTAX_FMESH_OPTION = 1320
    SYNTAX_MESH_OPTION = 1321
    SYNTAX_STOP_OPTION = 1322
    SYNTAX_PTRAC_OPTION = 1323
    SYNTAX_RAND_OPTION = 1324
    SYNTAX_TR_ENTRY = 1325
    SYNTAX_URAN_ENTRY = 1326
    SYNTAX_M_ENTRY = 1327
    SYNTAX_AWTAB_ENTRY = 1328
    SYNTAX_XS_ENTRY = 1329
    SYNTAX_DNEB_ENTRY = 1330
    SYNTAX_DGEB_ENTRY = 1331
    SYNTAX_KSRC_ENTRY = 1332
    SYNTAX_SD_ENTRY = 1333
    SYNTAX_DXT_ENTRY = 1334
    SYNTAX_DD_ENTRY = 1335
    SYNTAX_PIKMT_ENTRY = 1336
    SYNTAX_BIAS_ENTRY = 1337
    SYNTAX_FILTER_ENTRY = 1338
    SYNTAX_FILES_ENTRY = 1339

    SYNTAX_COMMENT = 1400

    SYNTAX_INTEGER = 1500
    SYNTAX_REAL = 1501
    SYNTAX_STRING = 1502
    SYNTAX_REPEAT = 1503
    SYNTAX_INSERT = 1504
    SYNTAX_MULTIPLY = 1505
    SYNTAX_JUMP = 1506
    SYNTAX_LOG = 1507
    SYNTAX_DISTRIBUTIONNUMBER = 1508
    SYNTAX_EMBEDDEDDISTRIBUTIONNUMBER = 1509
    SYNTAX_ZAID = 1510
    SYNTAX_PARTICLE = 1511
    SYNTAX_DESIGNATOR = 1512

    SEMANTICS_INP_MESSAGE = 2000
    SEMANTICS_INP_TITLE = 2001
    SEMANTICS_INP_CELLS = 2002
    SEMANTICS_INP_COMMENTS = 2003
    SEMANTICS_INP_SURFACES = 2004
    SEMANTICS_INP_DATA = 2005
    SEMANTICS_INP_OTHER = 2006

    SEMANTICS_CELL_NUMBER = 2100
    SEMANTICS_CELL_MATERIAL = 2101
    SEMANTICS_CELL_DENSITY = 2102
    SEMANTICS_CELL_GEOMETRY = 2103
    SEMANTICS_CELL_OPTIONS = 2104
    SEMANTICS_CELL_OPTION_VALUE = 2105
    SEMANTICS_CELL_OPTION_SUFFIX = 2106
    SEMANTICS_CELL_OPTION_DESIGNATOR = 2107
    SEMANTICS_CELL_ENTRY_PARAMETER = 2108

    SEMANTICS_SURFACE_NUMBER = 2200
    SEMANTICS_SURFACE_TRANSFORM = 2201
    SEMANTICS_SURFACE_OPTION = 2202
    SEMANTICS_SURFACE_PREFIX = 2203
    SEMANTICS_SURFACE_OPTION_VALUE = 2204

    SEMANTICS_DATA_OPTION = 2300
    SEMANTICS_DATA_OPTION_VALUE = 2301
    SEMANTICS_DATA_OPTION_SUFFIX = 2302
    SEMANTICS_DATA_OPTION_DESIGNATOR = 2303
    SEMANTICS_DATA_OPTION_ENTRY = 2304
    SEMANTICS_DATA_OPTION_ENTRY_VALUE = 2305

    SEMANTICS_COMMENT_TEXT = 2400

    SEMANTICS_INTEGER_VALUE = 2500
    SEMANTICS_REAL_VALUE = 2501
    SEMANTICS_STRING_VALUE = 2502
    SEMANTICS_REPEAT_N = 2503
    SEMANTICS_INSERT_N = 2504
    SEMANTICS_MULTIPLY_X = 2505
    SEMANTICS_JUMP_N = 2506
    SEMANTICS_LOG_N = 2507
    SEMANTICS_DISTRIBUTIONNUMBER_N = 2508
    SEMANTICS_EMBEDDEDDISTRIBUTIONNUMBER_NUMBERS = 2509
    SEMANTICS_ZAID_Z = 2510
    SEMANTICS_ZAID_A = 2511
    SEMANTICS_ZAID_ABX = 2512
    SEMANTICS_DESIGNATOR_PARTICLES = 2513
    SEMANTICS_DICT_VALUE = 2514
    SEMANTICS_TUPLE_VALUE = 2515


class McnpError(Exception):
    def __init__(self, code: McnpCode, info: str):
        """
        Initializes ``McnpError``

        Parameters:
            code: Error code.
            info: Error string.

        Returns:
                ``McnpError``.
        """

        self.code: typing.Final[McnpCode] = code
        self.info: typing.Final[str] = info


class CliCode(enum.Enum):
    """
    Represents CLI error codes.
    """

    SEMANTICS_INP = 110
    SEMANTICS_PATH = 111
    SEMANTICS_PREHOOK = 112
    SEMANTICS_POSTHOOK = 113
    SEMANTICS_COMMAND = 114


class CliError(Exception):
    """
    Represents CLI errors.

    Attributes:
        code: Error code.
        info: Error string.
    """

    def __init__(self, code: CliCode, info: str):
        """
        Initializes ``CliError``

        Parameters:
            code: Error code.
            info: Error string.

        Returns:
                ``CliError``.
        """

        self.code: typing.Final[CliCode] = code
        self.info: typing.Final[str] = info
