import pymcnp
from .... import classes


class Test_Block(classes.Test_Nonterminal):
    element = pymcnp.inp.option.Block
    EXAMPLES_VALID = [
        'ngroup 1',
        'isn 1',
        'niso 1',
        'mt 1',
        'iquad 1',
        'fmmix 1',
        'nosolv 1',
        'noedit 1',
        'nogeod 1',
        'nomix 1',
        'noasg 1',
        'nomacr 1',
        'noslnp 1',
        'noedtt 1',
        'noadjm 1',
        'lib hello',
        'libname hello',
        'fissneut 1',
        'lng 1',
        'balxs 1',
        'ntichi 1',
        'ievt 1',
        'isct 1',
        'ith 1',
        'trcor diag',
        'ibl 1',
        'ibr 1',
        'ibt 1',
        'ibb 1',
        'ibfrnt 1',
        'ibback 1',
        'epsi 3.1',
        'oitm 1',
        'nosigf 1',
        'srcacc dsa',
        'diffsol hello',
        'tsasn 1',
        'tsaepsi 3.1',
        'tsaits 1',
        'tsabeta 1',
        'ptconv 1',
        'norm 3.1',
        'xsectp 1',
        'fissrp 1',
        'sourcp 1',
        'angp 1',
        'balp 1',
        'raflux 1',
        'rmflux 1',
        'avatar 1',
        'asleft 1',
        'asrite 1',
        'asbott 1',
        'astop 1',
        'asfrnt 1',
        'asback 1',
        'massed 1',
        'pted 1',
        'zned 1',
        'rzflux 1',
        'rzmflux 1',
        'edoutf 1',
        'byvolp 1',
        'ajed 1',
        'fluxone 1',
    ]
    EXAMPLES_INVALID = [
        'hello',
    ]
