import pymcnp
from ... import consts
from ... import classes


class Test_Mcnp:
    class Test_Init(classes.Test_Init):
        element = pymcnp.outp.Mcnp
        EXAMPLES_VALID = [
            {
                'version': consts.string.types.STRING,
                'code_date': consts.string.types.STRING,
                'run_date': consts.string.types.STRING,
                'run_time': consts.string.types.STRING,
                'probid': consts.string.types.STRING,
                'command': consts.string.types.STRING,
                'lines': consts.string.types.STRING,
                'random_generator': consts.string.types.STRING,
                'random_seed': consts.string.types.STRING,
                'random_multiplier': consts.string.types.STRING,
                'random_adder': consts.string.types.STRING,
                'random_bits': consts.string.types.STRING,
                'random_stride': consts.string.types.STRING,
                'messages': consts.string.types.STRING,
            },
        ]
        EXAMPLES_INVALID = [
            {
                'version': None,
                'code_date': consts.string.types.STRING,
                'run_date': consts.string.types.STRING,
                'run_time': consts.string.types.STRING,
                'probid': consts.string.types.STRING,
                'command': consts.string.types.STRING,
                'lines': consts.string.types.STRING,
                'random_generator': consts.string.types.STRING,
                'random_seed': consts.string.types.STRING,
                'random_multiplier': consts.string.types.STRING,
                'random_adder': consts.string.types.STRING,
                'random_bits': consts.string.types.STRING,
                'random_stride': consts.string.types.STRING,
                'messages': consts.string.types.STRING,
            },
            {
                'version': consts.string.types.STRING,
                'code_date': None,
                'run_date': consts.string.types.STRING,
                'run_time': consts.string.types.STRING,
                'probid': consts.string.types.STRING,
                'command': consts.string.types.STRING,
                'lines': consts.string.types.STRING,
                'random_generator': consts.string.types.STRING,
                'random_seed': consts.string.types.STRING,
                'random_multiplier': consts.string.types.STRING,
                'random_adder': consts.string.types.STRING,
                'random_bits': consts.string.types.STRING,
                'random_stride': consts.string.types.STRING,
                'messages': consts.string.types.STRING,
            },
            {
                'version': consts.string.types.STRING,
                'code_date': consts.string.types.STRING,
                'run_date': None,
                'run_time': consts.string.types.STRING,
                'probid': consts.string.types.STRING,
                'command': consts.string.types.STRING,
                'lines': consts.string.types.STRING,
                'random_generator': consts.string.types.STRING,
                'random_seed': consts.string.types.STRING,
                'random_multiplier': consts.string.types.STRING,
                'random_adder': consts.string.types.STRING,
                'random_bits': consts.string.types.STRING,
                'random_stride': consts.string.types.STRING,
                'messages': consts.string.types.STRING,
            },
            {
                'version': consts.string.types.STRING,
                'code_date': consts.string.types.STRING,
                'run_date': consts.string.types.STRING,
                'run_time': None,
                'probid': consts.string.types.STRING,
                'command': consts.string.types.STRING,
                'lines': consts.string.types.STRING,
                'random_generator': consts.string.types.STRING,
                'random_seed': consts.string.types.STRING,
                'random_multiplier': consts.string.types.STRING,
                'random_adder': consts.string.types.STRING,
                'random_bits': consts.string.types.STRING,
                'random_stride': consts.string.types.STRING,
                'messages': consts.string.types.STRING,
            },
            {
                'version': consts.string.types.STRING,
                'code_date': consts.string.types.STRING,
                'run_date': consts.string.types.STRING,
                'run_time': consts.string.types.STRING,
                'probid': None,
                'command': consts.string.types.STRING,
                'lines': consts.string.types.STRING,
                'random_generator': consts.string.types.STRING,
                'random_seed': consts.string.types.STRING,
                'random_multiplier': consts.string.types.STRING,
                'random_adder': consts.string.types.STRING,
                'random_bits': consts.string.types.STRING,
                'random_stride': consts.string.types.STRING,
                'messages': consts.string.types.STRING,
            },
            {
                'version': consts.string.types.STRING,
                'code_date': consts.string.types.STRING,
                'run_date': consts.string.types.STRING,
                'run_time': consts.string.types.STRING,
                'probid': consts.string.types.STRING,
                'command': None,
                'lines': consts.string.types.STRING,
                'random_generator': consts.string.types.STRING,
                'random_seed': consts.string.types.STRING,
                'random_multiplier': consts.string.types.STRING,
                'random_adder': consts.string.types.STRING,
                'random_bits': consts.string.types.STRING,
                'random_stride': consts.string.types.STRING,
                'messages': consts.string.types.STRING,
            },
            {
                'version': consts.string.types.STRING,
                'code_date': consts.string.types.STRING,
                'run_date': consts.string.types.STRING,
                'run_time': consts.string.types.STRING,
                'probid': consts.string.types.STRING,
                'command': consts.string.types.STRING,
                'lines': None,
                'random_generator': consts.string.types.STRING,
                'random_seed': consts.string.types.STRING,
                'random_multiplier': consts.string.types.STRING,
                'random_adder': consts.string.types.STRING,
                'random_bits': consts.string.types.STRING,
                'random_stride': consts.string.types.STRING,
                'messages': consts.string.types.STRING,
            },
            {
                'version': consts.string.types.STRING,
                'code_date': consts.string.types.STRING,
                'run_date': consts.string.types.STRING,
                'run_time': consts.string.types.STRING,
                'probid': consts.string.types.STRING,
                'command': consts.string.types.STRING,
                'lines': consts.string.types.STRING,
                'random_generator': None,
                'random_seed': consts.string.types.STRING,
                'random_multiplier': consts.string.types.STRING,
                'random_adder': consts.string.types.STRING,
                'random_bits': consts.string.types.STRING,
                'random_stride': consts.string.types.STRING,
                'messages': consts.string.types.STRING,
            },
            {
                'version': consts.string.types.STRING,
                'code_date': consts.string.types.STRING,
                'run_date': consts.string.types.STRING,
                'run_time': consts.string.types.STRING,
                'probid': consts.string.types.STRING,
                'command': consts.string.types.STRING,
                'lines': consts.string.types.STRING,
                'random_generator': consts.string.types.STRING,
                'random_seed': None,
                'random_multiplier': consts.string.types.STRING,
                'random_adder': consts.string.types.STRING,
                'random_bits': consts.string.types.STRING,
                'random_stride': consts.string.types.STRING,
                'messages': consts.string.types.STRING,
            },
            {
                'version': consts.string.types.STRING,
                'code_date': consts.string.types.STRING,
                'run_date': consts.string.types.STRING,
                'run_time': consts.string.types.STRING,
                'probid': consts.string.types.STRING,
                'command': consts.string.types.STRING,
                'lines': consts.string.types.STRING,
                'random_generator': consts.string.types.STRING,
                'random_seed': consts.string.types.STRING,
                'random_multiplier': None,
                'random_adder': consts.string.types.STRING,
                'random_bits': consts.string.types.STRING,
                'random_stride': consts.string.types.STRING,
                'messages': consts.string.types.STRING,
            },
            {
                'version': consts.string.types.STRING,
                'code_date': consts.string.types.STRING,
                'run_date': consts.string.types.STRING,
                'run_time': consts.string.types.STRING,
                'probid': consts.string.types.STRING,
                'command': consts.string.types.STRING,
                'lines': consts.string.types.STRING,
                'random_generator': consts.string.types.STRING,
                'random_seed': consts.string.types.STRING,
                'random_multiplier': consts.string.types.STRING,
                'random_adder': None,
                'random_bits': consts.string.types.STRING,
                'random_stride': consts.string.types.STRING,
                'messages': consts.string.types.STRING,
            },
            {
                'version': consts.string.types.STRING,
                'code_date': consts.string.types.STRING,
                'run_date': consts.string.types.STRING,
                'run_time': consts.string.types.STRING,
                'probid': consts.string.types.STRING,
                'command': consts.string.types.STRING,
                'lines': consts.string.types.STRING,
                'random_generator': consts.string.types.STRING,
                'random_seed': consts.string.types.STRING,
                'random_multiplier': consts.string.types.STRING,
                'random_adder': consts.string.types.STRING,
                'random_bits': None,
                'random_stride': consts.string.types.STRING,
                'messages': consts.string.types.STRING,
            },
            {
                'version': consts.string.types.STRING,
                'code_date': consts.string.types.STRING,
                'run_date': consts.string.types.STRING,
                'run_time': consts.string.types.STRING,
                'probid': consts.string.types.STRING,
                'command': consts.string.types.STRING,
                'lines': consts.string.types.STRING,
                'random_generator': consts.string.types.STRING,
                'random_seed': consts.string.types.STRING,
                'random_multiplier': consts.string.types.STRING,
                'random_adder': consts.string.types.STRING,
                'random_bits': consts.string.types.STRING,
                'random_stride': None,
                'messages': consts.string.types.STRING,
            },
            {
                'version': consts.string.types.STRING,
                'code_date': consts.string.types.STRING,
                'run_date': consts.string.types.STRING,
                'run_time': consts.string.types.STRING,
                'probid': consts.string.types.STRING,
                'command': consts.string.types.STRING,
                'lines': consts.string.types.STRING,
                'random_generator': consts.string.types.STRING,
                'random_seed': consts.string.types.STRING,
                'random_multiplier': consts.string.types.STRING,
                'random_adder': consts.string.types.STRING,
                'random_bits': consts.string.types.STRING,
                'random_stride': consts.string.types.STRING,
                'messages': None,
            },
        ]

    class Test_Mcnp(classes.Test_Mcnp):
        element = pymcnp.outp.Mcnp
        EXAMPLES_VALID = [consts.string.outp.MCNP]
        EXAMPLES_INVALID = [
            'hello',
        ]
