import pymcnp
from ... import consts
from ... import classes


class Test_ProblemSummary:
    class Test_Init(classes.Test_Init):
        element = pymcnp.outp.ProblemSummary
        EXAMPLES_VALID = [
            {
                'histories': consts.string.type.STRING,
                'datetime': consts.string.type.STRING,
                'histories_rate': consts.string.type.STRING,
                'title': consts.string.type.STRING,
                'probid': consts.string.type.STRING,
                'neutron_data': consts.string.type.STRING,
                'proton_data': consts.string.type.STRING,
                'computer_time': consts.string.type.STRING,
                'max_bank': consts.string.type.STRING,
                'computer_mcrun': consts.string.type.STRING,
                'bank_overflows': consts.string.type.STRING,
                'source_per_minute': consts.string.type.STRING,
                'random_numbers': consts.string.type.STRING,
                'most_random': consts.string.type.STRING,
                'most_history': consts.string.type.STRING,
                'range_lower': consts.string.type.STRING,
                'range_upper': consts.string.type.STRING,
            },
        ]
        EXAMPLES_INVALID = [
            {
                'histories': None,
                'datetime': consts.string.type.STRING,
                'histories_rate': consts.string.type.STRING,
                'title': consts.string.type.STRING,
                'probid': consts.string.type.STRING,
                'neutron_data': consts.string.type.STRING,
                'proton_data': consts.string.type.STRING,
                'computer_time': consts.string.type.STRING,
                'max_bank': consts.string.type.STRING,
                'computer_mcrun': consts.string.type.STRING,
                'bank_overflows': consts.string.type.STRING,
                'source_per_minute': consts.string.type.STRING,
                'random_numbers': consts.string.type.STRING,
                'most_random': consts.string.type.STRING,
                'most_history': consts.string.type.STRING,
                'range_lower': consts.string.type.STRING,
                'range_upper': consts.string.type.STRING,
            },
            {
                'histories': consts.string.type.STRING,
                'datetime': None,
                'histories_rate': consts.string.type.STRING,
                'title': consts.string.type.STRING,
                'probid': consts.string.type.STRING,
                'neutron_data': consts.string.type.STRING,
                'proton_data': consts.string.type.STRING,
                'computer_time': consts.string.type.STRING,
                'max_bank': consts.string.type.STRING,
                'computer_mcrun': consts.string.type.STRING,
                'bank_overflows': consts.string.type.STRING,
                'source_per_minute': consts.string.type.STRING,
                'random_numbers': consts.string.type.STRING,
                'most_random': consts.string.type.STRING,
                'most_history': consts.string.type.STRING,
                'range_lower': consts.string.type.STRING,
                'range_upper': consts.string.type.STRING,
            },
            {
                'histories': consts.string.type.STRING,
                'datetime': consts.string.type.STRING,
                'histories_rate': None,
                'title': consts.string.type.STRING,
                'probid': consts.string.type.STRING,
                'neutron_data': consts.string.type.STRING,
                'proton_data': consts.string.type.STRING,
                'computer_time': consts.string.type.STRING,
                'max_bank': consts.string.type.STRING,
                'computer_mcrun': consts.string.type.STRING,
                'bank_overflows': consts.string.type.STRING,
                'source_per_minute': consts.string.type.STRING,
                'random_numbers': consts.string.type.STRING,
                'most_random': consts.string.type.STRING,
                'most_history': consts.string.type.STRING,
                'range_lower': consts.string.type.STRING,
                'range_upper': consts.string.type.STRING,
            },
            {
                'histories': consts.string.type.STRING,
                'datetime': consts.string.type.STRING,
                'histories_rate': consts.string.type.STRING,
                'title': None,
                'probid': consts.string.type.STRING,
                'neutron_data': consts.string.type.STRING,
                'proton_data': consts.string.type.STRING,
                'computer_time': consts.string.type.STRING,
                'max_bank': consts.string.type.STRING,
                'computer_mcrun': consts.string.type.STRING,
                'bank_overflows': consts.string.type.STRING,
                'source_per_minute': consts.string.type.STRING,
                'random_numbers': consts.string.type.STRING,
                'most_random': consts.string.type.STRING,
                'most_history': consts.string.type.STRING,
                'range_lower': consts.string.type.STRING,
                'range_upper': consts.string.type.STRING,
            },
            {
                'histories': consts.string.type.STRING,
                'datetime': consts.string.type.STRING,
                'histories_rate': consts.string.type.STRING,
                'title': consts.string.type.STRING,
                'probid': None,
                'neutron_data': consts.string.type.STRING,
                'proton_data': consts.string.type.STRING,
                'computer_time': consts.string.type.STRING,
                'max_bank': consts.string.type.STRING,
                'computer_mcrun': consts.string.type.STRING,
                'bank_overflows': consts.string.type.STRING,
                'source_per_minute': consts.string.type.STRING,
                'random_numbers': consts.string.type.STRING,
                'most_random': consts.string.type.STRING,
                'most_history': consts.string.type.STRING,
                'range_lower': consts.string.type.STRING,
                'range_upper': consts.string.type.STRING,
            },
            {
                'histories': consts.string.type.STRING,
                'datetime': consts.string.type.STRING,
                'histories_rate': consts.string.type.STRING,
                'title': consts.string.type.STRING,
                'probid': consts.string.type.STRING,
                'neutron_data': None,
                'proton_data': consts.string.type.STRING,
                'computer_time': consts.string.type.STRING,
                'max_bank': consts.string.type.STRING,
                'computer_mcrun': consts.string.type.STRING,
                'bank_overflows': consts.string.type.STRING,
                'source_per_minute': consts.string.type.STRING,
                'random_numbers': consts.string.type.STRING,
                'most_random': consts.string.type.STRING,
                'most_history': consts.string.type.STRING,
                'range_lower': consts.string.type.STRING,
                'range_upper': consts.string.type.STRING,
            },
            {
                'histories': consts.string.type.STRING,
                'datetime': consts.string.type.STRING,
                'histories_rate': consts.string.type.STRING,
                'title': consts.string.type.STRING,
                'probid': consts.string.type.STRING,
                'neutron_data': consts.string.type.STRING,
                'proton_data': None,
                'computer_time': consts.string.type.STRING,
                'max_bank': consts.string.type.STRING,
                'computer_mcrun': consts.string.type.STRING,
                'bank_overflows': consts.string.type.STRING,
                'source_per_minute': consts.string.type.STRING,
                'random_numbers': consts.string.type.STRING,
                'most_random': consts.string.type.STRING,
                'most_history': consts.string.type.STRING,
                'range_lower': consts.string.type.STRING,
                'range_upper': consts.string.type.STRING,
            },
            {
                'histories': consts.string.type.STRING,
                'datetime': consts.string.type.STRING,
                'histories_rate': consts.string.type.STRING,
                'title': consts.string.type.STRING,
                'probid': consts.string.type.STRING,
                'neutron_data': consts.string.type.STRING,
                'proton_data': consts.string.type.STRING,
                'computer_time': None,
                'max_bank': consts.string.type.STRING,
                'computer_mcrun': consts.string.type.STRING,
                'bank_overflows': consts.string.type.STRING,
                'source_per_minute': consts.string.type.STRING,
                'random_numbers': consts.string.type.STRING,
                'most_random': consts.string.type.STRING,
                'most_history': consts.string.type.STRING,
                'range_lower': consts.string.type.STRING,
                'range_upper': consts.string.type.STRING,
            },
            {
                'histories': consts.string.type.STRING,
                'datetime': consts.string.type.STRING,
                'histories_rate': consts.string.type.STRING,
                'title': consts.string.type.STRING,
                'probid': consts.string.type.STRING,
                'neutron_data': consts.string.type.STRING,
                'proton_data': consts.string.type.STRING,
                'computer_time': consts.string.type.STRING,
                'max_bank': None,
                'computer_mcrun': consts.string.type.STRING,
                'bank_overflows': consts.string.type.STRING,
                'source_per_minute': consts.string.type.STRING,
                'random_numbers': consts.string.type.STRING,
                'most_random': consts.string.type.STRING,
                'most_history': consts.string.type.STRING,
                'range_lower': consts.string.type.STRING,
                'range_upper': consts.string.type.STRING,
            },
            {
                'histories': consts.string.type.STRING,
                'datetime': consts.string.type.STRING,
                'histories_rate': consts.string.type.STRING,
                'title': consts.string.type.STRING,
                'probid': consts.string.type.STRING,
                'neutron_data': consts.string.type.STRING,
                'proton_data': consts.string.type.STRING,
                'computer_time': consts.string.type.STRING,
                'max_bank': consts.string.type.STRING,
                'computer_mcrun': None,
                'bank_overflows': consts.string.type.STRING,
                'source_per_minute': consts.string.type.STRING,
                'random_numbers': consts.string.type.STRING,
                'most_random': consts.string.type.STRING,
                'most_history': consts.string.type.STRING,
                'range_lower': consts.string.type.STRING,
                'range_upper': consts.string.type.STRING,
            },
            {
                'histories': consts.string.type.STRING,
                'datetime': consts.string.type.STRING,
                'histories_rate': consts.string.type.STRING,
                'title': consts.string.type.STRING,
                'probid': consts.string.type.STRING,
                'neutron_data': consts.string.type.STRING,
                'proton_data': consts.string.type.STRING,
                'computer_time': consts.string.type.STRING,
                'max_bank': consts.string.type.STRING,
                'computer_mcrun': consts.string.type.STRING,
                'bank_overflows': None,
                'source_per_minute': consts.string.type.STRING,
                'random_numbers': consts.string.type.STRING,
                'most_random': consts.string.type.STRING,
                'most_history': consts.string.type.STRING,
                'range_lower': consts.string.type.STRING,
                'range_upper': consts.string.type.STRING,
            },
            {
                'histories': consts.string.type.STRING,
                'datetime': consts.string.type.STRING,
                'histories_rate': consts.string.type.STRING,
                'title': consts.string.type.STRING,
                'probid': consts.string.type.STRING,
                'neutron_data': consts.string.type.STRING,
                'proton_data': consts.string.type.STRING,
                'computer_time': consts.string.type.STRING,
                'max_bank': consts.string.type.STRING,
                'computer_mcrun': consts.string.type.STRING,
                'bank_overflows': consts.string.type.STRING,
                'source_per_minute': None,
                'random_numbers': consts.string.type.STRING,
                'most_random': consts.string.type.STRING,
                'most_history': consts.string.type.STRING,
                'range_lower': consts.string.type.STRING,
                'range_upper': consts.string.type.STRING,
            },
            {
                'histories': consts.string.type.STRING,
                'datetime': consts.string.type.STRING,
                'histories_rate': consts.string.type.STRING,
                'title': consts.string.type.STRING,
                'probid': consts.string.type.STRING,
                'neutron_data': consts.string.type.STRING,
                'proton_data': consts.string.type.STRING,
                'computer_time': consts.string.type.STRING,
                'max_bank': consts.string.type.STRING,
                'computer_mcrun': consts.string.type.STRING,
                'bank_overflows': consts.string.type.STRING,
                'source_per_minute': consts.string.type.STRING,
                'random_numbers': None,
                'most_random': consts.string.type.STRING,
                'most_history': consts.string.type.STRING,
                'range_lower': consts.string.type.STRING,
                'range_upper': consts.string.type.STRING,
            },
            {
                'histories': consts.string.type.STRING,
                'datetime': consts.string.type.STRING,
                'histories_rate': consts.string.type.STRING,
                'title': consts.string.type.STRING,
                'probid': consts.string.type.STRING,
                'neutron_data': consts.string.type.STRING,
                'proton_data': consts.string.type.STRING,
                'computer_time': consts.string.type.STRING,
                'max_bank': consts.string.type.STRING,
                'computer_mcrun': consts.string.type.STRING,
                'bank_overflows': consts.string.type.STRING,
                'source_per_minute': consts.string.type.STRING,
                'random_numbers': consts.string.type.STRING,
                'most_random': None,
                'most_history': consts.string.type.STRING,
                'range_lower': consts.string.type.STRING,
                'range_upper': consts.string.type.STRING,
            },
            {
                'histories': consts.string.type.STRING,
                'datetime': consts.string.type.STRING,
                'histories_rate': consts.string.type.STRING,
                'title': consts.string.type.STRING,
                'probid': consts.string.type.STRING,
                'neutron_data': consts.string.type.STRING,
                'proton_data': consts.string.type.STRING,
                'computer_time': consts.string.type.STRING,
                'max_bank': consts.string.type.STRING,
                'computer_mcrun': consts.string.type.STRING,
                'bank_overflows': consts.string.type.STRING,
                'source_per_minute': consts.string.type.STRING,
                'random_numbers': consts.string.type.STRING,
                'most_random': consts.string.type.STRING,
                'most_history': None,
                'range_lower': consts.string.type.STRING,
                'range_upper': consts.string.type.STRING,
            },
            {
                'histories': consts.string.type.STRING,
                'datetime': consts.string.type.STRING,
                'histories_rate': consts.string.type.STRING,
                'title': consts.string.type.STRING,
                'probid': consts.string.type.STRING,
                'neutron_data': consts.string.type.STRING,
                'proton_data': consts.string.type.STRING,
                'computer_time': consts.string.type.STRING,
                'max_bank': consts.string.type.STRING,
                'computer_mcrun': consts.string.type.STRING,
                'bank_overflows': consts.string.type.STRING,
                'source_per_minute': consts.string.type.STRING,
                'random_numbers': consts.string.type.STRING,
                'most_random': consts.string.type.STRING,
                'most_history': consts.string.type.STRING,
                'range_lower': None,
                'range_upper': consts.string.type.STRING,
            },
            {
                'histories': consts.string.type.STRING,
                'datetime': consts.string.type.STRING,
                'histories_rate': consts.string.type.STRING,
                'title': consts.string.type.STRING,
                'probid': consts.string.type.STRING,
                'neutron_data': consts.string.type.STRING,
                'proton_data': consts.string.type.STRING,
                'computer_time': consts.string.type.STRING,
                'max_bank': consts.string.type.STRING,
                'computer_mcrun': consts.string.type.STRING,
                'bank_overflows': consts.string.type.STRING,
                'source_per_minute': consts.string.type.STRING,
                'random_numbers': consts.string.type.STRING,
                'most_random': consts.string.type.STRING,
                'most_history': consts.string.type.STRING,
                'range_lower': consts.string.type.STRING,
                'range_upper': None,
            },
        ]

    class Test_Mcnp(classes.Test_Mcnp):
        element = pymcnp.outp.ProblemSummary
        EXAMPLES_VALID = [consts.string.outp.PROBLEM_SUMMARY]
        EXAMPLES_INVALID = [
            'hello',
        ]
