import pymcnp
from ... import consts
from ... import classes


class Test_TallyNps1:
    class Test_Init(classes.Test_Init):
        element = pymcnp.outp.TallyNps1
        EXAMPLES_VALID = [
            {
                'tally': consts.string.type.STRING,
                'nps': consts.string.type.STRING,
                'tally_type': consts.string.type.STRING,
                'particles': consts.string.type.STRING,
                'subtallies': consts.string.type.STRING,
                'stats_desired': consts.string.type.STRING,
                'stats_observed': consts.string.type.STRING,
                'stats_passed': consts.string.type.STRING,
                'asymmetric_interval': consts.string.type.STRING,
                'symmetric_interval': consts.string.type.STRING,
            },
        ]
        EXAMPLES_INVALID = [
            {
                'tally': None,
                'nps': consts.string.type.STRING,
                'tally_type': consts.string.type.STRING,
                'particles': consts.string.type.STRING,
                'subtallies': consts.string.type.STRING,
                'stats_desired': consts.string.type.STRING,
                'stats_observed': consts.string.type.STRING,
                'stats_passed': consts.string.type.STRING,
                'asymmetric_interval': consts.string.type.STRING,
                'symmetric_interval': consts.string.type.STRING,
            },
            {
                'tally': consts.string.type.STRING,
                'nps': None,
                'tally_type': consts.string.type.STRING,
                'particles': consts.string.type.STRING,
                'subtallies': consts.string.type.STRING,
                'stats_desired': consts.string.type.STRING,
                'stats_observed': consts.string.type.STRING,
                'stats_passed': consts.string.type.STRING,
                'asymmetric_interval': consts.string.type.STRING,
                'symmetric_interval': consts.string.type.STRING,
            },
            {
                'tally': consts.string.type.STRING,
                'nps': consts.string.type.STRING,
                'tally_type': None,
                'particles': consts.string.type.STRING,
                'subtallies': consts.string.type.STRING,
                'stats_desired': consts.string.type.STRING,
                'stats_observed': consts.string.type.STRING,
                'stats_passed': consts.string.type.STRING,
                'asymmetric_interval': consts.string.type.STRING,
                'symmetric_interval': consts.string.type.STRING,
            },
            {
                'tally': consts.string.type.STRING,
                'nps': consts.string.type.STRING,
                'tally_type': consts.string.type.STRING,
                'particles': None,
                'subtallies': consts.string.type.STRING,
                'stats_desired': consts.string.type.STRING,
                'stats_observed': consts.string.type.STRING,
                'stats_passed': consts.string.type.STRING,
                'asymmetric_interval': consts.string.type.STRING,
                'symmetric_interval': consts.string.type.STRING,
            },
            {
                'tally': consts.string.type.STRING,
                'nps': consts.string.type.STRING,
                'tally_type': consts.string.type.STRING,
                'particles': consts.string.type.STRING,
                'subtallies': None,
                'stats_desired': consts.string.type.STRING,
                'stats_observed': consts.string.type.STRING,
                'stats_passed': consts.string.type.STRING,
                'asymmetric_interval': consts.string.type.STRING,
                'symmetric_interval': consts.string.type.STRING,
            },
            {
                'tally': consts.string.type.STRING,
                'nps': consts.string.type.STRING,
                'tally_type': consts.string.type.STRING,
                'particles': consts.string.type.STRING,
                'subtallies': consts.string.type.STRING,
                'stats_desired': None,
                'stats_observed': consts.string.type.STRING,
                'stats_passed': consts.string.type.STRING,
                'asymmetric_interval': consts.string.type.STRING,
                'symmetric_interval': consts.string.type.STRING,
            },
            {
                'tally': consts.string.type.STRING,
                'nps': consts.string.type.STRING,
                'tally_type': consts.string.type.STRING,
                'particles': consts.string.type.STRING,
                'subtallies': consts.string.type.STRING,
                'stats_desired': consts.string.type.STRING,
                'stats_observed': None,
                'stats_passed': consts.string.type.STRING,
                'asymmetric_interval': consts.string.type.STRING,
                'symmetric_interval': consts.string.type.STRING,
            },
            {
                'tally': consts.string.type.STRING,
                'nps': consts.string.type.STRING,
                'tally_type': consts.string.type.STRING,
                'particles': consts.string.type.STRING,
                'subtallies': consts.string.type.STRING,
                'stats_desired': consts.string.type.STRING,
                'stats_observed': consts.string.type.STRING,
                'stats_passed': None,
                'asymmetric_interval': consts.string.type.STRING,
                'symmetric_interval': consts.string.type.STRING,
            },
            {
                'tally': consts.string.type.STRING,
                'nps': consts.string.type.STRING,
                'tally_type': consts.string.type.STRING,
                'particles': consts.string.type.STRING,
                'subtallies': consts.string.type.STRING,
                'stats_desired': consts.string.type.STRING,
                'stats_observed': consts.string.type.STRING,
                'stats_passed': consts.string.type.STRING,
                'asymmetric_interval': None,
                'symmetric_interval': consts.string.type.STRING,
            },
            {
                'tally': consts.string.type.STRING,
                'nps': consts.string.type.STRING,
                'tally_type': consts.string.type.STRING,
                'particles': consts.string.type.STRING,
                'subtallies': consts.string.type.STRING,
                'stats_desired': consts.string.type.STRING,
                'stats_observed': consts.string.type.STRING,
                'stats_passed': consts.string.type.STRING,
                'asymmetric_interval': consts.string.type.STRING,
                'symmetric_interval': None,
            },
        ]

    class Test_Mcnp(classes.Test_Mcnp):
        element = pymcnp.outp.TallyNps1
        EXAMPLES_VALID = [consts.string.outp.TALLY_NPS_1]
        EXAMPLES_INVALID = [
            'hello',
        ]
