"""
``run`` contains functions for interacting with MCNP.

``run`` packages the ``Run`` utility class, providing an object-oriented, 
importable interface for running MCNP INP files.
"""


import os
import sys

import docopt

from .. import files
from . import _io
from . import _save


DEFAULT_NPP = 1000
DEFAULT_NPSMG = 1


class Run:
    """
    ``Run`` encapsulates methods for running MCNP INP files.

    ``Run`` provides utilities for executing MCNP simulations concurrently or
    in parallel. This class also stores the inputs and outputs of MNPC runs
    in timestamped directories.

    Attributes:
        inp: PyMCNP INP object to run.
        path: Path to directory to store run inputs and outputs.
        command: Terminal command to execute.
    """

    def __init__(self, inp: files.inp.Inp, path: str = ".", command: str = "mcnp"):
        """
        ``__init__`` initalizes ``Run``.

        Parameters:
             path: Path to directory to store run inputs and outputs.
            command: Terminal command to execute.
        """

        self.path: final[str] = path
        self.command: final[str] = command
        self.inp: final[files.inp.Inp] = inp

    def run_single(self) -> str:
        """
        ``run_single`` runs MCNP INP files.

        ``run_single`` creates a directory to store a copy of the input file
        passed to MCNP and the outputfiles generated by MCNP.

        Returns:
            Path to run directory.
        """

        timestamp = _io.get_timestamp()

        directory_path = f"{self.path}/pymcnp-run-{timestamp}"
        os.mkdir(directory_path)

        inp_path = f"{directory_path}/pymcnp-inp-{timestamp}.inp"
        self.inp.to_mcnp_file(inp_path)

        outp_path = f"{directory_path}/pymcnp-outp-{timestamp}.outp"
        os.system(f"{self.command} I={inp_path} O={outp_path}")

        return directory_path

    def run_parallel(self, count: int) -> str:
        """
        ``run_parallel`` runs MCNP INP files in parallel.

        ``run_parallel`` creates a directory to store a copy of the input file
        passed to MCNP and directories containing each seperate run output
        files. This method works by dividing the INP particles histories and
        running the MCNP simulation many times concurrently.

        Parameters:
            count: Number of parallel threads to run.

        Returns:
            Path to run directory.
        """

        if count <= 0:
            _io.error("Invalid Count.")

        timestamp = _io.get_timestamp()

        directory_path = f"{self.path}/pymcnp-runs-{timestamp}"
        os.mkdir(directory_path)

        if "nps" in self.inp.data:
            self.inp.data["nps"].npp //= count
        else:
            self.inp.data.append(inp.Nps(DEFAULT_NPP // count, DEFAULT_NPSMG))

        inp_path = f"{directory_path}/pymcnp-inp-{timestamp}.inp"
        self.inp.to_mcnp_file(inp_path)

        outp_paths = []
        for n in range(0, count):
            subdirectory_path = f"{directory_path}/pymcnp-run-{n}"
            os.mkdir(subdirectory_path)

            outp_path = f"{subdirectory_path}/pymcnp-outp-{n}.outp"
            outp_paths.append(outp_path)

        os.system(f"parallel {self.command} ::: {' '.join(f'\"I={inp_path} O={outp_path}\"' for outp_path in outp_paths)}")

        return directory_path


PYMCNP_RUN_DOC = f"""
Usage:
    pymcnp run ( [--object] <alias> | --file <file> ) [ --parallel=<threads> ]

Options:
    -o --object                   Run from PyMCNP objects.
    -f --file                     Run from filename.
    -p --parallel=<threads>       Run files in parallel on <threads> threads.
"""


def main(argv: list[str] = sys.argv[1:]) -> None:
    """
    ``main`` executes the ``pymcnp run`` command.

    ``main`` processes the given command line arguments, and it runs either INP
    files or PyMCNP aliased INP files single or in parallel.

    Parameters:
        argv: Tokenized list of CLI arguments.
    """

    args = docopt.docopt(PYMCNP_RUN_DOC, argv=argv)

    if args["<alias>"] is not None:
        # Running aliased PyMCNP object.
        aliases = _save.Save.get_save()
        run = Run(aliases[args["<alias>"]][1], path=".")
    elif args["<file>"] is not None:
        # Running from INP files.
        inp = files.inp.Inp.from_mcnp_file(args["<file>"])
        run = Run(inp, path=".")

    if args["--parallel"] is not None:
        run.run_parallel(int(args["--parallel"][1:]))
    else:
        run.run_single()
