import pymcnp
from .... import consts
from .... import classes


class Test_Sq:
    class Test_Init(classes.Test_Init):
        element = pymcnp.inp.surface.Sq
        EXAMPLES_VALID = [
            {
                'a': consts.string.type.REAL,
                'b': consts.string.type.REAL,
                'c': consts.string.type.REAL,
                'd': consts.string.type.REAL,
                'e': consts.string.type.REAL,
                'f': consts.string.type.REAL,
                'g': consts.string.type.REAL,
                'x': consts.string.type.REAL,
                'y': consts.string.type.REAL,
                'z': consts.string.type.REAL,
            },
            {'a': 3.1, 'b': 3.1, 'c': 3.1, 'd': 3.1, 'e': 3.1, 'f': 3.1, 'g': 3.1, 'x': 3.1, 'y': 3.1, 'z': 3.1},
            {
                'a': consts.ast.type.REAL,
                'b': consts.ast.type.REAL,
                'c': consts.ast.type.REAL,
                'd': consts.ast.type.REAL,
                'e': consts.ast.type.REAL,
                'f': consts.ast.type.REAL,
                'g': consts.ast.type.REAL,
                'x': consts.ast.type.REAL,
                'y': consts.ast.type.REAL,
                'z': consts.ast.type.REAL,
            },
        ]
        EXAMPLES_INVALID = [
            {
                'a': None,
                'b': consts.string.type.REAL,
                'c': consts.string.type.REAL,
                'd': consts.string.type.REAL,
                'e': consts.string.type.REAL,
                'f': consts.string.type.REAL,
                'g': consts.string.type.REAL,
                'x': consts.string.type.REAL,
                'y': consts.string.type.REAL,
                'z': consts.string.type.REAL,
            },
            {
                'a': consts.string.type.REAL,
                'b': None,
                'c': consts.string.type.REAL,
                'd': consts.string.type.REAL,
                'e': consts.string.type.REAL,
                'f': consts.string.type.REAL,
                'g': consts.string.type.REAL,
                'x': consts.string.type.REAL,
                'y': consts.string.type.REAL,
                'z': consts.string.type.REAL,
            },
            {
                'a': consts.string.type.REAL,
                'b': consts.string.type.REAL,
                'c': None,
                'd': consts.string.type.REAL,
                'e': consts.string.type.REAL,
                'f': consts.string.type.REAL,
                'g': consts.string.type.REAL,
                'x': consts.string.type.REAL,
                'y': consts.string.type.REAL,
                'z': consts.string.type.REAL,
            },
            {
                'a': consts.string.type.REAL,
                'b': consts.string.type.REAL,
                'c': consts.string.type.REAL,
                'd': None,
                'e': consts.string.type.REAL,
                'f': consts.string.type.REAL,
                'g': consts.string.type.REAL,
                'x': consts.string.type.REAL,
                'y': consts.string.type.REAL,
                'z': consts.string.type.REAL,
            },
            {
                'a': consts.string.type.REAL,
                'b': consts.string.type.REAL,
                'c': consts.string.type.REAL,
                'd': consts.string.type.REAL,
                'e': None,
                'f': consts.string.type.REAL,
                'g': consts.string.type.REAL,
                'x': consts.string.type.REAL,
                'y': consts.string.type.REAL,
                'z': consts.string.type.REAL,
            },
            {
                'a': consts.string.type.REAL,
                'b': consts.string.type.REAL,
                'c': consts.string.type.REAL,
                'd': consts.string.type.REAL,
                'e': consts.string.type.REAL,
                'f': None,
                'g': consts.string.type.REAL,
                'x': consts.string.type.REAL,
                'y': consts.string.type.REAL,
                'z': consts.string.type.REAL,
            },
            {
                'a': consts.string.type.REAL,
                'b': consts.string.type.REAL,
                'c': consts.string.type.REAL,
                'd': consts.string.type.REAL,
                'e': consts.string.type.REAL,
                'f': consts.string.type.REAL,
                'g': None,
                'x': consts.string.type.REAL,
                'y': consts.string.type.REAL,
                'z': consts.string.type.REAL,
            },
            {
                'a': consts.string.type.REAL,
                'b': consts.string.type.REAL,
                'c': consts.string.type.REAL,
                'd': consts.string.type.REAL,
                'e': consts.string.type.REAL,
                'f': consts.string.type.REAL,
                'g': consts.string.type.REAL,
                'x': None,
                'y': consts.string.type.REAL,
                'z': consts.string.type.REAL,
            },
            {
                'a': consts.string.type.REAL,
                'b': consts.string.type.REAL,
                'c': consts.string.type.REAL,
                'd': consts.string.type.REAL,
                'e': consts.string.type.REAL,
                'f': consts.string.type.REAL,
                'g': consts.string.type.REAL,
                'x': consts.string.type.REAL,
                'y': None,
                'z': consts.string.type.REAL,
            },
            {
                'a': consts.string.type.REAL,
                'b': consts.string.type.REAL,
                'c': consts.string.type.REAL,
                'd': consts.string.type.REAL,
                'e': consts.string.type.REAL,
                'f': consts.string.type.REAL,
                'g': consts.string.type.REAL,
                'x': consts.string.type.REAL,
                'y': consts.string.type.REAL,
                'z': None,
            },
        ]

    class Test_Mcnp(classes.Test_Mcnp):
        element = pymcnp.inp.surface.Sq
        EXAMPLES_VALID = [consts.string.inp.surface.SQ]
        EXAMPLES_INVALID = ['hello']
