import pymcnp
from .... import consts
from .... import classes


class Test_Wed:
    class Test_Init(classes.Test_Init):
        element = pymcnp.inp.surface.Wed
        EXAMPLES_VALID = [
            {
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'v1x': consts.string.types.REAL,
                'v1y': consts.string.types.REAL,
                'v1z': consts.string.types.REAL,
                'v2x': consts.string.types.REAL,
                'v2y': consts.string.types.REAL,
                'v2z': consts.string.types.REAL,
                'v3x': consts.string.types.REAL,
                'v3y': consts.string.types.REAL,
                'v3z': consts.string.types.REAL,
            },
            {'vx': 3.1, 'vy': 3.1, 'vz': 3.1, 'v1x': 3.1, 'v1y': 3.1, 'v1z': 3.1, 'v2x': 3.1, 'v2y': 3.1, 'v2z': 3.1, 'v3x': 3.1, 'v3y': 3.1, 'v3z': 3.1},
            {
                'vx': consts.ast.types.REAL,
                'vy': consts.ast.types.REAL,
                'vz': consts.ast.types.REAL,
                'v1x': consts.ast.types.REAL,
                'v1y': consts.ast.types.REAL,
                'v1z': consts.ast.types.REAL,
                'v2x': consts.ast.types.REAL,
                'v2y': consts.ast.types.REAL,
                'v2z': consts.ast.types.REAL,
                'v3x': consts.ast.types.REAL,
                'v3y': consts.ast.types.REAL,
                'v3z': consts.ast.types.REAL,
            },
        ]
        EXAMPLES_INVALID = [
            {
                'vx': None,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'v1x': consts.string.types.REAL,
                'v1y': consts.string.types.REAL,
                'v1z': consts.string.types.REAL,
                'v2x': consts.string.types.REAL,
                'v2y': consts.string.types.REAL,
                'v2z': consts.string.types.REAL,
                'v3x': consts.string.types.REAL,
                'v3y': consts.string.types.REAL,
                'v3z': consts.string.types.REAL,
            },
            {
                'vx': consts.string.types.REAL,
                'vy': None,
                'vz': consts.string.types.REAL,
                'v1x': consts.string.types.REAL,
                'v1y': consts.string.types.REAL,
                'v1z': consts.string.types.REAL,
                'v2x': consts.string.types.REAL,
                'v2y': consts.string.types.REAL,
                'v2z': consts.string.types.REAL,
                'v3x': consts.string.types.REAL,
                'v3y': consts.string.types.REAL,
                'v3z': consts.string.types.REAL,
            },
            {
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': None,
                'v1x': consts.string.types.REAL,
                'v1y': consts.string.types.REAL,
                'v1z': consts.string.types.REAL,
                'v2x': consts.string.types.REAL,
                'v2y': consts.string.types.REAL,
                'v2z': consts.string.types.REAL,
                'v3x': consts.string.types.REAL,
                'v3y': consts.string.types.REAL,
                'v3z': consts.string.types.REAL,
            },
            {
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'v1x': None,
                'v1y': consts.string.types.REAL,
                'v1z': consts.string.types.REAL,
                'v2x': consts.string.types.REAL,
                'v2y': consts.string.types.REAL,
                'v2z': consts.string.types.REAL,
                'v3x': consts.string.types.REAL,
                'v3y': consts.string.types.REAL,
                'v3z': consts.string.types.REAL,
            },
            {
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'v1x': consts.string.types.REAL,
                'v1y': None,
                'v1z': consts.string.types.REAL,
                'v2x': consts.string.types.REAL,
                'v2y': consts.string.types.REAL,
                'v2z': consts.string.types.REAL,
                'v3x': consts.string.types.REAL,
                'v3y': consts.string.types.REAL,
                'v3z': consts.string.types.REAL,
            },
            {
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'v1x': consts.string.types.REAL,
                'v1y': consts.string.types.REAL,
                'v1z': None,
                'v2x': consts.string.types.REAL,
                'v2y': consts.string.types.REAL,
                'v2z': consts.string.types.REAL,
                'v3x': consts.string.types.REAL,
                'v3y': consts.string.types.REAL,
                'v3z': consts.string.types.REAL,
            },
            {
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'v1x': consts.string.types.REAL,
                'v1y': consts.string.types.REAL,
                'v1z': consts.string.types.REAL,
                'v2x': None,
                'v2y': consts.string.types.REAL,
                'v2z': consts.string.types.REAL,
                'v3x': consts.string.types.REAL,
                'v3y': consts.string.types.REAL,
                'v3z': consts.string.types.REAL,
            },
            {
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'v1x': consts.string.types.REAL,
                'v1y': consts.string.types.REAL,
                'v1z': consts.string.types.REAL,
                'v2x': consts.string.types.REAL,
                'v2y': None,
                'v2z': consts.string.types.REAL,
                'v3x': consts.string.types.REAL,
                'v3y': consts.string.types.REAL,
                'v3z': consts.string.types.REAL,
            },
            {
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'v1x': consts.string.types.REAL,
                'v1y': consts.string.types.REAL,
                'v1z': consts.string.types.REAL,
                'v2x': consts.string.types.REAL,
                'v2y': consts.string.types.REAL,
                'v2z': None,
                'v3x': consts.string.types.REAL,
                'v3y': consts.string.types.REAL,
                'v3z': consts.string.types.REAL,
            },
            {
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'v1x': consts.string.types.REAL,
                'v1y': consts.string.types.REAL,
                'v1z': consts.string.types.REAL,
                'v2x': consts.string.types.REAL,
                'v2y': consts.string.types.REAL,
                'v2z': consts.string.types.REAL,
                'v3x': None,
                'v3y': consts.string.types.REAL,
                'v3z': consts.string.types.REAL,
            },
            {
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'v1x': consts.string.types.REAL,
                'v1y': consts.string.types.REAL,
                'v1z': consts.string.types.REAL,
                'v2x': consts.string.types.REAL,
                'v2y': consts.string.types.REAL,
                'v2z': consts.string.types.REAL,
                'v3x': consts.string.types.REAL,
                'v3y': None,
                'v3z': consts.string.types.REAL,
            },
            {
                'vx': consts.string.types.REAL,
                'vy': consts.string.types.REAL,
                'vz': consts.string.types.REAL,
                'v1x': consts.string.types.REAL,
                'v1y': consts.string.types.REAL,
                'v1z': consts.string.types.REAL,
                'v2x': consts.string.types.REAL,
                'v2y': consts.string.types.REAL,
                'v2z': consts.string.types.REAL,
                'v3x': consts.string.types.REAL,
                'v3y': consts.string.types.REAL,
                'v3z': None,
            },
        ]

    class Test_Mcnp(classes.Test_Mcnp):
        element = pymcnp.inp.surface.Wed
        EXAMPLES_VALID = [consts.string.inp.surface.WED]
        EXAMPLES_INVALID = ['hello']

    class Test_Show(classes.Test_Show):
        element = pymcnp.inp.surface.Wed
        EXAMPLES = [consts.string.inp.surface.WED]
