import pymcnp
from .... import consts
from .... import classes


class Test_Rec:
    class Test_Init(classes.Test_Init):
        element = pymcnp.inp.surface.Rec
        EXAMPLES_VALID = [
            {
                'vx': consts.ast.type.REAL,
                'vy': consts.ast.type.REAL,
                'vz': consts.ast.type.REAL,
                'hx': consts.ast.type.REAL,
                'hy': consts.ast.type.REAL,
                'hz': consts.ast.type.REAL,
                'v1x': consts.ast.type.REAL,
                'v1y': consts.ast.type.REAL,
                'v1z': consts.ast.type.REAL,
                'v2x': consts.ast.type.REAL,
                'v2y': consts.ast.type.REAL,
                'v2z': consts.ast.type.REAL,
            },
            {
                'vx': consts.ast.type.REAL,
                'vy': consts.ast.type.REAL,
                'vz': consts.ast.type.REAL,
                'hx': consts.ast.type.REAL,
                'hy': consts.ast.type.REAL,
                'hz': consts.ast.type.REAL,
                'v1x': consts.ast.type.REAL,
                'v1y': consts.ast.type.REAL,
                'v1z': consts.ast.type.REAL,
                'v2x': consts.ast.type.REAL,
                'v2y': None,
                'v2z': consts.ast.type.REAL,
            },
            {
                'vx': consts.ast.type.REAL,
                'vy': consts.ast.type.REAL,
                'vz': consts.ast.type.REAL,
                'hx': consts.ast.type.REAL,
                'hy': consts.ast.type.REAL,
                'hz': consts.ast.type.REAL,
                'v1x': consts.ast.type.REAL,
                'v1y': consts.ast.type.REAL,
                'v1z': consts.ast.type.REAL,
                'v2x': consts.ast.type.REAL,
                'v2y': consts.ast.type.REAL,
                'v2z': None,
            },
        ]
        EXAMPLES_INVALID = [
            {
                'vx': None,
                'vy': consts.ast.type.REAL,
                'vz': consts.ast.type.REAL,
                'hx': consts.ast.type.REAL,
                'hy': consts.ast.type.REAL,
                'hz': consts.ast.type.REAL,
                'v1x': consts.ast.type.REAL,
                'v1y': consts.ast.type.REAL,
                'v1z': consts.ast.type.REAL,
                'v2x': consts.ast.type.REAL,
                'v2y': consts.ast.type.REAL,
                'v2z': consts.ast.type.REAL,
            },
            {
                'vx': consts.ast.type.REAL,
                'vy': None,
                'vz': consts.ast.type.REAL,
                'hx': consts.ast.type.REAL,
                'hy': consts.ast.type.REAL,
                'hz': consts.ast.type.REAL,
                'v1x': consts.ast.type.REAL,
                'v1y': consts.ast.type.REAL,
                'v1z': consts.ast.type.REAL,
                'v2x': consts.ast.type.REAL,
                'v2y': consts.ast.type.REAL,
                'v2z': consts.ast.type.REAL,
            },
            {
                'vx': consts.ast.type.REAL,
                'vy': consts.ast.type.REAL,
                'vz': None,
                'hx': consts.ast.type.REAL,
                'hy': consts.ast.type.REAL,
                'hz': consts.ast.type.REAL,
                'v1x': consts.ast.type.REAL,
                'v1y': consts.ast.type.REAL,
                'v1z': consts.ast.type.REAL,
                'v2x': consts.ast.type.REAL,
                'v2y': consts.ast.type.REAL,
                'v2z': consts.ast.type.REAL,
            },
            {
                'vx': consts.ast.type.REAL,
                'vy': consts.ast.type.REAL,
                'vz': consts.ast.type.REAL,
                'hx': None,
                'hy': consts.ast.type.REAL,
                'hz': consts.ast.type.REAL,
                'v1x': consts.ast.type.REAL,
                'v1y': consts.ast.type.REAL,
                'v1z': consts.ast.type.REAL,
                'v2x': consts.ast.type.REAL,
                'v2y': consts.ast.type.REAL,
                'v2z': consts.ast.type.REAL,
            },
            {
                'vx': consts.ast.type.REAL,
                'vy': consts.ast.type.REAL,
                'vz': consts.ast.type.REAL,
                'hx': consts.ast.type.REAL,
                'hy': None,
                'hz': consts.ast.type.REAL,
                'v1x': consts.ast.type.REAL,
                'v1y': consts.ast.type.REAL,
                'v1z': consts.ast.type.REAL,
                'v2x': consts.ast.type.REAL,
                'v2y': consts.ast.type.REAL,
                'v2z': consts.ast.type.REAL,
            },
            {
                'vx': consts.ast.type.REAL,
                'vy': consts.ast.type.REAL,
                'vz': consts.ast.type.REAL,
                'hx': consts.ast.type.REAL,
                'hy': consts.ast.type.REAL,
                'hz': None,
                'v1x': consts.ast.type.REAL,
                'v1y': consts.ast.type.REAL,
                'v1z': consts.ast.type.REAL,
                'v2x': consts.ast.type.REAL,
                'v2y': consts.ast.type.REAL,
                'v2z': consts.ast.type.REAL,
            },
            {
                'vx': consts.ast.type.REAL,
                'vy': consts.ast.type.REAL,
                'vz': consts.ast.type.REAL,
                'hx': consts.ast.type.REAL,
                'hy': consts.ast.type.REAL,
                'hz': consts.ast.type.REAL,
                'v1x': None,
                'v1y': consts.ast.type.REAL,
                'v1z': consts.ast.type.REAL,
                'v2x': consts.ast.type.REAL,
                'v2y': consts.ast.type.REAL,
                'v2z': consts.ast.type.REAL,
            },
            {
                'vx': consts.ast.type.REAL,
                'vy': consts.ast.type.REAL,
                'vz': consts.ast.type.REAL,
                'hx': consts.ast.type.REAL,
                'hy': consts.ast.type.REAL,
                'hz': consts.ast.type.REAL,
                'v1x': consts.ast.type.REAL,
                'v1y': None,
                'v1z': consts.ast.type.REAL,
                'v2x': consts.ast.type.REAL,
                'v2y': consts.ast.type.REAL,
                'v2z': consts.ast.type.REAL,
            },
            {
                'vx': consts.ast.type.REAL,
                'vy': consts.ast.type.REAL,
                'vz': consts.ast.type.REAL,
                'hx': consts.ast.type.REAL,
                'hy': consts.ast.type.REAL,
                'hz': consts.ast.type.REAL,
                'v1x': consts.ast.type.REAL,
                'v1y': consts.ast.type.REAL,
                'v1z': None,
                'v2x': consts.ast.type.REAL,
                'v2y': consts.ast.type.REAL,
                'v2z': consts.ast.type.REAL,
            },
            {
                'vx': consts.ast.type.REAL,
                'vy': consts.ast.type.REAL,
                'vz': consts.ast.type.REAL,
                'hx': consts.ast.type.REAL,
                'hy': consts.ast.type.REAL,
                'hz': consts.ast.type.REAL,
                'v1x': consts.ast.type.REAL,
                'v1y': consts.ast.type.REAL,
                'v1z': consts.ast.type.REAL,
                'v2x': None,
                'v2y': consts.ast.type.REAL,
                'v2z': consts.ast.type.REAL,
            },
        ]

    class Test_Mcnp(classes.Test_Mcnp):
        element = pymcnp.inp.surface.Rec
        EXAMPLES_VALID = [consts.string.inp.surface.REC]
        EXAMPLES_INVALID = ['hello']

    class Test_Draw(classes.Test_Draw):
        element = pymcnp.inp.surface.Rec
        EXAMPLES = [consts.string.inp.surface.REC]


class Test_RecBuilder:
    class TestBuild(classes.Test_Build):
        element = pymcnp.inp.surface.RecBuilder
        EXAMPLES_VALID = [
            {
                'vx': consts.string.type.REAL,
                'vy': consts.string.type.REAL,
                'vz': consts.string.type.REAL,
                'hx': consts.string.type.REAL,
                'hy': consts.string.type.REAL,
                'hz': consts.string.type.REAL,
                'v1x': consts.string.type.REAL,
                'v1y': consts.string.type.REAL,
                'v1z': consts.string.type.REAL,
                'v2x': consts.string.type.REAL,
                'v2y': consts.string.type.REAL,
                'v2z': consts.string.type.REAL,
            },
            {'vx': 3.1, 'vy': 3.1, 'vz': 3.1, 'hx': 3.1, 'hy': 3.1, 'hz': 3.1, 'v1x': 3.1, 'v1y': 3.1, 'v1z': 3.1, 'v2x': 3.1, 'v2y': 3.1, 'v2z': 3.1},
            {
                'vx': consts.ast.type.REAL,
                'vy': consts.ast.type.REAL,
                'vz': consts.ast.type.REAL,
                'hx': consts.ast.type.REAL,
                'hy': consts.ast.type.REAL,
                'hz': consts.ast.type.REAL,
                'v1x': consts.ast.type.REAL,
                'v1y': consts.ast.type.REAL,
                'v1z': consts.ast.type.REAL,
                'v2x': consts.ast.type.REAL,
                'v2y': consts.ast.type.REAL,
                'v2z': consts.ast.type.REAL,
            },
            {
                'vx': consts.string.type.REAL,
                'vy': consts.string.type.REAL,
                'vz': consts.string.type.REAL,
                'hx': consts.string.type.REAL,
                'hy': consts.string.type.REAL,
                'hz': consts.string.type.REAL,
                'v1x': consts.string.type.REAL,
                'v1y': consts.string.type.REAL,
                'v1z': consts.string.type.REAL,
                'v2x': consts.string.type.REAL,
                'v2y': None,
                'v2z': consts.string.type.REAL,
            },
            {
                'vx': consts.string.type.REAL,
                'vy': consts.string.type.REAL,
                'vz': consts.string.type.REAL,
                'hx': consts.string.type.REAL,
                'hy': consts.string.type.REAL,
                'hz': consts.string.type.REAL,
                'v1x': consts.string.type.REAL,
                'v1y': consts.string.type.REAL,
                'v1z': consts.string.type.REAL,
                'v2x': consts.string.type.REAL,
                'v2y': consts.string.type.REAL,
                'v2z': None,
            },
        ]
        EXAMPLES_INVALID = [
            {
                'vx': None,
                'vy': consts.string.type.REAL,
                'vz': consts.string.type.REAL,
                'hx': consts.string.type.REAL,
                'hy': consts.string.type.REAL,
                'hz': consts.string.type.REAL,
                'v1x': consts.string.type.REAL,
                'v1y': consts.string.type.REAL,
                'v1z': consts.string.type.REAL,
                'v2x': consts.string.type.REAL,
                'v2y': consts.string.type.REAL,
                'v2z': consts.string.type.REAL,
            },
            {
                'vx': consts.string.type.REAL,
                'vy': None,
                'vz': consts.string.type.REAL,
                'hx': consts.string.type.REAL,
                'hy': consts.string.type.REAL,
                'hz': consts.string.type.REAL,
                'v1x': consts.string.type.REAL,
                'v1y': consts.string.type.REAL,
                'v1z': consts.string.type.REAL,
                'v2x': consts.string.type.REAL,
                'v2y': consts.string.type.REAL,
                'v2z': consts.string.type.REAL,
            },
            {
                'vx': consts.string.type.REAL,
                'vy': consts.string.type.REAL,
                'vz': None,
                'hx': consts.string.type.REAL,
                'hy': consts.string.type.REAL,
                'hz': consts.string.type.REAL,
                'v1x': consts.string.type.REAL,
                'v1y': consts.string.type.REAL,
                'v1z': consts.string.type.REAL,
                'v2x': consts.string.type.REAL,
                'v2y': consts.string.type.REAL,
                'v2z': consts.string.type.REAL,
            },
            {
                'vx': consts.string.type.REAL,
                'vy': consts.string.type.REAL,
                'vz': consts.string.type.REAL,
                'hx': None,
                'hy': consts.string.type.REAL,
                'hz': consts.string.type.REAL,
                'v1x': consts.string.type.REAL,
                'v1y': consts.string.type.REAL,
                'v1z': consts.string.type.REAL,
                'v2x': consts.string.type.REAL,
                'v2y': consts.string.type.REAL,
                'v2z': consts.string.type.REAL,
            },
            {
                'vx': consts.string.type.REAL,
                'vy': consts.string.type.REAL,
                'vz': consts.string.type.REAL,
                'hx': consts.string.type.REAL,
                'hy': None,
                'hz': consts.string.type.REAL,
                'v1x': consts.string.type.REAL,
                'v1y': consts.string.type.REAL,
                'v1z': consts.string.type.REAL,
                'v2x': consts.string.type.REAL,
                'v2y': consts.string.type.REAL,
                'v2z': consts.string.type.REAL,
            },
            {
                'vx': consts.string.type.REAL,
                'vy': consts.string.type.REAL,
                'vz': consts.string.type.REAL,
                'hx': consts.string.type.REAL,
                'hy': consts.string.type.REAL,
                'hz': None,
                'v1x': consts.string.type.REAL,
                'v1y': consts.string.type.REAL,
                'v1z': consts.string.type.REAL,
                'v2x': consts.string.type.REAL,
                'v2y': consts.string.type.REAL,
                'v2z': consts.string.type.REAL,
            },
            {
                'vx': consts.string.type.REAL,
                'vy': consts.string.type.REAL,
                'vz': consts.string.type.REAL,
                'hx': consts.string.type.REAL,
                'hy': consts.string.type.REAL,
                'hz': consts.string.type.REAL,
                'v1x': None,
                'v1y': consts.string.type.REAL,
                'v1z': consts.string.type.REAL,
                'v2x': consts.string.type.REAL,
                'v2y': consts.string.type.REAL,
                'v2z': consts.string.type.REAL,
            },
            {
                'vx': consts.string.type.REAL,
                'vy': consts.string.type.REAL,
                'vz': consts.string.type.REAL,
                'hx': consts.string.type.REAL,
                'hy': consts.string.type.REAL,
                'hz': consts.string.type.REAL,
                'v1x': consts.string.type.REAL,
                'v1y': None,
                'v1z': consts.string.type.REAL,
                'v2x': consts.string.type.REAL,
                'v2y': consts.string.type.REAL,
                'v2z': consts.string.type.REAL,
            },
            {
                'vx': consts.string.type.REAL,
                'vy': consts.string.type.REAL,
                'vz': consts.string.type.REAL,
                'hx': consts.string.type.REAL,
                'hy': consts.string.type.REAL,
                'hz': consts.string.type.REAL,
                'v1x': consts.string.type.REAL,
                'v1y': consts.string.type.REAL,
                'v1z': None,
                'v2x': consts.string.type.REAL,
                'v2y': consts.string.type.REAL,
                'v2z': consts.string.type.REAL,
            },
            {
                'vx': consts.string.type.REAL,
                'vy': consts.string.type.REAL,
                'vz': consts.string.type.REAL,
                'hx': consts.string.type.REAL,
                'hy': consts.string.type.REAL,
                'hz': consts.string.type.REAL,
                'v1x': consts.string.type.REAL,
                'v1y': consts.string.type.REAL,
                'v1z': consts.string.type.REAL,
                'v2x': None,
                'v2y': consts.string.type.REAL,
                'v2z': consts.string.type.REAL,
            },
        ]
