import pymcnp
from .... import consts
from .... import classes


class Test_Box:
    class Test_Init(classes.Test_Init):
        element = pymcnp.inp.surface.Box
        EXAMPLES_VALID = [
            {
                'vx': consts.string.type.REAL,
                'vy': consts.string.type.REAL,
                'vz': consts.string.type.REAL,
                'a1x': consts.string.type.REAL,
                'a1y': consts.string.type.REAL,
                'a1z': consts.string.type.REAL,
                'a2x': consts.string.type.REAL,
                'a2y': consts.string.type.REAL,
                'a2z': consts.string.type.REAL,
                'a3x': consts.string.type.REAL,
                'a3y': consts.string.type.REAL,
                'a3z': consts.string.type.REAL,
            },
            {'vx': 3.1, 'vy': 3.1, 'vz': 3.1, 'a1x': 3.1, 'a1y': 3.1, 'a1z': 3.1, 'a2x': 3.1, 'a2y': 3.1, 'a2z': 3.1, 'a3x': 3.1, 'a3y': 3.1, 'a3z': 3.1},
            {
                'vx': consts.ast.type.REAL,
                'vy': consts.ast.type.REAL,
                'vz': consts.ast.type.REAL,
                'a1x': consts.ast.type.REAL,
                'a1y': consts.ast.type.REAL,
                'a1z': consts.ast.type.REAL,
                'a2x': consts.ast.type.REAL,
                'a2y': consts.ast.type.REAL,
                'a2z': consts.ast.type.REAL,
                'a3x': consts.ast.type.REAL,
                'a3y': consts.ast.type.REAL,
                'a3z': consts.ast.type.REAL,
            },
        ]
        EXAMPLES_INVALID = [
            {
                'vx': None,
                'vy': consts.string.type.REAL,
                'vz': consts.string.type.REAL,
                'a1x': consts.string.type.REAL,
                'a1y': consts.string.type.REAL,
                'a1z': consts.string.type.REAL,
                'a2x': consts.string.type.REAL,
                'a2y': consts.string.type.REAL,
                'a2z': consts.string.type.REAL,
                'a3x': consts.string.type.REAL,
                'a3y': consts.string.type.REAL,
                'a3z': consts.string.type.REAL,
            },
            {
                'vx': consts.string.type.REAL,
                'vy': None,
                'vz': consts.string.type.REAL,
                'a1x': consts.string.type.REAL,
                'a1y': consts.string.type.REAL,
                'a1z': consts.string.type.REAL,
                'a2x': consts.string.type.REAL,
                'a2y': consts.string.type.REAL,
                'a2z': consts.string.type.REAL,
                'a3x': consts.string.type.REAL,
                'a3y': consts.string.type.REAL,
                'a3z': consts.string.type.REAL,
            },
            {
                'vx': consts.string.type.REAL,
                'vy': consts.string.type.REAL,
                'vz': None,
                'a1x': consts.string.type.REAL,
                'a1y': consts.string.type.REAL,
                'a1z': consts.string.type.REAL,
                'a2x': consts.string.type.REAL,
                'a2y': consts.string.type.REAL,
                'a2z': consts.string.type.REAL,
                'a3x': consts.string.type.REAL,
                'a3y': consts.string.type.REAL,
                'a3z': consts.string.type.REAL,
            },
            {
                'vx': consts.string.type.REAL,
                'vy': consts.string.type.REAL,
                'vz': consts.string.type.REAL,
                'a1x': None,
                'a1y': consts.string.type.REAL,
                'a1z': consts.string.type.REAL,
                'a2x': consts.string.type.REAL,
                'a2y': consts.string.type.REAL,
                'a2z': consts.string.type.REAL,
                'a3x': consts.string.type.REAL,
                'a3y': consts.string.type.REAL,
                'a3z': consts.string.type.REAL,
            },
            {
                'vx': consts.string.type.REAL,
                'vy': consts.string.type.REAL,
                'vz': consts.string.type.REAL,
                'a1x': consts.string.type.REAL,
                'a1y': None,
                'a1z': consts.string.type.REAL,
                'a2x': consts.string.type.REAL,
                'a2y': consts.string.type.REAL,
                'a2z': consts.string.type.REAL,
                'a3x': consts.string.type.REAL,
                'a3y': consts.string.type.REAL,
                'a3z': consts.string.type.REAL,
            },
            {
                'vx': consts.string.type.REAL,
                'vy': consts.string.type.REAL,
                'vz': consts.string.type.REAL,
                'a1x': consts.string.type.REAL,
                'a1y': consts.string.type.REAL,
                'a1z': None,
                'a2x': consts.string.type.REAL,
                'a2y': consts.string.type.REAL,
                'a2z': consts.string.type.REAL,
                'a3x': consts.string.type.REAL,
                'a3y': consts.string.type.REAL,
                'a3z': consts.string.type.REAL,
            },
            {
                'vx': consts.string.type.REAL,
                'vy': consts.string.type.REAL,
                'vz': consts.string.type.REAL,
                'a1x': consts.string.type.REAL,
                'a1y': consts.string.type.REAL,
                'a1z': consts.string.type.REAL,
                'a2x': None,
                'a2y': consts.string.type.REAL,
                'a2z': consts.string.type.REAL,
                'a3x': consts.string.type.REAL,
                'a3y': consts.string.type.REAL,
                'a3z': consts.string.type.REAL,
            },
            {
                'vx': consts.string.type.REAL,
                'vy': consts.string.type.REAL,
                'vz': consts.string.type.REAL,
                'a1x': consts.string.type.REAL,
                'a1y': consts.string.type.REAL,
                'a1z': consts.string.type.REAL,
                'a2x': consts.string.type.REAL,
                'a2y': None,
                'a2z': consts.string.type.REAL,
                'a3x': consts.string.type.REAL,
                'a3y': consts.string.type.REAL,
                'a3z': consts.string.type.REAL,
            },
            {
                'vx': consts.string.type.REAL,
                'vy': consts.string.type.REAL,
                'vz': consts.string.type.REAL,
                'a1x': consts.string.type.REAL,
                'a1y': consts.string.type.REAL,
                'a1z': consts.string.type.REAL,
                'a2x': consts.string.type.REAL,
                'a2y': consts.string.type.REAL,
                'a2z': None,
                'a3x': consts.string.type.REAL,
                'a3y': consts.string.type.REAL,
                'a3z': consts.string.type.REAL,
            },
            {
                'vx': consts.string.type.REAL,
                'vy': consts.string.type.REAL,
                'vz': consts.string.type.REAL,
                'a1x': consts.string.type.REAL,
                'a1y': consts.string.type.REAL,
                'a1z': consts.string.type.REAL,
                'a2x': consts.string.type.REAL,
                'a2y': consts.string.type.REAL,
                'a2z': consts.string.type.REAL,
                'a3x': None,
                'a3y': consts.string.type.REAL,
                'a3z': consts.string.type.REAL,
            },
            {
                'vx': consts.string.type.REAL,
                'vy': consts.string.type.REAL,
                'vz': consts.string.type.REAL,
                'a1x': consts.string.type.REAL,
                'a1y': consts.string.type.REAL,
                'a1z': consts.string.type.REAL,
                'a2x': consts.string.type.REAL,
                'a2y': consts.string.type.REAL,
                'a2z': consts.string.type.REAL,
                'a3x': consts.string.type.REAL,
                'a3y': None,
                'a3z': consts.string.type.REAL,
            },
            {
                'vx': consts.string.type.REAL,
                'vy': consts.string.type.REAL,
                'vz': consts.string.type.REAL,
                'a1x': consts.string.type.REAL,
                'a1y': consts.string.type.REAL,
                'a1z': consts.string.type.REAL,
                'a2x': consts.string.type.REAL,
                'a2y': consts.string.type.REAL,
                'a2z': consts.string.type.REAL,
                'a3x': consts.string.type.REAL,
                'a3y': consts.string.type.REAL,
                'a3z': None,
            },
        ]

    class Test_Mcnp(classes.Test_Mcnp):
        element = pymcnp.inp.surface.Box
        EXAMPLES_VALID = [consts.string.inp.surface.BOX]
        EXAMPLES_INVALID = ['hello']

    class Test_Draw(classes.Test_Draw):
        element = pymcnp.inp.surface.Box
        EXAMPLES = [consts.string.inp.surface.BOX]
